### ISSUE TITLE
Angular CLI Hangs up while running ng serve

### ISSUE THREAD

**Issue by faiztherocker** [angular-architects/module-federation-plugin#1]
### CLI HANGS UP TO 21% WHILE RUNNING NG SERVE OR YARN START

@manfredsteyer I tried using the @angular-architects/module-federation plugin by following the steps mentioned for using this library in a newly created Angular 11 project. However, the execution of the ng serve or yarn start halts up at 21% with the below mentioned message.

![Screenshot 2020-10-19 at 3 08 00 PM](https://user-images.githubusercontent.com/7435269/96428021-e842ac80-121c-11eb-8009-48362885f7db.png)

Could you please help me out if I am missing something here.

**Comment by rarmatei** [comment]
I was seeing the same - in my case my Angular versions were out of sync with each other

These are the versions I now use, and it works:

```json
"@angular-architects/module-federation": "1.0.2",
"@angular-devkit/build-angular": "0.1100.0-next.6",

// all angular packages are on this version
"@angular/core": "11.0.0-next.6",

"resolutions": {
    "webpack": "5.1.3"
  },
```

**Comment by manfredsteyer** [comment]
Hi,

thanks for reaching out. Yes, this is currently the solution. Just only go with next.6 for everything. Don't use a ~ prefix.

We are currently investigating the issues with next.7.

Best wishes,
Manfred
