### ISSUE TITLE
Module is not loaded with ng cli v11.1.1

### ISSUE THREAD

**Issue by lincetto** [angular-architects/module-federation-plugin#10]
After upgrading to @angular/cli to version 11.1.1 this module is not loaded due to the backslash presents in package.json for main and typings

` 
    "main": "src\\index.js",
    "schematics": "./collection.json",
  "builders": "./builders.json",
  "dependencies": {
    "@nrwl/workspace": "^10.3.0",
    "ngx-build-plus": "^10.0.0",
    "cross-spawn": "^7.0.3",
    "json5": "^2.1.3"
  },
  "typings": "src\\index.d.ts",
  "peerDependencies": {}
}
`

Changing to 

`"main": "src/index.js",
  "schematics": "./collection.json",
  "builders": "./builders.json",
  "dependencies": {
    "@nrwl/workspace": "^10.3.0",
    "ngx-build-plus": "^10.0.0",
    "cross-spawn": "^7.0.3",
    "json5": "^2.1.3"
  },
  "typings": "src/index.d.ts",
  "peerDependencies": {}
}
`

 makes the module loadable again.
If agree, I can file a pull request for this fix.

**Comment by lincetto** [comment]
The issue arise only on macos and linux machines, not in window machines.

**Comment by sauliuni** [comment]
@lincetto can you create a pull request? This is a breaking change also for me

**Comment by lincetto** [comment]
Unfortunately no, because this repo seems not aligned to the nom package published here 

https://www.npmjs.com/package/@angular-architects/module-federation

Indeed the package version is 1.2.3, here in the repo the source code refers to version 0.0.0, dependencies are not aligned with the one included in package.json inside nom package, etc..

@manfredsteyer is the source code available in order to patch it?

**Comment by sauliuni** [comment]
For a quick fix in my pipeline, I'm using the following bash commands
Mac:
`sed -i '' 's/src\\\\index.js/src\/index.js/g' ./node_modules/@angular-architects/module-federation/package.json`
Linux:
`sed -i 's/src\\\\index.js/src\/index.js/g' ./node_modules/@angular-architects/module-federation/package.json`
