### ISSUE TITLE
Live reload on host when remotes change

### ISSUE THREAD

**Issue by KyleThenTR** [angular-architects/module-federation-plugin#100]
Hello, is it possible for the host to reload the page when the remote's code changes?

**Comment by scottfwalter** [comment]
I've bookmarked this article but haven't tried the plugin mentioned here:  https://medium.com/@A__G__B/introducing-fmr-federated-module-reloading-820ec56256db.  Its worth a look.

**Comment by KyleThenTR** [comment]
> I've bookmarked this article but haven't tried the plugin mentioned here: https://medium.com/@A__G__B/introducing-fmr-federated-module-reloading-820ec56256db. Its worth a look.

FYI, I tried out that library and couldn't get it working. I used this instead https://www.npmjs.com/package/webpack-livereload-plugin and was able to get it working, just adding
```
new LiveReloadPlugin({port: 0, appendScriptTag: true}),
```
to all of my remotes plugins section

**Comment by mikezks** [comment]
It is now directly supported in der current @angular/cli and webpack version.
