### ISSUE TITLE
Support for Angular CLI 13

### ISSUE THREAD

**Issue by ShashankHegde16** [angular-architects/module-federation-plugin#101]
Please find the attachment. We are getting import.meta outside a module error when we use the latest 13.0.1 package with the angular 13. However it works fine with version 12.5.3 with angular 12.

![image](https://user-images.githubusercontent.com/47588129/142449291-0845912e-774c-48bf-94c2-477492f7f0fd.png)

**Comment by scottfwalter** [comment]
I believe this is the same issue as https://github.com/angular-architects/module-federation-plugin/issues/96

**Comment by manfredsteyer** [comment]
Hi,

thanks for pointing this out. Seems like, there is an issue with how Angular 13 uses webpack. We are on it!

Best wishes,
Manfred

**Comment by mikezks** [comment]
For further issues see https://github.com/angular-architects/module-federation-plugin/issues/96.
