### ISSUE TITLE
Build only remoteEntry with dependencies

### ISSUE THREAD

**Issue by rodrigo-garofalo** [angular-architects/module-federation-plugin#104]
There is a way run a build only with remoteEntry and his dependencies? removing index.html, main.ts, polyfill, etc?

**Comment by manfredsteyer** [comment]
Unfortunately not. However, you can just ignore what you don't need.

**Comment by manfredsteyer** [comment]
Btw: Normally, you also want to run remotes in standalone mode, e. g. for testing.

**Comment by rodrigo-garofalo** [comment]
Thanks for the answer.
in my case I created a way to run standalone in the development environment, however when deploying in production I configured entrypoint to be a separate router module.
The problem is that when it builds for prod, it creates the names with the hashes and makes a mess with the names of the files.
so I wondered if there wasn't a way when running "ng build --prod" the compiler would generate just the files needed for entrypoint
