### ISSUE TITLE
Current State: Issue with Angular 13

### ISSUE THREAD

**Issue by manfredsteyer** [angular-architects/module-federation-plugin#106]
Please see: https://github.com/angular-architects/module-federation-plugin/issues/96#issuecomment-981896034

**Comment by mikezks** [comment]
- first ng v13 integration https://github.com/angular-architects/module-federation-plugin/issues/96#issuecomment-981896034
- [migration guide ng v12 to ng v13](https://github.com/angular-architects/module-federation-plugin/blob/main/migration-guide.md)
- mapping b/w `@angular` version and `@angular-architects/module-federation` version https://github.com/angular-architects/module-federation-plugin/issues/96#issuecomment-994588837
- `@angular-architects/module-federation` v14 release https://github.com/angular-architects/module-federation-plugin/issues/96#issuecomment-997013146
- known CLI issue for `ng serve`: `import.meta` https://github.com/angular-architects/module-federation-plugin/issues/96#issuecomment-1000285956
