### ISSUE TITLE
How to resolve Micro Frontend Shell app throwing 'not a known element' error for child Micro app?

### ISSUE THREAD

**Issue by abigby** [angular-architects/module-federation-plugin#107]
I have all the appropriate modules imported in both the Shell(parent) app and Micro(child) app yet I get the error; specifically in my case 'mat-chip-list' is not a known element only when I launch the Shell(parent) app.

Is there a configuration I must have in my: webpack.config.js or nx.json or project.json or angular.json?

**Comment by manfredsteyer** [comment]
Hi,

hm, I guess you need to share Angular Material and all the used secondary entry points via all webpack.config-s (the one of the shell and the one of the micro frontend). Also, you need to import the Modules everywhere you need this shared mat-chip.list.
