### ISSUE TITLE
How to load module using the plugin-based approach ?

### ISSUE THREAD

**Issue by samvienne** [angular-architects/module-federation-plugin#111]
Hi,

I've been using module federation with the router approach where you can easily expose a module from your MFE. I've been trying to do the same with the plugin-based approach but when dynamically creating the component the createComponent() method only accept component type as parameter. 
Does anyone know how to use your exposed module with this plugin approach?

Thanks a lot

Plugin-based approach:  https://www.angulararchitects.io/en/aktuelles/dynamic-module-federation-with-angular-2/

**Comment by mikezks** [comment]
You need to use the NgModule factory, where your Component is declared and can then add the Component to your ViewContainer. Be aware that this works in a Module Federation single version setup only. For a multi version setup you need to use a CustomElement or Angular Root Component, but then w/o shared Dependency Injection tree.

**Comment by manfredsteyer** [comment]
+1

If you combine this [1] with a path mapped by module federation, it should work:
https://juristr.com/blog/2019/10/lazyload-module-ivy-viewengine/
