### ISSUE TITLE
Material Select not working when used in exposed component?

### ISSUE THREAD

**Issue by sajtdavid** [angular-architects/module-federation-plugin#113]
I followed the tutorial to build the Flights search project, and it worked well. Then I changed to expose only a component: 
`            exposes: {
                './FlightsSearch': './projects/mfe1/src/app/flights/flights-search/flights-search.component.ts',
            },   `
Then I added a Material Select field to the flights-search component:

```
<mat-select>
        <mat-option [value]="1">1</mat-option>
        <mat-option [value]="2">2</mat-option>
</mat-select>
```

I loaded the component using this code in the shell project:

```
    loadRemoteModule({
      remoteEntry: 'http://localhost:3000/remoteEntry.js', 
      remoteName: 'mfe1',
      exposedModule: './FlightsSearch'
    })
      .then(module => module.FlightsSearchComponent)
      .then(component => {
        const factory = this.resolver.resolveComponentFactory(component);
        const componentRef = (this.preview.createComponent(factory) as ComponentRef<any>);
      });
```

The component is loaded and contents are displayed. For the select, I got this error: 

`NullInjectorError: No provider for InjectionToken mat-select-scroll-strategy!`

I solved that by adding 

`"@angular/material/select": { singleton: true, strictVersion: true, requiredVersion: '12.2.13' },` 

to the shared modules.
There were no further errors, but the select does not open when the component is loaded at the shell (the select is displayed as empty, and its `options` list is empty, like there would be no mat-options inside). The select does work when it is opened directly at mfe1, or when copied to the shell. I tried to share further libraries like `@angular/animations` or `@angular/platform-browser` but it did not help. The select also worked, when the whole module was exposed. As far as I tested, all other elements are working fine.

How can I get the select to display the options properly? If necessary, I can upload the whole code. Thank you!

**Comment by vugar005** [comment]
@sajtdavid 
This is because you only import select, you should also import cdk and platform-browser. On my side, I did this(of course you should specify your version).
```
  shared: {
           "@angular/core": { strictVersion: true, requiredVersion: '12.2.15' },
           "@angular/common": { strictVersion: true, requiredVersion: '12.2.15' },
           "@angular/router": { strictVersion: true, requiredVersion: '12.2.15' },
           "@angular/material": { strictVersion: true, requiredVersion: '12.2.15' },
           "@angular/cdk": { strictVersion: true, requiredVersion: '12.2.15' },
           "@angular/platform-browser": { strictVersion: true, requiredVersion: '12.2.15' },
           }
```
