### ISSUE TITLE
Error when adding module-federation

### ISSUE THREAD

**Issue by DailisLangovskis** [angular-architects/module-federation-plugin#115]
Hello, I am trying out the module-federation plugin, following the [tutorial](https://github.com/angular-architects/module-federation-plugin/blob/main/libs/mf/tutorial/tutorial.md), but for some reason I am getting an error (following).

```
$ ng add @angular-architects/module-federation --project test --port 5000
Skipping installation: Package already installed
Unexpected token / in JSON at position 2155
```

My project is upgraded to angular 13.1.1 version and it also uses a small custom webpack config just for optimization.

**Comment by raitisbe** [comment]
Was due to comments in angular.json
