### ISSUE TITLE
core.js:6479 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'bindingStartIndex')

### ISSUE THREAD

**Issue by spoddutu** [angular-architects/module-federation-plugin#116]
Hi @manfredsteyer 
Need your help with this error, I have 2 apps
1. App1 is developed using Angular 13 with "@angular-architects/module-federation": "^14.0.1" and configured below too
    set tsconfig -> "target": "es2020",
    set  webpack.config -> scriptType: 'text/javascript', publicPath: "http://localhost:7000/",
2. App2 is developed using Angular 12 with "@angular-architects/module-federation": "14.0.0-rc.1",
3. App1 exposes a component and used below code to load in App2
    async ngOnInit() {
    const { BarChartComponent } = await loadRemoteModule({
      type: 'module',
      remoteEntry: 'http://localhost:7000/remoteEntry.js',
      exposedModule: './BarChart',
    });
    
    this.vcref.createComponent(
      this.cfr.resolveComponentFactory(BarChartComponent)
    );
  }
4.  When i try to run App2, i got below error
     core.js:6479 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'bindingStartIndex')
TypeError: Cannot read properties of null (reading 'bindingStartIndex')
    at Module.ɵɵelementStart (core.mjs:14503:46)
    at BarChartComponent_Template (bar-chart.component.html:1:1)
    at executeTemplate (core.js:9599:1)
    at renderView (core.js:9402:1)
    at renderComponent (core.js:10683:1)
    at renderChildComponents (core.js:9267:1)
    at renderView (core.js:9427:1)
    at ComponentFactory$1.create (core.js:25137:1)
    at ViewContainerRef.createComponent (core.js:23172:1)
    at bar-chart-host.component.ts:22:16
    at resolvePromise (zone.js:832:39)
    at zone.js:739:21
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    
 I went through several stackoverflows, but nothing helped. **I am also using @angular-builders/custom-webpack instead of Angular default builder**
 
 **Note: i have tried to set projects.projectName.architect.build.options.preserveSymlinks with true in angular.json in App2, but that is throwing loadRemoteModule not found error in angular/architects.**
 
 How should i slove this issue?

**Comment by mikezks** [comment]
Beginning with ng v13 the Angular framework uses ESM modules as build targets. Therefore the way on how to load Remotes changed with v14 of this library for default ng v13 apps.

Please use v12 of this library for Angular v12 apps. If you use `scriptType: 'text/javascript'` in your ng v13 app it should be possible to load it into v12 apps.

We may offer further guidance on how to support such scenarios easier.
