### ISSUE TITLE
remoteEntry.js cache busting

### ISSUE THREAD

**Issue by rdukeshier** [angular-architects/module-federation-plugin#118]
In production builds we get hashes in all our filenames for cache busting.  remoteEntry.js is the exception.  What is the recommended approach for cache busting this file?

**Comment by mikezks** [comment]
You can use:

- Webpack content hashes together with a discovery service
  - `filename: 'remoteEntry.[contenthash].js'`
- HTTP cache header or etags
- A changing query param like a timestamp for loading the remote
