### ISSUE TITLE
Unexpected error when trying to add the package

### ISSUE THREAD

**Issue by timtos** [angular-architects/module-federation-plugin#122]
Hello, we just switched to the latest nx version and after that, I wanted to try this package here. So I called

`yarn add @angular-architects/module-federation` (don't want to use npm as we are not using it)

but unfortunately always get 

`error An unexpected error occurred: "could not find a copy of browserslist to link in ...\\node_modules\\ngx-build-plus\\node_modules\\@angular-devkit\\build-angular\\node_modules\\postcss-preset-env\\node_modules
`

Did anyone try to install this package via yarn? Any ideas?
When I remove this package, everything is fine again...

**Comment by laryk9** [comment]
@timtos I had exactly the same problem. I just updated to the latest nx version again, deleted the yarn.lock, and tried to add the package again and it worked.
