### ISSUE TITLE
getting errors "TypeError: container.init is not a function, TypeError: container.get is not a function" while loading remote module using dynamic federation 

### ISSUE THREAD

**Issue by heynitish717** [angular-architects/module-federation-plugin#125]
Hi @manfredsteyer. Please guide on below issue.

I am using nrwl-nx-monorepo and have upgraded to the latest of:
1). angular - 13.1.3
2). @angular-architects/module-federation - 14.0.1
3). webpack - 5.60.0

I followed your migration guide at below link:
https://github.com/angular-architects/module-federation-plugin/blob/main/migration-guide.md

But yet when I try to load remoteModule into my host using dynamic federation I am getting below issues in my console:

![image](https://user-images.githubusercontent.com/13821117/151670736-646342d4-8982-4a5f-a2d7-7c02583e06e1.png)

Let me know if any more information needed.

**Comment by manfredsteyer** [comment]
Hi,

- Do you have ``target="es2020"`` in your global tsconfig.json?
- Do you use ``type:'module'`` when calling ``loadRemoteModule`` and ``loadRemoteEntry``?

**Comment by heynitish717** [comment]
> Hi,
> 
> * Do you have `target="es2020"` in your global tsconfig.json?
> * Do you use `type:'module'` when calling `loadRemoteModule` and `loadRemoteEntry`?

Hi @manfredsteyer , 
  1). Yes I have target="es2020" in global tsconfig.json (tsconfig.base.json in nx monorepo)
  2). Yes in my host app route file I have specified "type='module' ".

For reference I am providing below details:
1). Global tsconfig.base.json image.
2). Host app - routing file image, webpack.config.js image, main.ts image
3). Mfe app - webpack.config.js image


**Global tsconfig.base.json** 

![image](https://user-images.githubusercontent.com/13821117/151811078-abe09f2a-c97e-46b8-a784-db6bfbcf3ead.png)

**Host app**
routing file 
![image](https://user-images.githubusercontent.com/13821117/151811303-5213ed08-916b-47c5-b13e-82d508b3acd1.png)

main.ts
![image](https://user-images.githubusercontent.com/13821117/151811400-510e8c37-db29-49d6-8969-7273540f94f0.png)

webpack.config.json
![image](https://user-images.githubusercontent.com/13821117/151811682-4fd2b252-5946-46cd-b112-09611684e41b.png)

**Mfe app**
webpack.config.json
![image](https://user-images.githubusercontent.com/13821117/151811887-a1ac6161-46e7-4593-89ec-3aa10687eba6.png)

**Migration guide points which are now throwing error are:**
1). scriptType="text/javascript" - not able to use it now. Gives error "Invalid property".
2). In host app "main.ts" file can not write the below code:
import { loadRemoteEntry } from '@angular-architects/module-federation';
loadRemoteEntry({ type: 'module', remoteEntry: 'http://localhost:5005/remoteEntry.js'})
	.then(_ => import('./bootstrap').catch(err => console.error(err)))

It throw error.

I have a requirement where I have 5 microfrontends and have to load them conditionally inside the host app. 

Please have a look at the above observations.

**Comment by mikezks** [comment]
- to make sure, the config is correct please try to add the Module Federation setup with ng add.
- delete ".angular" folder after each config change to make sure no side-effects occur.
- please provide more details on the errors for "scriptType" and "main.ts.

**Comment by heynitish717** [comment]
> * to make sure, the config is correct please try to add the Module Federation setup with ng add.
> * delete ".angular" folder after each config change to make sure no side-effects occur.
> * please provide more details on the errors for "scriptType" and "main.ts".

Hi @mikezks
Below are the observations:
**Microfrontend successfully loading with [scriptType:"text/javascript"] setting**
1). Now I am able to use [scriptType:"text/javascript"]. I had done a mistake shown in comment ['equal' sign i was using in place of 'colon']
![image](https://user-images.githubusercontent.com/13821117/151860648-a7ba449e-5644-4b91-84d1-005cfd3a0005.png)

with above configuration in both host and mfe webpack.config.js and below host routing I am able to load mfe in host app
![image](https://user-images.githubusercontent.com/13821117/151861033-0d16040f-f510-4111-8100-85419361b303.png)

**But with ES6 module configuration in webpack.config.js it is not working and giving the same issue mentioned in my initial post**
1).  I already used below command format to add module federation to the host and mfe projects
![image](https://user-images.githubusercontent.com/13821117/151858994-d7c17480-1a6b-4c6d-9c05-9fbd6939e011.png)

2). I tried deleting the .angular folder after changes in webpack.config.js but still issue getting.

3). main.ts --> Let me elaborate on this
In the migration guide its is said to have below code in host app main.ts 
![image](https://user-images.githubusercontent.com/13821117/151861871-9a313910-1bdc-46a8-b90a-3a4b9b5d07de.png)

but on load in this case i get below error
![image](https://user-images.githubusercontent.com/13821117/151862100-da7655ae-8eb6-4376-b09c-1981d77302be.png)

-------------------on the other hand if I keep the default content in main.ts file as shown below i do not get issues
![image](https://user-images.githubusercontent.com/13821117/151862303-6003219a-0a5c-455f-8729-4f60b3ef2db0.png)

**Comment by mikezks** [comment]
I tested w/ @angular@13.1.3 and @angular-architects/module-federation@14.0.1 successfully. Only difference, I used a CLI app and not Nx.
Works with fully dynamic loading and main.ts based runtime loading.

Feel free to provide a demo repo that shows your issue.
