### ISSUE TITLE
platformCache.platform.get is not a function

### ISSUE THREAD

**Issue by Alexandr-Baluhin** [angular-architects/module-federation-plugin#126]
**@angular-architects/module-federation-tools@^14.0.0** is not compatible with **@angular-architects/module-federation-tools@^12.5.3** when using **bootstrap** function to load Angular 13 MFE into Angular 12 Shell.

![image](https://user-images.githubusercontent.com/6184519/151695830-99bcdf97-0533-4ee6-818f-621f16f9db08.png)

problem is with platform cache
in 12 version it was just plain object

![image](https://user-images.githubusercontent.com/6184519/151695854-d692c24f-d764-4438-918c-3e44916aa886.png)

but in 14 version it now Map

![image](https://user-images.githubusercontent.com/6184519/151695869-50eb0826-ec9c-4a1e-89e3-19210ba03d05.png)

We need to add fallback here to support multi-version setup

**Comment by mikezks** [comment]
Please check first, whether your ng 13 MFE uses the latest version of `@angular-architects/module-federation-tools`, which is currently `14.0.1`.

**Comment by r1m** [comment]
@mikezks, the legacy mode is working fine, however it does not allow a progressive migration. It's either all modules working in legacy, either all in new mode.
Can we add some fallback to legacy if existing `platform` is not a map ?
