### ISSUE TITLE
Use module-federation-runtime in module-federation-tools

### ISSUE THREAD

**Issue by wszydlak** [angular-architects/module-federation-plugin#128]
Hello :) 

We are using `@angular-architects/module-federation-runtime` for utilities to load remote modules/components, but we don't use package `@angular-architects/module-federation` as we don't need architect.

Currently `@angular-architects/module-federation-tools` requires in peerDependencies usage of `@angular-architects/module-federation`, but it uses functions that are avaiable in `@angular-architects/module-federation-runtime`.

It would be great to have a chance to use `@angular-architects/module-federation-tools` with installing only `@angular-architects/module-federation-runtime`. Maybe this should even be not peer by regular dependency?

Are there any plans to improve that support?

**Comment by skorzyk** [comment]
I also faced this problem. it would be great if you could improve this support

**Comment by wszydlak** [comment]
Seems to be resolved by 544607fd7a8b127d1a02b4b7ea9afd48f49e4961
