### ISSUE TITLE
is it possibile to use this using multi repositories? 

### ISSUE THREAD

**Issue by thomasbricchi** [angular-architects/module-federation-plugin#134]
i would like to use module federation without using monorepo. is it possible?

**Comment by windbeneathyourwings** [comment]
Yes, it is. I'm using module federation with a separate repo for the micro-front end.

**Comment by thomasbricchi** [comment]
thank you for the response.
I saw that you are using ssr, I would like to use two simple angular applications. 
regarding the microfrontends is ok, but how should I configure the shell?

**Comment by thomasbricchi** [comment]
actually in my projects

shell poer 4200:
main.ts 
<code>
Promise.all([loadRemoteEntry({type: 'module', remoteEntry: 'http://localhost:3000/remoteEntry.js'})])
  .catch(err => console.error('Error loading remote entries', err))
  .then(() => import('./bootstrap')).catch(err => console.error(err));
<code>

routing 
<code>
{
    path: 'mfe1',
????
  },<code>


MICROFRONTEND:
<code>

      name: 'mfe1',
      filename: 'remoteEntry.js',
      exposes: {
        './VolierModule': './src/app/volier/volier.module',
      },
<code>

I cannot understand how can works routing

**Comment by vugar005** [comment]
Hi @thomasbricchi , I had same desire to have micro front end in different workspace, you can either check mine https://github.com/vugar005/module-federation-space or Manfred repo https://github.com/manfredsteyer/multi-framework-micro-frontend

**Comment by mikezks** [comment]
@windbeneathyourwings, @vugar005, thanks for your support!

**Comment by windbeneathyourwings** [comment]
@mikezks 

Through a bunch of trail and error I've been able to get this all working with your workflow designer.

I copied the workflow designer repo and modified it to be compatible with my dependency versions. I was then able to load the workflow designer apps into my shell app un-styled.

https://ng-druid.github.io/workflow-designer-v2

Shell: https://github.com/ng-druid/ipe
Workflow Designer: https://github.com/ng-druid/workflow-designer

This is becoming a pivotal piece of my project. I'm currently working on loading unknown remote modules at runtime as extension libraries. So users will be able to load effectively extensions as separate repos that can add new plugins dynamically at runtime.

**Comment by windbeneathyourwings** [comment]
This is the next evolution. Compiling modules at runtime into Angular shell that provide new functionality via plugin system which become immediately available.

* https://ng-druid.github.io/tractorbeam-test-v3
* https://ng-druid.github.io/tractorbeam-test-v3/manage
* 
On the manage page click the (x) in the upper right to reveal the download context. Click the download context link and the modal containing the info to load the remote DownloadModule extension is shown.

**Comment by ktsangop** [comment]
Sorry to bump this but after reading the answers here, I'm still not sure if the module federation plugin works for different projects.
All the example links are either dead or point to monorepos.
Am I missing something? 
Thanks in advance!

**Comment by ng-druid** [comment]
Thought I would come back and update this now that we have a working plugin system for Angular using modular federation. Our climate aware CMS built with Angular recently upgraded to Angular 16 uses module federation for adding plugins that extend the system.

https://github.com/rollthecloudinc/quell-plugin
