### ISSUE TITLE
SVG files not display from assets folder

### ISSUE THREAD

**Issue by ofirrifo** [angular-architects/module-federation-plugin#138]
SVG files not display from assets folder.

I clone the examples repo `manfredsteyer/module-federation-plugin-example` 

I added SVG file under `module-federation-plugin-example/tree/main/projects/mfe1/src/assets`
and added to this file below img html tag with the SVG src

**projects/mfe1/src/app/flights/flights-search/flights-search.component.html**
```html
<img width="100px" src="../../../../assets/notification-active-gray.svg" alt="">
```

I executed both shell and remote projects but the SVG in the shell not display.
in the remote as stand alone it do display.

I expected it to work with this config `webpack.config.js`

```
output: {
    uniqueName: "mfe1",
    publicPath: "http://localhost:3000/"
  },
```

**Comment by FredBlondel** [comment]
Hello
I think the answer is the same as here: https://github.com/angular-architects/module-federation-plugin/issues/90

**Comment by ofirrifo** [comment]
@FredBlondel Hello,

It not the same as png, jpg files are workin as should.
The issue is only with SVG.

**Comment by ofirrifo** [comment]
from @manfredsteyer https://www.youtube.com/watch?v=pD8VaBdU1f8&feature=youtu.be minute 16:34 it should work

**Comment by ofirrifo** [comment]
@manfredsteyer can you please reopen this issue please.
It still not work

**Comment by LironHazan** [comment]
I couldn't get it to work either,
my repos are separated as well,
should I workaround it as mentioned in [#90  ](https://github.com/angular-architects/module-federation-plugin/issues/90) ?
