### ISSUE TITLE
Adding to existing project: Cannot set properties of undefined (setting 'extraWebpackConfig')

### ISSUE THREAD

**Issue by rcmosher** [angular-architects/module-federation-plugin#140]
I'm attempting to start using module-federation with an existing project. When `ng add`ing module federation I get the following error: `Cannot set properties of undefined (setting 'extraWebpackConfig')`

Full output:
```
> ng add @angular-architects/module-federation --project my project --port 6010
ℹ Using package manager: npm
✔ Found compatible package version: @angular-architects/module-federation@14.1.1.
✔ Package information loaded.

The package @angular-architects/module-federation@14.1.1 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
Cannot set properties of undefined (setting 'extraWebpackConfig')
```
I'm not sure where to start on debugging this. It seems similar to the [issue 99](https://github.com/angular-architects/module-federation-plugin/issues/99) with the error worded differently, though we're not using Nx: 

Version info
```
>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.1.2
Node: 16.13.2
Package Manager: npm 8.3.0
OS: linux x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.5.2
typescript                      4.5.4
```

**Comment by rcmosher** [comment]
After doing a sample project from scratch I realized the error is probably coming from adding the `extraWebpackConfig` property in one of several places in `angular.json`. Investigation showed my project's `angular.json` did not have `production` listed under `projects.project-name.architect.build.configurations` (we have a few different production configurations, with nothing named "production").

I'm not sure if it is worthwhile to support this deviation from convention. But there could definitely be a better error message. Indicating the file and property tree being modified would help with diagnosing the issue.

**Comment by manfredsteyer** [comment]
Thanks for pointing this out.

**Comment by emaswebdesign** [comment]
@rcmosher May I ask how did you fix it. I have the same proble. Property in my angular.json file is named "prod" and I get this error Cannot set properties of undefined (setting 'extraWebpackConfig') Is there any workaround?? Amy app is big and I don't want to chang this name in angular.json file. Thank in advance

**Comment by rcmosher** [comment]
@emaswebdesign I just added a `production` entry under projects > _projectname_ > architect > build > configurations in the angular.json file. Not a great solution since it isn't intended for use, but it works around the issue.

**Comment by richardgyq** [comment]
Thanks @rcmosher !
In additional to adding a "production" node under projects.project-name.architect.**build**.configurations, I had to add a "production" node under projects.project-name.architect.**serve**.configurations as well. I'm using Angular 16.
