### ISSUE TITLE
Problem with 14.1.1: Could not find the 'ngx-build-plus:dev-server

### ISSUE THREAD

**Issue by fabiostrada** [angular-architects/module-federation-plugin#142]
Hi. I updated the version of module-federation-plugin of my angular application. When I start my application, I've got this error:

```Could not find the 'ngx-build-plus:dev-server' builder's node package```

**Comment by manfredsteyer** [comment]
+1 -- please just add this lib. For new projects, our ng-add respective init schematic adds it automatically.
