### ISSUE TITLE
Size of exposed modules is too big

### ISSUE THREAD

**Issue by maxgonzaga** [angular-architects/module-federation-plugin#150]
On my Angular project, there is a dependency on the components library DevExtreme, and I am in a quandary as how to share this dependency among the exposed modules. The situation is as follows.

When that dependency is shared, like showed in the following screen capture, the size of the exposed modules go fine, about 800 kB, which is fine. However, my `remoteEntry` go about 10 MB, which makes the child app take too long to load.
![image](https://user-images.githubusercontent.com/37736133/156856429-9f20b5e5-8f27-446d-bfd8-bf1617fe9194.png)

On the other side, when I do not share DevExtreme, the size of the exposed modules go about 3 MB, which makes the overall experience on the app slow, whilst the size of the `remoteEntry` is fine, around 1,7 MB.
![image](https://user-images.githubusercontent.com/37736133/156856225-6d8b1337-3919-4544-8ec8-afa59be19aeb.png)

I tried tweaking the sharing options in various way, but without success.

**Comment by manfredsteyer** [comment]
Hi,

what happens if you set eager to false?

**Comment by maxgonzaga** [comment]
Setting eager to false used to give me an error saying that devextreme is not available for eager consumption. But surprisingly it seems to be working now. The problem now is that I have a 7 MB lazy chunk file, that is the devextreme-angular package. Since it is loaded only once when the shell app first renders a module from the child app, it is ok, and it's better than a 10 MB remote entry…
![image](https://user-images.githubusercontent.com/37736133/157747804-909383b1-a305-4daa-979d-23e5a0f8b65c.png)

**Comment by manfredsteyer** [comment]
Awesome. You get this "not available for eager consumption" error if you don't bootstrap asynchronously. This is the reason why the plugin makes ```main.ts`` importing the ``bootstrap.ts`` via a dynamic (and hance async) ``import``. Every time, module federation sees an import statement, it loads the shared libs it needs for the chunk behind it.

**Comment by mayank714** [comment]
@manfredsteyer  @maxgonzaga  How and where to set eager as false
