### ISSUE TITLE
Can't share @angular/material/input

### ISSUE THREAD

**Issue by houdass** [angular-architects/module-federation-plugin#152]
Hello world,

I am getting the following error when I try to navigate from first-web-client to second-web-client:

```
ERROR Error: Uncaught (in promise): Error: Unsatisfied version 13.2.2 from first-web-client of shared singleton module @angular/material/input (required ^13.2.3)
Error: Unsatisfied version 13.2.2 from first-web-client of shared singleton module @angular/material/input (required ^13.2.3)
```

I am using buttons, tables, icons from **@angular/material**, everything works well, but not inputs.

**Shell:**

_package.json_
```
"dependencies": {
    ...
    "@angular/material": "~13.2.3",
    ....
}
```

_custom-webpack.config.ts_

```
'@angular/material': {
    singleton: true,
    strictVersion: true,
    requiredVersion: '^13.2.2',
    eager: true
},
```

**first-web-client:**

_package.json_

```
"dependencies": {
    ...
    "@angular/material": "~13.2.2",
    ...
}
```

_custom-webpack.config.ts_

```
'@angular/material': {
    singleton: true,
    strictVersion: true,
    requiredVersion: '^13.2.2',
    eager: true
},
```

**second-web-client:**
_package.json_
```
"dependencies": {
    ...
    "@angular/material": "^13.2.3",
    ...
}

```
_custom-webpack.config.ts_
```
'@angular/material': {
    singleton: true,
    strictVersion: true,
    requiredVersion: '^13.2.2',
    eager: true
},
```

Any idea why **@angular/material/input** is the only one that cause this issue? When I remove the `import { MatInputModule } from '@angular/material/input';` from code, I have no issue, again using table, icon, button … works fine.

Thanks in advance.

**Comment by manfredsteyer** [comment]
Hi,

you have to share each secondary entry point separately. Hence, you need another entry for @angular/material/input:

```javascript
'@angular/material/input': {
    singleton: true,
    strictVersion: true,
    requiredVersion: 'auto',
},
```

Our share helper also supports an includeSecondaries property for importing all secondary entrypoints:

```javascript
'@angular/material': {
    singleton: true,
    strictVersion: true,
    requiredVersion: 'auto',
    includeSecondaries: true
},
```
