### ISSUE TITLE
Expose option to not open browsers for mfe's when using `run:all`

### ISSUE THREAD

**Issue by k-schneider** [angular-architects/module-federation-plugin#155]
Looks like this is hardcoded at the moment into `mf-dev-server.js` but I'd really like the option to not have this occur.  Being able to run all of them at once is super useful but having to close a ton of unnecessary browser tabs each time is not cool.  Thanks!

**Comment by manfredsteyer** [comment]
It's now implemented with version 14.3. You can pass the names of the apps you want to start. If you don't pass names, all apps (but e2e apps) are started.

**Comment by svella-at-nice** [comment]
@manfredsteyer - I was looking for this functionality as well, but as far as I can tell 14.3 doesn't provide it. What I think we are both looking for is for the servers to start for all the apps, but for the browser to only start for 1 of the apps (i.e., the ability to omit the `-o` option from the `ng serve` command for all but the designated app.
