### ISSUE TITLE
Project Not Working after upgrading to ng 11.1.4 and module federation 1.2.3

### ISSUE THREAD

**Issue by charles-7StarsSolutions** [angular-architects/module-federation-plugin#16]
I add an old project (PRJ1) which was working. This project is in Angular 11.0.7 and module federation 1.2.2

I create a new project (PRJ2) with the last version of Angular (11.1.4) and module federation 1.2.3.
This project doesn't start and doesn't build.

I have updated PRJ1 to 11.1.4 and have the same problem.
I downgraded PRJ2 to 11.0.7 and it works !!! (i have used the working package.json from PRJ1).

package.json files that is working :
[package.working.json.txt](https://github.com/angular-architects/module-federation-plugin/files/5976127/package.working.json.txt)

package.json files that is not working : 
[package.notworking.json.txt](https://github.com/angular-architects/module-federation-plugin/files/5976128/package.notworking.json.txt)

**Comment by charles-7StarsSolutions** [comment]
I have upgraded the working project (angular 11.0.7) to module federation 1.2.3. And it is working. 
There seems there is an incompatibility between module federation 1.2.3 and angular 11.1.4.

**Comment by Al00X** [comment]
@manfredsteyer There's a bug with `license-webpack-plugin@2.3.11` which causes this issue and application becomes unbuildable.

The author of `license-webpack-plugin` fixed this bug in version `2.3.13` as he said in this issue :
[https://github.com/xz64/license-webpack-plugin/issues/95](url)

Appreciate if you update this dependency on module federation.

**Comment by lincetto** [comment]
@Al00X please could you post the correct link to the issue of license-webpack-plugin? Thanks

**Comment by manfredsteyer** [comment]
Thanks for this info. Let me check this asap. Hoewever, I also had the impression that there is an issue with Angular 11.1 and Module Federation. With 11.0 everything is fine and with 12.x everything should be fine too, b/c it will contain a stable webpack5 integration.

**Comment by manfredsteyer** [comment]
It's also resolved for version 12 of this lib
