### ISSUE TITLE
Getting started tutorial issue, port 5000 doesn't work on MacOS

### ISSUE THREAD

**Issue by marcellkiss** [angular-architects/module-federation-plugin#165]
The ['getting started tutorial'](https://github.com/angular-architects/module-federation-plugin/blob/main/libs/mf/tutorial/tutorial.md) is using port 3000 and port 5000 to show a module-federation example. 

Switching to the `ngx-build-plus` builder and `port 5000` is causing a silent error on `serve`, when the port is already in use. ControlCenter is using port 5000 on MacOS by default, but the `serve` command doesn't show an error:
![Screenshot 2022-04-12 at 08 10 49](https://user-images.githubusercontent.com/2832556/162892423-9be07379-ff67-4a16-9083-59f6b03b1d6a.png)
Although, opening `http://localhost:5000` in the browser gives a 403 error.

TODO:
 - Fix the tutorial page and use another port (eg. 4200) -> I'll open a PR for that
 - Fix ngx-build-plus and show a proper error message if the port is already in use 
 (not relevant for module-federation-plugin)

**Comment by manfredsteyer** [comment]
Thanks for this hint, Marcell!

**Comment by manfredsteyer** [comment]
The updated tutorials now use port 4200 and 4201
