### ISSUE TITLE
cannot resolve @angular-architects/module-federation due to improper main path

### ISSUE THREAD

**Issue by kylecannon** [angular-architects/module-federation-plugin#17]
I noticed that when installing the package that I was getting issues with actually requiring in the file. I noticed that the package.json main property is: `  "main": "src\\index.js",` when it should be `  "main": "src/index.js",`

If I pull down this project and run `yarn build mf`, it generates the correct path.

<img width="1151" alt="Screen Shot 2021-02-15 at 10 58 20 AM" src="https://user-images.githubusercontent.com/867978/107984471-d8459a00-6f7c-11eb-9157-b9990221d722.png">

Here is the error:

```
➜  ngx-dashboard-widget-sandbox-example git:(feature/mfe) node   
Welcome to Node.js v14.15.3.
Type ".help" for more information.
> require('@angular-architects/module-federation')
Uncaught:
Error: Cannot find module '/Volumes/Development/ngx-dashboard-widget-sandbox-example/node_modules/@angular-architects/module-federation/src\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/Volumes/Development/ngx-dashboard-widget-sandbox-example/node_modules/@angular-architects/module-federation/package.json',
  requestPath: '@angular-architects/module-federation'
}
> 
```

Changing the above main property value allows for the module to work.

This also looks to have the same issue on the `typings` property as well.

**Comment by lincetto** [comment]
@kylecannon I think this related also to https://github.com/angular-architects/module-federation-plugin/issues/10
In addition in this repository there is no source cove of the latest version of the packages published in npm, so we cannot find and file a PR to solve this kind of issue.. :(

**Comment by kylecannon** [comment]
this is my workaround for now.

create `fix-module-federation-package.js`
```javascript
const fs = require('fs/promises');
const path = require('path');

const packageJsonPath = path.join(
  process.cwd(),
  'node_modules/@angular-architects/module-federation/package.json'
);

fs.readFile(packageJsonPath, { encoding: 'utf8' })
  .then((fileContents) => {
    const parsedContents = JSON.parse(fileContents);
    return {
      ...parsedContents,
      main: parsedContents.main.replace('\\', '/'),
      typings: parsedContents.typings.replace('\\', '/'),
    };
  })
  .then((sanitizedContents) => JSON.stringify(sanitizedContents, null, 2))
  .then((newContents) =>
    fs.writeFile(packageJsonPath, newContents, { encoding: 'utf8' })
  );
```

add into postinstall in your own package.json

```    "postinstall": "node ./decorate-angular-cli.js &&  node fix-module-federation-package.js && ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
```

**Comment by manfredsteyer** [comment]
Thanks for pointing this out and for providing workarounds. Seems to be a npm publish issue. I'll try to publish a working version 1.2.4 soon. Also, this issue is gone with version 12 of this lib.
