### ISSUE TITLE
configure module federation shell and microfrontend, load remoteentry.js but show empty page

### ISSUE THREAD

**Issue by EmranSa** [angular-architects/module-federation-plugin#177]
i configure module federation, and use angular 13

webpack.config.js in host/shell : 
![003](https://user-images.githubusercontent.com/7761443/168458778-8a14169f-5377-492d-8a9e-d4126980edf5.png)

app-routing.module.ts in host/shell:
![004](https://user-images.githubusercontent.com/7761443/168458793-352dcf85-feeb-4ae3-a85d-1d94df06aaf0.png)

webpack.config.js in microfrontend: 
![005](https://user-images.githubusercontent.com/7761443/168458806-05336d35-b8bc-4d74-9e1d-225aabc1a3ae.png)

app-routing.module.ts in microfrontend:
![006](https://user-images.githubusercontent.com/7761443/168458813-1f794bd5-fcfe-4de0-82f3-5ad5987dc63b.png)

but when open url http://localhost:5001/wi show empty page:
![001](https://user-images.githubusercontent.com/7761443/168458843-439482a4-5732-46b9-b59c-1b3e5c03c7ae.png)

and remoteentry.js is loaded :
![002](https://user-images.githubusercontent.com/7761443/168458874-bf9a92d9-bfc3-4caf-be10-6909052b18aa.png)

first i start ng microfrontend with ng s, after that start shell
i open microfrontend url with port 3000 and show my message

but why it show empty page on shell app?

**Comment by flys1ck** [comment]
I am having the same issue. Could you please explain what fixed it for you?
