### ISSUE TITLE
Error importing external angular library

### ISSUE THREAD

**Issue by miguelguerreroadl** [angular-architects/module-federation-plugin#18]
Hi, i am having issues importing an external angular library.

When i try to import it, the build hangs up. i tried to run first the project and then add de import and the terminal shows me this error:

```Compiled successfully.
✔ Browser application bundle generation complete.
⠹ Generating browser application bundles (phase: building)...(node:34635) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.modules was changed from Array to Set (using Array method 'find' is deprecated)
⠸ Generating browser application bundles (phase: sealing)...
```

anyone knows what this error is about? thanks!

**Comment by lincetto** [comment]
@miguelguerreroadl please could you try to launch ng serve or ng build command not from the root of the project but inside the src folder?
In our case it solved the hanging build, but this is a weird behaviour..

**Comment by miguelguerreroadl** [comment]
@lincetto i looked into the code and i found out that the problem is not importing an angular library, the problem is with an specific library called `node-forge`, when yout create an angular project with yarn an add module federation the project doesn't transpile.

Do you know guys what could be the problem with this particular library?

**Comment by glebmachine** [comment]
Oh, got the same, every workspace lib hansa building process : /

**Comment by manfredsteyer** [comment]
very likely you ran into one of the issues outlined at the end of the readme, e. g. the styleUrls issue.

With Version 12 of this lib, it should work. Can you give it a try?

**Comment by glebmachine** [comment]
Update to 12 helps, Thanks!
