### ISSUE TITLE
Getting module load error

### ISSUE THREAD

**Issue by rupamroy** [angular-architects/module-federation-plugin#185]
Hi I am following the enterprise-angular 2021 edition , I am using angular 14 ,and trying to load a mfe (called `admin`) through webpack module federation. But i am getting the following runtime error with my definition of shell --> remotes. 

```
Failed to resolve module specifier "admin@http://localhost:3000/remoteEntry.js". Relative references must start with either "/","./", or "../". 

```
any idea why that could be happening.

**Comment by manfredsteyer** [comment]
Please have a look at these two migration guides:
https://github.com/angular-architects/module-federation-plugin/blob/main/migration-guide.md
