### ISSUE TITLE
remote component - consume statically

### ISSUE THREAD

**Issue by tomani77** [angular-architects/module-federation-plugin#19]
This is not a issue rather a question. how to consume a component (available at remote) at design time ( without componentFactoryResolver)

exposes: {
 "component": ".//src/app/app.component.ts"
}
while importing 
import {component} from "mfe@component" 
I am getting build error "cannot find module "mfe1@component"

how to consume remotely exposed component at design time

**Comment by manishxpo** [comment]
Hello @manfredsteyer, could you advice on above. I have similar scenarios where I have to consume remote services as well.

**Comment by tomani77** [comment]
Hello @manfredsteyer did you get chance to look into the above mentioned issue

**Comment by manfredsteyer** [comment]
I think it should be mfe/component. If you don't want to use the componentFactoryResolver you could try the directive *componentOutlet shipped with Angular.
