### ISSUE TITLE
NX 14 and angular 14: cannot find '@angular/platform-browser' 

### ISSUE THREAD

**Issue by yntelectual** [angular-architects/module-federation-plugin#191]
hi
I have an NX monorepo, which I recently updated to v14:

```
"@angular-architects/module-federation": "^14.3.8",
 "@angular/animations": "14.0.2",
"@angular/cdk": "14.0.2",
"@angular/common": "14.0.2",
"@angular/compiler": "14.0.2",
"@angular/core": "14.0.2",
"@angular/forms": "14.0.2",
"@angular/platform-browser-dynamic": "^14.0.2",
"@angular/router": "14.0.2",
"@nrwl/angular": "14.3.6",
```
I created a new Angular app in the workspace and installed the module-federation as described in the docu - using type dynamic-host:

```
npm install @angular-architects/module-federation
ng g @angular-architects/module-federation:init --type dynamic-host
```

The generated webpack.config.js looks like this:
```
const { shareAll, withModuleFederationPlugin } = require('@angular-architects/module-federation/webpack');
module.exports = withModuleFederationPlugin({
  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
  },
});
```

If I run the blank app with Module federation enabled, I get the following error:
```
main.ts:1 Error: Cannot find module '@angular/platform-browser'
    at webpackMissingModule (consumes:134:161)
    at consumes:134:269
```

I understand that the `shareAll` resolves dependencies from `package.json`, should it therefore be used in NX repos, or should we stick to the old format? The example repo does not use NX, do we have any example repo we could use as baseline for NX repos?

Thanks

**Comment by manfredsteyer** [comment]
What happens if you npm install @angular/platform-browser?

**Comment by yntelectual** [comment]
Hi Manfred, I believe it was caused by corrupted node_modules. I have deleted it along with package lock, installed again and everything works. I have still switched the the ,,old"  `share` instead of `shareAll` so that not all top level dependencies are mapped as shared modules.
Thanks
