### ISSUE TITLE
Cannot find module 'webpack/lib/container/ModuleFederationPlugin'

### ISSUE THREAD

**Issue by hmaidithamer** [angular-architects/module-federation-plugin#20]
Hello @manfredsteyer 
I have an issue when I add module-federation-plugin using ng add @angular-architects/module-federation
with nx projects it add webpack.config.js for each project 
![image](https://user-images.githubusercontent.com/12519197/109061831-6fca8b80-76e7-11eb-87ae-2838fc59db01.png)
 but when I run npm start I get this issue :
![error](https://user-images.githubusercontent.com/12519197/109061927-925ca480-76e7-11eb-8a74-a84886d431a7.png)
any idea about this plz ?

**Comment by otoming** [comment]
Hey
It looks you are using webpack 4, not 5.

**Comment by glebmachine** [comment]
@hmaidithamer 
please add this to `package.json`
```json
  "resolutions": {
    "webpack": "5.27.2"
  }
```

**Comment by manfredsteyer** [comment]
+ you have to install the deps with yarn.

Beginning with version 12 you can also use npm and you don't need this resolutions section anymore.

**Comment by choicevine** [comment]
you can add the module by using:

const { ModuleFederationPlugin } = require('webpack').container;

**Comment by choicevine** [comment]
you can structure your webpac.config.js as this:

const HtmlWebpackPlugin = require('html-webpack-plugin');
const { ModuleFederationPlugin } = require('webpack').container;
//const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederaionPlugin')

module.exports = {
  mode: 'development',
  devServer: {
    port: 8081,
  },
  plugins: [
      new ModuleFederationPlugin({
          name: '....',
          filename: '.....',
          exposes: {
                ' ......'
          },
      }),
    new HtmlWebpackPlugin({
      template: './public/index.html',
    }),
  ],
};

**Comment by choicevine** [comment]
..... tends to means your code structure

**Comment by zrafio** [comment]
> * you have to install the deps with yarn.
> 
> Beginning with version 12 you can also use npm and you don't need this resolutions section anymore.

@manfredsteyer I'm using nx/cli (nx v12) -> empty preset then generated an angular (v12) host app with the mfe option

**Comment by xubalachandran** [comment]
I tried updating the code structure with 
// const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const { ModuleFederationPlugin } = require('webpack').container; 

-- not working

Also "resolutions": {
    "webpack": "^5.0.0"
  },  -- not working

@manfredsteyer -- I am working on  https://github.com/manfredsteyer/module-federation-plugin-example and have same error

**Comment by eolamisan** [comment]
> I tried updating the code structure with // const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin"); const { ModuleFederationPlugin } = require('webpack').container;
> 
> -- not working
> 
> Also "resolutions": { "webpack": "^5.0.0" }, -- not working
> 
> @manfredsteyer -- I am working on https://github.com/manfredsteyer/module-federation-plugin-example and have same error

It looks like you can specify resolution on the root level package. Then it worked for me.
