### ISSUE TITLE
Can't resolve '@angular-architects/module-federation' when routing to dynamic microfrontends

### ISSUE THREAD

**Issue by eironman** [angular-architects/module-federation-plugin#21]
Hello, I have been following the steps at https://www.angulararchitects.io/ for module federation, and it worked fine until I tried to route dynamic modules. I get this error when I start the shell app:

[...]  Error: Module not found: Error: Can't resolve '@angular-architects/module-federation' [...]

![Captura de pantalla de 2021-03-03 18-14-00](https://user-images.githubusercontent.com/1751920/109844313-4dd38a80-7c4c-11eb-8ddc-982365a68a67.png)

Before adding the funcion 'loadRemoteModule' it was working. This is my package.json:

![Captura de pantalla de 2021-03-03 18-16-39](https://user-images.githubusercontent.com/1751920/109844662-a6a32300-7c4c-11eb-9394-91321e6927e6.png)

**Comment by rkristelijn** [comment]
I ran into the same issue. Are you running linux or macos by any chance? Then in `.1.2.3` you can temporarily fix this in the `/node_modules/@angular-architects/module-federation/package.json` file.

change:
```json
"main": "src\\index.js",
```

to 
```
"main": "src/index.js",
```

@manfredsteyer I can't find this in the code, does have anything to do how you publish to npm?

**Comment by eironman** [comment]
Thanks @rkristelijn, that change worked. I am using linux, Ubuntu 20. I imagine this will be fixed soon.

**Comment by lincetto** [comment]
@eironman unfortunately this repo seems not aligned with the npm package and we need to create a local copy of the package to apply the same patch you suggested. Many other open issues are referring to the same root cause. I asked many times to have the code aligned in order to file a pull request, but no answers til now.

**Comment by michael-golden** [comment]
Thank you @rkristelijn  - confirmed that that did work building on AWS codebuild ( aws/codebuild/standard:5.0).

**Comment by rkristelijn** [comment]
Until @manfredsteyer has time to look at our issues, you could use my fork instead, where this issue is fixed. I'll accept other merge requests too.

What I did is, I forked this repo. Then I copied the contents of my `node_modules` on top of it, so it is in line with the `1.2.3` version. Then I fixed #21 as described above and created the tag `1.2.4-beta.1`.

You can use it this way:

- Instead of `yarn add @angular-architects/module-federation`
- ... you use`yarn add git+https://github.com/rkristelijn/module-federation-plugin.git#1.2.4-beta.1`

instead of
```ts
const mf = require("@angular-architects/module-federation/webpack");
```

you use
```ts
const mf = require("@rkristelijn/module-federation/webpack");
```

If desired I can bring this to npm too, but for this I'm unsure about bypassing @manfredsteyer

**Comment by michael-golden** [comment]
@rkristelijn 
I was able to use patch-package to generate a patch until a PR is released:
below is the diff that I manually created:

### @angular-architects+module-federation+1.2.3.patch
```
diff --git a/node_modules/@angular-architects/module-federation/package.json b/node_modules/@angular-architects/module-federation/package.json
index d9245e2..17027ea 100644
--- a/node_modules/@angular-architects/module-federation/package.json
+++ b/node_modules/@angular-architects/module-federation/package.json
@@ -11,7 +11,7 @@
     "email": "manfred.steyer@gmx.net",
     "url": "https://www.angulararchitects.io"
   },
-  "main": "src\\index.js",
+  "main": "src/index.js",
   "schematics": "./collection.json",
   "builders": "./builders.json",
   "dependencies": {
@@ -20,6 +20,6 @@
     "cross-spawn": "^7.0.3",
     "json5": "^2.1.3"
   },
-  "typings": "src\\index.d.ts",
+  "typings": "src/index.d.ts",
   "peerDependencies": {}
 }
```

**Comment by eironman** [comment]
@michael-golden, I've tried using patch-package but I cannot get it to read changes in package.json. If I make changes to files in src folder it works. I am going to use @rkristelijn branch until the change is official.
Thank you both!

**Comment by anatolitrifonov** [comment]
I ran into today. Sad that this is broken.
Anyone looked into why this works with this package.json from the example repository?
https://github.com/manfredsteyer/module-federation-plugin-example/blob/main/package.json
@rkristelijn thank you for pointing to the temp fix.

**Comment by smasala** [comment]
@manfredsteyer any update on this?

**Comment by stefancplace** [comment]
Is there any news when a fix will be available?

**Comment by slaven3kopic** [comment]
Any updates on this topic? It would be nice to solve this issue

**Comment by smasala** [comment]
Not very cool but 🤷‍♂️ ...

```json
"scripts": {
    ...
    "postinstall": "ts-node patchMFPlugin.ts"
}
```

patchMFPlugin.ts:
```typescript
import { readFileSync, writeFileSync } from "fs";
import * as os from 'os';

if (os.platform() !== 'win32') {
    console.warn("Patching module according to: https://github.com/angular-architects/module-federation-plugin/issues/21");
    const filePath = 'node_modules/@angular-architects/module-federation/package.json';
    const content = readFileSync(filePath, {encoding: 'utf-8'});
    const patchedContent = content.replace(/src\\\\/g, "src/");
    writeFileSync(filePath, patchedContent, {encoding: 'utf-8'});
    console.warn("Patching complete");
}
```

**Comment by tropan** [comment]
An update on this would be awesome

**Comment by Lars-Wunderlich** [comment]
A solution is quite important for us and urgently required to continue.

**Comment by jeremyhayes** [comment]
FWIW, we were able to handle this by importing from the `src` subfolder in the package:
```typescript
import { loadRemoteModule, LoadRemoteModuleOptions } from '@angular-architects/module-federation/src';
```

Not an _ideal_ fix, but likely preferable to patching `node_modules` or forking the project.

**Comment by NagornovAlex** [comment]
Ran into this issue when was building a linux docker image  in CI. Spent a whole day trying to figure it out since it works fine on windows... Luckily found this issue page by chance. Hope all PRs will be approved soon and a new version is released. 
Anyway thanks @manfredsteyer for the package!

**Comment by manfredsteyer** [comment]
Thanks for reporting this and sorry that I lost track of this. Indeed, it's not in the source code. Seems to be an issue with npm publish in the version used back then. 

The new version for Angular CLI 12.rc.1 does not have this issue (it's @next or @12.0.0-rc.1) and I'll try to make a version of 1.x for Angular 11 ready that does not have this issue.

Btw: There was an issue with Angular 11.1 and 11.2. Angular 11.0.0 works fine with Version 1 of this plugin and Angular 12 works fine with version 12 of this plugin (currently RC).

**Comment by eironman** [comment]
Thanks @manfredsteyer!
