### ISSUE TITLE
Load one MF inside another MF

### ISSUE THREAD

**Issue by theSumit67** [angular-architects/module-federation-plugin#213]
Our application is currently built using ngx-build-plus based on micro-frontend architecture. We are trying to move to module federation now.

UI Repos
1. Angular library `shared-lib` which contains some root module like material modules, `TranslateModule.forRoot()`, `NgxPermissionsModule.forRoot()`, etc. Currently, we do not want to share this library across micro frontends, plan is to share angular core/material libraries across micro frontends.
2. Shell(uses `shared-lib` as node_module dependency)
3. MF1(uses `shared-lib` as node_module dependency) - web component using angular elements library -> comp1
4. MF2(uses `shared-lib` as node_module dependency) - registers multiple web-components using angular elements library -> comp2, comp3

All application build file single bundle which includes shared library.

Now using module federation I am able to split & share angular common/forms/http modules.

I am able to load MF1 & MF2 using routing like this -
```ts
{
  path: "mf1",
  component: WebComponentWrapper,
   data: {
    type: 'module',
    remoteEntry: '/mf1/remoteEntry.js',
     exposedModule: './web-components',
     elementName: 'mf1-app'
   } as WebComponentWrapperOptions
} 
```

However, my requirement is to load comp3(MF2) inside comp1(MF1) (both will be inside shell/host).

I tried following two approaches-
1. When I tried matching routes for comp3(MF2) so then parent comp1(MF1) gets destroyed and the page gets blank.
2. Using `loadRemoteModule({ type: 'module', remoteEntry: '/mf2/remoteEntry.js', exposedModule: './comp3-components }).then(m => m.Comp3Module)` causes error `ERROR Error: Uncaught (in promise): NullInjectorError: NullInjectorError: No provider for InjectionToken SHARED_LIB_CONFIG_TOKEN!` resolving this leads to one after another similar error. I think this is due to the architecture of  MF1/2 which expects complete shared lib modules ( like material modules, TranslateModule.forRoot() etc )and its dependencies loaded before loading any component.

Once MF2 is loaded directly from shell then it also works inside MF1.

Please let me know how can I achieve this. Thanks!

**Comment by dkhrunov** [comment]
Hello!
Try using this [ngx-mfe](https://www.npmjs.com/package/ngx-mfe), this library should help you to load one MFE app in another MFE app's template.

**Comment by theSumit67** [comment]
Hi @dkhrunov, All MFEs are exported as web component using angular element library. Will it work with ngx-mfe?

**Comment by dkhrunov** [comment]
No, sorry
