### ISSUE TITLE
[Native Federation] lexical re-exports of non esm modules

### ISSUE THREAD

**Issue by ScriptedAlchemy** [angular-architects/module-federation-plugin#220]
If a module is exposed or shared and not ESM, we need to run it through a parser to re-export its exports as ESM 

Like In the case of react. 

We should not need to run this on everything as esbuild will handle internal modules that are commonjs; only if it's to be externally referenced will we require re-exporting it in a esm wrapper. 

Performance-wise, it should have minimal impact as the parser I've picked to help with the lexical scope is built in Rust. 

related to: https://github.com/manfredsteyer/native-federation-core-example/issues/1

**Comment by manfredsteyer** [comment]
+1

if we do this outside of esbuild, it'd be tooling agnostic. 

We should end up in this branch when there is no esm version of a shared lib. Perhaps i/o returning ``null``, we can run the parser:

https://github.com/angular-architects/module-federation-plugin/blob/da488c00ae5dedfa1e75657bd8f982e0c9dd8a71/libs/native-federation-core/src/lib/utils/package-info.ts#L109

**Comment by ScriptedAlchemy** [comment]
We can check the resolution of the package type. If it's not type module then we run it over the parser and reexport it. If there's no module or import field on the consuming package. It might be worthwhile to not make this agnostic since all bundle tools should have this capability in some way. Rollup3 includes this out the box and esbuild has a commonjs plugin we could just compose on. 
But we can always offer the base parser capability- however might be nice to lean on the plugin when a bundler has a plugin to deal with this so our surface area of maintenance is lower across different compiler tools

**Comment by manfredsteyer** [comment]
+1
We now have a solution. The build adapter now gets information about the kind of the build (e. g. shared-package) and if it is esm. There is now also a default adapter in https://www.npmjs.com/package/@softarc/native-federation-esbuild that uses rollup for shared packages and otherwise esbuild.

Doing it directly with esbuild would speed up the process. So, if we find a solution, please let me know.

**Comment by ScriptedAlchemy** [comment]
Check the pr on module Fede examples. Someone added a PR to fix using esbuild for externals
