### ISSUE TITLE
Ability to configure proxy to fix CORS errors with Angular CLI proxy

### ISSUE THREAD

**Issue by abrahamjoseph** [angular-architects/module-federation-plugin#221]
Trying to access an API endpoint while building on localhost can be traumatizing, especially when this error “No ‘Access-Control-Allow-Origin’ header is present on the requested resource” comes up. The error is due to the same-origin policy that is implemented by most browsers.The same-origin policy is a critical security mechanism that restricts how a document or script loaded from one origin can interact with a resource from another origin.

We have a provision in angular cli to run 

`ng serve --proxy-config proxy.conf.json` 

How can we handle this along with npm run run:all or `node node_modules/@angular-architects/module-federation/src/server/mf-dev-server.js`

**Comment by manfredsteyer** [comment]
In this case you can do this configuration in your angular.json
