### ISSUE TITLE
Plugin bumps TypeScript target?

### ISSUE THREAD

**Issue by eric-horodyski** [angular-architects/module-federation-plugin#230]
When running `nx g @angular-architects/module-federation:init`, the following files are updated:

* `apps/{project}/tsconfig.app.json`
* `tsconfig.base.json`

Both files will update the TypeScript target to `es2020`. Is there a reason why this is done? Would it be possible to preserve the output target?

**Comment by manfredsteyer** [comment]
Unfortunately, we need es2020+. Since v13, the Angular CLI produces EcmaScript modules (instead of plain javascript files) and in this mode, Module Federation uses import.meta which is only available for es2020+.

**Comment by eric-horodyski** [comment]
@manfredsteyer - Thanks for the response. However, I still get the `import.meta` error with the targets bumped to `es2020`. My Angular dependencies point to ~14.2.0
