### ISSUE TITLE
Unable to load microfrontend hosted in cloudfront in the shell application

### ISSUE THREAD

**Issue by abhijeetkharkar** [angular-architects/module-federation-plugin#231]
My **Shell** application is written in `Angular 8`. My **microfrontend** is written in `Angular 14`. I have followed the tutorial.

When I run the microfrontend in my local and run my shell in parallel, the microfrontend loads successfully in the shell. When I build it and copy all the files in the dist folder to a S3 bucket fronted by AWS Cloudfront, it is able to load my `remoteEntry.js` file but when from within the `remoteEntry.js` file, the lazy chunk is being referenced, I am getting a CORS error and hence, the chunk is not being loaded.

I have another microfronend built by someone else in ReactJS put in a different folder of the same S3 bucket, and that loads just fine from my shell.

Any help would be appreciated!

**Comment by AlonsoK28** [comment]
Could you try migrate your `host / shell` app to `ng 14` ?

**Comment by abhijeetkharkar** [comment]
That was the real problem, it is a critical and an almost legacy application. There are other dependencies too. Hence, we cannot change it angular 14. But the issue is actually resolved now. There was nothing wrong with the package or my code. The S3 bucket where it is was hosted didn't have `localhost` added to the allowed origins. Once that was done, the mfe started loading.
