### ISSUE TITLE
How to display micro-frontend component(s) inside HTML template?

### ISSUE THREAD

**Issue by vikramsinghvirdi** [angular-architects/module-federation-plugin#233]
Instead of using routes, how can I display / render MFE inside HTML templates?
I am using Angular version 12.

I found this plugin - https://www.npmjs.com/package/ngx-mfe which might do, but I am looking for an approach using [module-federation-plugin](https://github.com/angular-architects/module-federation-plugin) instead of using one more plugin (if that's possible)

**Comment by dkhrunov** [comment]
Hi, I'm the creator of https://www.npmjs.com/package/ngx-mfe, my library runs on top of the module-federation-plugin and simply extends the functionality provided by the plugin-federation-module.

**Comment by manfredsteyer** [comment]
You can import the component via module federation and display it with a *ngComponentOutlet
