### ISSUE TITLE
build optimization problem in prod mode after project migration from NX 13 (Angular 13) to NX 14 (Angular 14)

### ISSUE THREAD

**Issue by eugenephilipov7** [angular-architects/module-federation-plugin#238]
We have problem with build optimization in prod mode after project migration from NX 13 (Angular 13) to NX 14 (Angular 14).
In NX 13 we did not have issues.

We also use "@angular-architects/module-federation": "14.3.10",
and "@angular-architects/module-federation-tools": "14.3.10".

While running npx nx run my-mf:serve, we don't have any problem.
Running npx nx run my-mf:serve:production, we have error in browser console and not working web app.
The same error in browser console after deployment of build created with nx run my-mf:build --skip-nx-cache.
in browser console:
ERROR NullInjectorError: R3InjectorError[yu -> yu -> undefined -> undefined -> undefined]:
NullInjectorError: No provider for undefined!
at au.get (537.167380f1e67f7b44.js:1:44933)
at pu.get (537.167380f1e67f7b44.js:1:47603)
at pu.get (537.167380f1e67f7b44.js:1:47603)
at pu.get (537.167380f1e67f7b44.js:1:47603)
at qm (537.167380f1e67f7b44.js:1:34022)
at K (537.167380f1e67f7b44.js:1:34120)
at Di (537.167380f1e67f7b44.js:1:34552)
at Object.r [as factory] (537.167380f1e67f7b44.js:1:50241)
at pu.hydrate (537.167380f1e67f7b44.js:1:48980)
at pu.get (537.167380f1e67f7b44.js:1:47556)

If change production.optimization to false in project.json, there is no error in browser console while running nx run my-mf:serve:production or nx run my-mf:build.

How to reproduce:
git clone https://github.com/eugenephilipov7/migration_problem
npm i
npx nx run my-mf:serve:production
http://localhost:4300/
in browser console (Edge,FF):
ERROR NullInjectorError: R3InjectorError[yu -> yu -> undefined -> undefined -> undefined]:
npx nx run my-mf:serve
no error in browser console (Edge,FF)

Initially https://github.com/webpack/webpack/issues/16311.
After created https://github.com/angular/angular/issues/47592.
We also try to find help in modeule-federation-plugin team beacouse it one of main part of our non-working case.

Additional tools: NX,
"@angular-architects/module-federation": "14.3.10",
"@angular-architects/module-federation-tools": "14.3.10",

angular-devkit/architect          0.1402.3
@angular-devkit/build-angular      14.2.3
@angular-devkit/core               14.2.3
@angular-devkit/schematics         14.2.4
@angular/cdk                       14.2.2
@angular/cli                       14.2.4
@angular/material                  14.2.2
@angular/material-moment-adapter   14.2.2
@schematics/angular                14.2.4
ng-packagr                         14.2.1
rxjs                               6.6.7
typescript                         4.7.4
webpack                            5.74.0
node                               16.17.1

**Comment by manfredsteyer** [comment]
Hi,

thanks for pointing this out.

I'm afraid, we cannot reproduce this.

Can you create a minimal example showing this issue?

Best wishes,
Manfred
