### ISSUE TITLE
Handle Remote Unavailable

### ISSUE THREAD

**Issue by fraschizzato** [angular-architects/module-federation-plugin#247]
Hi,
at this time I'm setting the routes of mfe in the "dynamic" way:

```
export function buildRoutes(options: CustomManifest): Routes {
 
     const lazyRoutes: Routes = Object.keys(options).map(key => {
         const entry = options[key];
         return {
             path: entry.routePath,
             loadChildren: () => 
                 loadRemoteModule({
                     type: 'manifest',
                     remoteName: key,
                     exposedModule: entry.exposedModule
                 })
                 .then(m => m[entry.ngModuleName])
         }
     });
 
     return [...APP_ROUTES, ...lazyRoutes];
```
in our environment one remote could be down/unavailable and that locks all the frontend. 
I'd like to add a fallback when the remote module is unavailable but i can't find out where to catch the error.

When module is unavailable I'd like to change the return as it follows:

```
return {
             path: entry.routePath,
             component: MfeFallback
}
```

thanks

**Comment by dkhrunov** [comment]
@fraschizzato  Hi,  check this [ngx-mfe](https://github.com/dkhrunov/ngx-mfe) , this lib allow you to declare fallback component

**Comment by manfredsteyer** [comment]
Also, here, you can go with traditional Angular features. For instance, you can register for the router events (router.events) or you can register a global error handler.
