### ISSUE TITLE
Possibility to invalidate loaded remote entries

### ISSUE THREAD

**Issue by TimSielemann** [angular-architects/module-federation-plugin#248]
Hello,

we have a problem when loading the remote modules before bootstrapping the application to get the best possible shared split and then loading the micro frontends lazy in a later point in time. 

The problem there is that if we deploy a new version of the micro frontend while the users do not reload the shell and haven't loaded the micro frontend yet the resources that should be loaded changed and therefor the previously loaded remote entry is not valid anymore. 

We would like to have a fallback to reload the remoteEntry again for that micro frontend if that error occured but thats sadly not possible as the remoteEntries loaded are cached in the library code. Would it be possible to add some functionality to remove loaded remoteEntries from that cache?

**Comment by ezagdir** [comment]
@TimSielemann 
You have the control over the loading of the remoteEntry in `loadChildren` so you can try to implement your own fallback mechanism. for example (just to deliver the idea):

```
import { firstValueFrom, Subject, switchMap } from 'rxjs';
import { loadRemoteModule } from '@angular-architects/module-federation-runtime';

const reloadMyModule$ = new Subject<void>();

const ROUTES = [
	{
		path: 'my-module',
		loadChildren: () => reloadMyModule$.pipe(
			switchMap(() => firstValueFrom(loadRemoteModule({
				remoteEntry: 'https://my-remote-site/remoteEntry.js',
				type: 'module',
				exposedModule: './Module',
			}))),
		),
	}
]

```

and then `reloadMyModule$.next()` should trigger the load of remote module again.

btw if the remote site is gone, you can catch it and provide whatever error-contactus-broken-module you have like `loadRemoteModule(/* ... */).catch(() => MyOoopsModule)`

**Comment by manfredsteyer** [comment]
Actually, you really have to take care to load the remote after bootstrapping. You can do this with an AppInitializer or with resolver blocking the router a bit.

**Comment by TimSielemann** [comment]
@manfredsteyer so that problem of the outdated remoteEntry will be resolved then automatically if i load the remoteEntries after bootstrapping?

**Comment by michaelhunziker** [comment]
@TimSielemann Sorry for digging this up... but did you ever find a solution to your issue?

**Comment by TimSielemann** [comment]
we fell back to loading the remote entry just when we would load the microfrontend and not right after bootstrapping anymore.
