### ISSUE TITLE
@angular-architects/native-federation approach to static assets?

### ISSUE THREAD

**Issue by Ketec** [angular-architects/module-federation-plugin#270]
With webpack based approach i end up with an option that uses
`__webpack_public_path__` to gain access to the remote URL to correctly load static assets (and also webworker scripts).

Are there any built-in ways to deal with assets with a native approach?

**Comment by r1m** [comment]
You can try with to mimic the auto strategy of wepback using [import.meta.url](https://webpack.js.org/api/module-variables/#importmetaurl), [document.currentScript](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript), script.src or self.location

https://webpack.js.org/guides/public-path/#automatic-publicpath
https://github.com/webpack/webpack/blob/main/lib/runtime/AutoPublicPathRuntimeModule.js#L37

**Comment by manfredsteyer** [comment]
You need to obtain this information from somewhere else. E. g. from a configuration file or from the mf.manifest.json that points to the entrypoint.
