### ISSUE TITLE
angular mfe error from CommonModule when loading mfe v12 to shell v14 

### ISSUE THREAD

**Issue by alexkoretzki** [angular-architects/module-federation-plugin#273]
hi, 
we getting this error
dashboard.component.html:1 NG0303: Can't bind to 'ngIf' since it isn't a known property of 'div' (used in the 'DashboardComponent' component template).
**If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is a part of an @NgModule where this component is declared.**
when loading mfe to shell app with different versions.
its not happening when shell is 12 and mfe also v12

**Comment by manfredsteyer** [comment]
Unfortunately, this is not supported. You can bootstrap both applications, the shell and the micro frontend, separately in one page. You might want to wrap them into web components.
