### ISSUE TITLE
CORS error when trying to access mfr remoteEntry.js on Shell

### ISSUE THREAD

**Issue by sahithiKondapalli** [angular-architects/module-federation-plugin#281]
I am using angular cli 13.3.5 
and  @angular-architects/module-federation 14.0.1

When i am trying to access the MFE from local it is working as expected.
Deployed the apps to PCF when i am trying to acess the MFE remoteEntry.js from the shell i am getting CORS error.

please provide your inputs.

**Comment by maurotamm** [comment]
Cors is entirely your deployment/web server issue. Depending on what you use for your deployments.

nginx for example would need to allow cross-origin headers.

add_header Access-Control-Allow-Origin * always;

Or use proxies to keep requests on the same domain (again nginx proxy or another webserver one, istio proxies etc).

**Comment by manfredsteyer** [comment]
Yes, you need to configure CORS on your web server.
