### ISSUE TITLE
Native Federation Adapter for esbuild Should Support Asset Loading

### ISSUE THREAD

**Issue by FlorianRappl** [angular-architects/module-federation-plugin#282]
Right now there are no additional loaders configured in the adapter. This is a problem, e.g., when referencing images.

So simple things like

```js
import tractorRed from "./images/tractor-red.jpg";
```

will not work.

A simple fix is to introduce the file loader, e.g., in

```js
await esbuild.build({
  entryPoints: [isPkg ? tmpFolder : entryPoint],
  loader: {
    '.jpg': 'file',
  },
  // ... like before
})
```

would make this "work" (compile), but then will face the issue of potentially not being properly routed.

A mitigation for this could be found for instance in the source of [esbuild-pilet-plugin](https://github.com/smapiot/piral-cli-esbuild/blob/develop/packages/esbuild-pilet-plugin/src/index.ts#L38), which does not load the registered file extensions directly, but via a path resolver. So the assets are still treated as files, but the paths are normalized to the calling MF root URL.

**Comment by manfredsteyer** [comment]
Hi Florian,

thanks for this info. What do you think about the possibility to pass a custom ``loader`` property to ``createEsBuildAdapter``:

```typescript
createEsBuildAdapter({ 
   plugins: [MyPlugin1, MyPlugin2], // <-- This is already possible
   loader: { '.jpg': 'file' } // <-- We could add this
})
```

Would this solve this issue?

Best wishes,
Manfred

**Comment by FlorianRappl** [comment]
I think we should definitely add the `loader` property, however, this alone would not fix it (as outlined, we also need to satisfy the paths, which otherwise do not work).

I actually extracted the auto-path now to a dedicated esbuild plugin, so either we depend on the plugin directly ([`esbuild-auto-path-plugin`](https://www.npmjs.com/package/esbuild-auto-path-plugin)) or we put it in the documentation and users would need to use it explicitly for referencing assets (since this is a fairly standard task my recommendation is the former, but having the flexibility to choose would be sufficient, too).

**Comment by manfredsteyer** [comment]
In the current version 1.1.1, the adapter now exposes the loader property.

Please make sure to delete your cache manually when changing it (this setting does currently not affect the hash key)

**Comment by FlorianRappl** [comment]
In my opinion the documentation should still contain the info about asset loading. Assets are an elementary piece of any frontend - as it is right now people would just get strange errors and not know what's going on.

Even if somebody puts in the right loaders nothing would work - they'd still require, e.g., the `esbuild-auto-path-plugin`.
