### ISSUE TITLE
Module Federation Plugin does not work with Angular 15

### ISSUE THREAD

**Issue by igokul1973** [angular-architects/module-federation-plugin#303]
I have created a shell and remote in Angular 15, using @angular/cli as multi-repo app.

Angular CLI: 15.2.2
Node: 16.13.2
Package Manager: yarn 1.22.19
OS: linux x64

Then ran the `ng add @angular-architects/module-federation` for each of the app and following the tutorial (which for some reason only shows the mono-repo set-up and examples) set up a couple of links on the shell, one of them pointing to the remote, which, in turn, shares one module.
Both applications started fine, but as soon as I clicked the link to remote on a shell, I got:
```
GET http://localhost:4200/src_app_product-registry_product-registry_module_ts-_1c6c1.js net::ERR_ABORTED 404 (Not Found)
```
in the browser's Web Dev Tools.

Two more additional errors (not listed here) following by, but most probably are associated with the 404.

I tried the same thing with the Angular 14 (do not remember the exact version) and it works fine. 
I tried all sorts of tweaks in Angular 15 (changing the node.js version to 18 and back, trying to use 'module', 'manifest', dynamic federation or not, even tried different workstations - both Linux) - to no avail. Spent 3 days on it already. I searched and could not see any related issues on the WWW or in your issues here.

To reproduce the issue, here is a link to the shell's repo - https://github.com/igokul1973/shell and the remote's repo - https://github.com/igokul1973/mfe1. Run it, open the shell and click on the [Product registry](http://localhost:4200/product-registry) link with Web Dev tools open.

Please tell me if I am doing anything wrong. To my understanding - it is a bug.

**Comment by igokul1973** [comment]
As an additional information, in a slightly different set-up of the shell-remote, and the difference would be - I upgraded all the packages to latest ones (such as "@angular/common": "^15.2.2"), I get this upon opening the shell in the browser:"@angular/common": "^15.2.2".
![image](https://user-images.githubusercontent.com/5454915/224803834-ad787f8d-7442-449f-bf85-b06e1f7e2e61.png)
I can clearly see, however, that the http://localhost:4200/node_modules_angular_platform-browser_fesm2020_platform-browser_mjs-_18080.js is there, as I can open it up in the browser.

**Comment by manfredsteyer** [comment]
The good message is: It works.

Your webpack.config.js is exposed to export the result of withModuleFederationPlugin:

```javascript
module.exports = withModuleFederationPlugin({ ... });
```

However, in your example, you export sth else:

```javascript
const plugin = withModuleFederationPlugin({ ... });

module.exports = {
  ...plugin,
  output: {
    ...plugin.output,
    scriptType: 'text/javascript'
  }
}
```
