### ISSUE TITLE
facing route related issue while loading web component in shell app.

### ISSUE THREAD

**Issue by utkarshbankar** [angular-architects/module-federation-plugin#306]
FYR.

![issue](https://user-images.githubusercontent.com/26164773/227792464-478a7444-aaa4-4948-a1cd-4c1115994274.PNG)

**Comment by lanmingle** [comment]
note route configuration and a link

main app:

- /app1/r1/p1
- /app1/r1/p2
- /app2/r1/p1

sub app1:

/r1/p1 -> main /r1/p1 (error)
r1/p2 -> main /app1/r1/p2 (ok)

sub app2:
r1/p1 -> main /app2/r1/p1 (ok)
