### ISSUE TITLE
Support both es5 and es2015 in remoteEntry.js

### ISSUE THREAD

**Issue by leokern** [angular-architects/module-federation-plugin#31]
Currently, the file name of the remote entry (remoteEntry.js in the examples) is fixed. When building the MFE with browser support requiring both es5 (IE) and es2015 (modern browsers) this leads to most chunk files being generated twice (es5 and es2015) but only one remoteEntry.js file. In my case, this happens to be the es2015 variant, which IE does not understand.

From the yarn build log:

    Initial Chunk Files                      | Names            |      Size
    polyfills-es5.8708f858c867e6a0dd1e.js    | polyfills-es5    | 196.21 kB
    styles-es2015.0a3903fa3827b16066ce.js    | styles           | 192.21 kB
    styles-es5.0a3903fa3827b16066ce.js       | styles           | 192.21 kB
    polyfills-es2015.7a38b8dd65b103288781.js | polyfills        | 171.44 kB
    remoteEntry_mfe.js                       | mfe              |  15.42 kB  // NO es2015
    remoteEntry_mfe.js                       | mfe              |  15.38 kB  // NO es5
    main-es5.63a2713a22969121bd91.js         | main             |  14.89 kB
    main-es2015.63a2713a22969121bd91.js      | main             |  14.87 kB

In order to enable IE support it would be great if there were a way to have both variants of the remoteEntry.js file and allow the shell to pick the right one depending on which browser is being used.

As a workaround I effectively disabled es2015 by only having IE11 in the .browserslistrc file and setting the target to es5 in the tsconfig.

**Comment by hardikpatel043** [comment]
@leokern How to disable es5 (IE) and build only for modern browser. I have just one line in browserlistrc file. But still I see both type of bundles are getting created.

chrome >= 63

**Comment by leokern** [comment]
@hardikpatel043 I don‘t know. For my case (enable only IE/es5), I had to edit the browserlistrc and the target setting in the tsconfig file. Maybe the latter is something you can check, too.

**Comment by matt-gold** [comment]
@leokern 
After looking into this problem for a bit, I discovered that if you just leave out the filename option for ModuleFederationPlugin, the build will output both versions of the remote entry file as `[name]-es5.js` and `[name]-es2015.js`.

**Comment by leokern** [comment]
@matt-gold Thank you!
