### ISSUE TITLE
Lazy Loaded Module shares same ngx-translate TranslationService instance with MFE

### ISSUE THREAD

**Issue by Yello001** [angular-architects/module-federation-plugin#316]
Hello,

our shell application loads a MFE which in turn lazy-loads another module.
The lazy module would like to have its own instance of ngx-translate TranslationService 

https://github.com/ngx-translate/core#lazy-loaded-modules.
According to this doc, the TranslationService of ngx-translate should be re-instantiated for the lazy-loaded module
https://angular.io/guide/providers#limiting-provider-scope-by-lazy-loading-modules

This works fine in standalone case, as soon as the MFE is loaded via Module Federation, MFE and lazy-loaded modules share the same instance of ngx-translate TranslationService and translation does not work as desired anymore.
ngx-translate/core was not included in any webpack.config shared, even an explicit "singleton: false" behaves the same.

Please help/hints

Angular 14.2
Module Federation 14.3.14
Ngx-translate 14.0.0

**Comment by bh3605** [comment]
You need to specify you want a instance of your service scoped to your lazy loaded module.

import { [Injectable](https://angular.io/api/core/Injectable) } from '@angular/core';

@[Injectable](https://angular.io/api/core/Injectable)({
  providedIn: 'any',
})
export class UserService {
}

source: https://angular.io/guide/providers#limiting-provider-scope-by-lazy-loading-modules
