### ISSUE TITLE
Bug with styles/css

### ISSUE THREAD

**Issue by natilivni** [angular-architects/module-federation-plugin#32]
Hello, you mention in your documentation the bug in the experimental CLI/webpack5 which does not allow bundling styles in the federated modules.  Is there an ETA on when this will be resolved?  This is a pretty big hurdle for any enterprise solution.

**Comment by manfredsteyer** [comment]
Hi,

yes, it will be resolved in the version for CLI 12. We currently prepare one for CLI 12.0.0-rc.1.

Saying this, this bug only appears if you share libs in a monorepo. If you use multiple repos, it should be fine.

**Comment by hardikpatel043** [comment]
oowww. I was waiting for sharing css via shared lib. I have to wait then?

**Comment by manfredsteyer** [comment]
The current version 12.0.0-rc.1 of this plugin which works together with Angular (CLI) 12.0.0-rc.1 solves this issue. Please also have a look to the migration section here:
https://www.npmjs.com/package/@angular-architects/module-federation/v/12.0.0-rc.1

**Comment by jimyhdolores** [comment]
@hardikpatel043  how did you come to share css files using sharedLib?
