### ISSUE TITLE
Multi version setup from docs is not working

### ISSUE THREAD

**Issue by mte-bad** [angular-architects/module-federation-plugin#330]
I tried to create a multi version setup according to the docs, and blog posts on angulararchitects. However, I keep running into the same issue NG0203. I created a reproduction repo here https://github.com/mte-bad/ng-module-federation-example.

**Comment by janstadt** [comment]
@manfredsteyer any updates on this?

**Comment by manfredsteyer** [comment]
Hi,

for this to work, you need to wrap your micro frontends into web components.
