### ISSUE TITLE
Angular 12 support

### ISSUE THREAD

**Issue by shuppert** [angular-architects/module-federation-plugin#34]
The Angular core team announced that Webpack 5 will be the default in Angular 12.  The Yarn requirement is a stumbling block as our build system only supports NPM today.

I started playing around with Angular 12 (v12.0.0-rc-0) and the both the MFE and shell build with NPM but at runtime it fails to load the MFE module in the host.  I know it's early, but I'm curious.  Will the Angular 12 out of the box support for Webpack 5 enable dropping the Yarn requirement?

I also tested upgrading the [module-federation-with-angular-dynamic ](https://github.com/manfredsteyer/module-federation-with-angular-dynamic) to Angular 12 and I received the same errors as with Angular 12 and NPM.

Any ideas?

`load script:41 GET http://localhost:5000/common.js net::ERR_ABORTED 404 (Not Found)
__webpack_require__.l @ load script:41
__webpack_require__.f.j @ jsonp chunk loading:43
(anonymous) @ ensure chunk:6
__webpack_require__.e @ ensure chunk:5
./Module @ container-entry:6
get @ container-entry:13
(anonymous) @ dynamic-federation.js:11
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
lookupExposedModule @ dynamic-federation.js:9
(anonymous) @ dynamic-federation.js:57
fulfilled @ tslib.es6.js:73
__webpack_modules__.9140.ZoneDelegate.invoke @ zone.js:400
onInvoke @ core.js:28632
__webpack_modules__.9140.ZoneDelegate.invoke @ zone.js:399
__webpack_modules__.9140.Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
__webpack_modules__.9140.ZoneDelegate.invokeTask @ zone.js:434
onInvokeTask @ core.js:28619
__webpack_modules__.9140.ZoneDelegate.invokeTask @ zone.js:433
__webpack_modules__.9140.Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
__webpack_modules__.9140.ZoneTask.invokeTask @ zone.js:520
invokeTask @ zone.js:1656
globalZoneAwareCallback @ zone.js:1682
load (async)
customScheduleGlobal @ zone.js:1808
__webpack_modules__.9140.ZoneDelegate.scheduleTask @ zone.js:421
onScheduleTask @ zone.js:311
__webpack_modules__.9140.ZoneDelegate.scheduleTask @ zone.js:414
__webpack_modules__.9140.Zone.scheduleTask @ zone.js:248
__webpack_modules__.9140.Zone.scheduleEventTask @ zone.js:274
(anonymous) @ zone.js:1965
desc.set @ zone.js:864
(anonymous) @ dynamic-federation.js:43
ZoneAwarePromise @ zone.js:1340
loadRemoteEntry @ dynamic-federation.js:34
(anonymous) @ dynamic-federation.js:55
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
loadRemoteModule @ dynamic-federation.js:53
loadChildren @ menu-utils.ts:10
loadModuleFactory @ router.js:3687
load @ router.js:3661
(anonymous) @ router.js:2798
_tryNext @ mergeMap.js:44
_next @ mergeMap.js:34
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ catchError.js:14
subscribe @ Observable.js:23
innerSubscribe @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ filter.js:13
subscribe @ Observable.js:23
call @ take.js:22
subscribe @ Observable.js:23
call @ throwIfEmpty.js:13
subscribe @ Observable.js:23
call @ catchError.js:14
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
innerSubscribe @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ scan.js:18
subscribe @ Observable.js:23
call @ takeLast.js:22
subscribe @ Observable.js:23
call @ throwIfEmpty.js:13
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
call @ catchError.js:14
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
innerSubscribe @ innerSubscribe.js:67
_innerSub @ switchMap.js:44
_next @ switchMap.js:34
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
(anonymous) @ subscribeToPromise.js:5
__webpack_modules__.9140.ZoneDelegate.invoke @ zone.js:400
onInvoke @ core.js:28632
__webpack_modules__.9140.ZoneDelegate.invoke @ zone.js:399
__webpack_modules__.9140.Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
__webpack_modules__.9140.ZoneDelegate.invokeTask @ zone.js:434
onInvokeTask @ core.js:28619
__webpack_modules__.9140.ZoneDelegate.invokeTask @ zone.js:433
__webpack_modules__.9140.Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
__webpack_modules__.9140.ZoneTask.invokeTask @ zone.js:520
invokeTask @ zone.js:1656
globalZoneAwareCallback @ zone.js:1682
Show 93 more frames
core.js:6456 ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk common failed.
(error: http://localhost:5000/common.js)
ChunkLoadError: Loading chunk common failed.
(error: http://localhost:5000/common.js)
    at Object.__webpack_require__.f.j (jsonp chunk loading:27)
    at ensure chunk:6
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (ensure chunk:5)
    at Object../Module (container-entry:6)
    at Object.get (container-entry:13)
    at dynamic-federation.js:11
    at Generator.next (<anonymous>)
    at tslib.es6.js:76
    at new ZoneAwarePromise (zone.js:1340)
    at resolvePromise (zone.js:1255)
    at resolvePromise (zone.js:1209)
    at zone.js:1321
    at ZoneDelegate.__webpack_modules__.9140.ZoneDelegate.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:28619)
    at ZoneDelegate.__webpack_modules__.9140.ZoneDelegate.invokeTask (zone.js:433)
    at Zone.__webpack_modules__.9140.Zone.runTask (zone.js:205)
    at drainMicroTaskQueue (zone.js:620)
    at ZoneTask.__webpack_modules__.9140.ZoneTask.invokeTask [as invoke] (zone.js:520)
    at invokeTask (zone.js:1656)`

**Comment by scottfwalter** [comment]
I thought I would start with a brand new Angular 12 project but can't add the schematics.  

```
❯ ng add @angular-architects/module-federation --project container-module-federation --port 4200
Skipping installation: Package already installed
"Mf" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
The project doen't have a build or serve target in angular.json!
```

**Comment by shuppert** [comment]
@scottfwalter I ran into that as well.  The schematic fails but I manually made the same changes that the schematic makes to my project to get past it.

**Comment by manfredsteyer** [comment]
Hi,

cli 12 support is coming and it will also solve some issues. I will reach out in the course of the next days.

**Comment by shuppert** [comment]
Thank you @manfredsteyer.  I'm looking forward to it.

**Comment by manfredsteyer** [comment]
Good news: You can now use the current Angular Version 12.0.0-rc.1 with the version 12.0.0-rc.1 of this plugin.

**Comment by scottfwalter** [comment]
@manfredsteyer  Angular 12 no longer creates an options object under the serve target.  This will cause the error "The project doen't have a build or serve target in angular.json!".  I created a PR to address this.
