### ISSUE TITLE
is there an existing webpack adapter for the native federation builder?

### ISSUE THREAD

**Issue by stephencranedesign** [angular-architects/module-federation-plugin#340]
I've just recently discovered native federation. I currently have module federation implemented thru webpack. Looking at the `Augment Your Build Process` section in the [npm docs](https://www.npmjs.com/package/@softarc/native-federation), it mentions that the `federationBuilder.init` function needs an adapter for your bundler. Is there one for webpack currently? if not, where would be a good place to get started attempting to implement one?

**Comment by manfredsteyer** [comment]
Currently, there is none. But it would be interesting to have one. So, if you have some time, creating a community project for this, would be great. I would link it here.
