### ISSUE TITLE
Forcing a version for a "shared" library from shell

### ISSUE THREAD

**Issue by Ketec** [angular-architects/module-federation-plugin#352]
I cannot seem to find any valid combination of share settings that would enforce a singleton version to use from Shell.

mfe1 uses library@1.0.0
mfe2 uses library@2.0.0
shell is set to share 2.0.0 (shareAll / package.json)
2.0.0 is backwards compatible, but 1.0.0 will not work in mfe2

Now if you navigate to mfe1 - it loads 1.0.0.
Navigating to mfe2 breaks it. 1.0.0 singleton is now already loaded. The forRoot services are invalid.

It ignores the shell 2.0.0 requirement - that is unless I just explicitly import AND use it in Shell (but there is no need for it there - shell does nothing).

Importing every module and sub-module - 100-s of them in the shell AND using them feels stupid.

I can make libraries backward compatible - but not the opposite. New functionality cannot exist in old versions.

**Comment by manfredsteyer** [comment]
Yes, you are right. This feature is still pending. Comes with one of the next releases.

**Comment by Ketec** [comment]
@manfredsteyer which version was this released in?
