### ISSUE TITLE
Error on build No loader is configured for ".scss"

### ISSUE THREAD

**Issue by luizluan** [angular-architects/module-federation-plugin#358]
![image](https://github.com/angular-architects/module-federation-plugin/assets/13450436/eb59453d-d547-47f4-a67c-fab5f617a4e2)
```
const { withNativeFederation, shareAll } = require('@angular-architects/native-federation/config');

const config = withNativeFederation({
  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
  },
  skip: [
    "ngx-toastr",
    "monaco-editor"
  ]
});

config.module = {
  rules: [
    {
      test: /\.s[ac]ss$/i,
      use: [
        "style-loader",
        "css-loader",
        "sass-loader",
      ],
    },
  ],
};

module.exports = config;
```

Can someone help me?

**Comment by luizluan** [comment]
I made an example based on the tutorial
https://github.com/luizluan/native-federation-test-angular

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. Seems like, this only happens when a npm packages ships directly uses scss. I'm currently looking into it.

**Comment by manfredsteyer** [comment]
Just released a new version that fixes this issue.
