### ISSUE TITLE
[Bug] requiredVersion 'auto' not working with locally installed package

### ISSUE THREAD

**Issue by shastaxc** [angular-architects/module-federation-plugin#372]
Using module federation with Angular v16, I have a library generated in a different repository that I packed up with `npm pack` and transferred over to my MF project. I installed that package using `npm install` which adds a line in the package.json in the format similar to 
```
"package-name": "file:local-packages/package-name-0-0-5.tgz"
```
This results in a runtime error of:
```
main.ts:6 Error: Unsatisfied version 0.0.5.tgz from mf-shell of shared singleton module package-name (required =[file:local-packages/package-name-0.0.5.tgz](file://local-packages/package-name-0.0.5.tgz))
    at getStrictSingletonVersion (main.js:354:58)
    at main.js:438:19
    at main.js:390:19
    at 300 (main.js:444:24)
    at main.js:499:55
    at Array.forEach (<anonymous>)
    at __webpack_require__.f.consumes (main.js:482:35)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (ensure chunk:5:1)
```

Uncompressing the TGZ file and installing with `npm link` results in a similar error.

My host has in its webpack.config.js:
```
const mf = require('@angular-architects/module-federation/webpack');
...
shared: mf.share({
  "package-name": { singleton: true, strictVersion: true, requiredVersion: 'auto', eager: true, },
  ...
})
```

And my remote has:
```
const mf = require('@angular-architects/module-federation/webpack');
...
shared: {
  ...mf.shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
},
```

It appears that the "requiredVersion" set to "auto" is being checked is simply looking at the value in the package.json. It should recognize the `file:` protocol and dig into that dependency's package.json for the actual version number.

A workaround is explicitly setting "requiredVersion" to the desired version number (e.g. "0.0.5").

**Comment by manfredsteyer** [comment]
Yes, this is not supported.

**Comment by shastaxc** [comment]
Then I request that it be supported.

**Comment by manfredsteyer** [comment]
Noted. Honestly, it won't have priority.

**Comment by manfredsteyer** [comment]
Btw - as a workaround, you could do something like this:

shared: {
  ...mf.shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
  'my-lib': { singleton: true, strictVersion: true, requiredVersion: '1.2.3' },
},

1.2.3 is in this case the version you want to assign. You can also add some nodejs logic to determine the version dynamically.
