### ISSUE TITLE
Can't find stylesheet to import

### ISSUE THREAD

**Issue by GeorgeKnap** [angular-architects/module-federation-plugin#373]
There seems to be a bug in `@angular-architects/native-federation:build` executor:

I've scaffolded following [demo  repository](https://github.com/GeorgeKnap/nx-ng-native-federation)  (NX, Angular 16, Angular Material, native federation) 

In this repository shell  `AppComponent` is using material mixin to change chips density: 

```
app.component.scss
------------------------------------------
@use '@angular/material' as mat;

:host {
    ::ng-deep {
        @include mat.chips-density(-3);
    }
}
```

Without native federation this app builds with esbuild without problems. With native federation there is a build error:
```
✘ [ERROR] Can't find stylesheet to import.
  ╷
1 │ @use '@angular/material' as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  apps\shell\src\app\app.component.scss 1:1  root stylesheet [plugin angular-sass]
```

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. I managed to reproduce this issue and I'm going to look into this asap.

**Comment by manfredsteyer** [comment]
Good message: We hunted down the origin of this behavior. We are also contacting the Angular team to develop a proper solution.

Until then, as a temp. workaround, you might want to unblock yourself by copying the styles over to the assets folder.

**Comment by manfredsteyer** [comment]
We've just updated a new version. It solves this issue. Can you please give it a try?

**Comment by manfredsteyer** [comment]
Does it work for you?

**Comment by GeorgeKnap** [comment]
@manfredsteyer Sorry for late reply. Yes, with the latest version this error is gone. Many thanks for looking into it.

**Comment by digaus** [comment]
@manfredsteyer is this also fixed in version 16? Because I am currently getting same error with 16.3.5

**Comment by mcorbett-cognex** [comment]
@manfredsteyer is there any update on this for version 16?

**Comment by phoenix741** [comment]
@manfredsteyer is there any update on this for version 16?

we need it to migrate our application step by step (instead of migrate to native federation + angular 17 in one shot)
