### ISSUE TITLE
Angular 17 build with native-federation will not include stylesheets referenced form npm packages

### ISSUE THREAD

**Issue by pamartinez-signify** [angular-architects/module-federation-plugin#378]
With native-federation build, the styles array including npm package styles, e.g.
```
"styles": [
  "@angular/material/prebuilt-themes/indigo-pink.css",
  "src/styles.scss"
]
```
will be added as `@import "@angular/material/prebuilt-themes/indigo-pink.css";` instead of rendering the actual stylesheet from that path, like the Angular build implementation does.

**Comment by manfredsteyer** [comment]
Thans for pointing this out. Closing this one, as it's a duplication of #373
