### ISSUE TITLE
Live Reload Not Working

### ISSUE THREAD

**Issue by vrapalis** [angular-architects/module-federation-plugin#38]
After executing ng add @angular-architects/module-federation command, live reload not working anymore. Nx based project.

Inf.
os: Ubuntu 20
node: v14.16.1
npm: 7.11.2
yarn: 1.22.5

**Comment by vrapalis** [comment]
I removed node_module folder and reinstall, but still not working, maybe some ides anyone

**Comment by vrapalis** [comment]
Seems like webpack problem => https://github.com/webpack/webpack/issues/11182

**Comment by manfredsteyer** [comment]
I think, this works now with CLI 12 and its webpack 5 integration.
