### ISSUE TITLE
Native Federation: What about SSR?

### ISSUE THREAD

**Issue by petogriac** [angular-architects/module-federation-plugin#381]
Is there please a possiibility to configure or plan to support SSR in Native Federation Plugin?

Our stack is:

- NG17
- default SSR enabled (which is provided by Ng17 cli out of the box by default)

and we are trying this: https://www.angulararchitects.io/en/blog/micro-frontends-with-modern-angular-part-1-standalone-and-esbuild/

but getting this error when running `ng serve shell`:

`Error: Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(server).`

**Comment by manfredsteyer** [comment]
We currently don't have a sound SSR story. This will change soon with 17.1 or 17.2

Also, you are using the ApplicationBuilder -- this will be supported with 17.1

So far, we are supporting the -esbuild builder.

**Comment by petogriac** [comment]
Thanks for the fast response, looking forward to 17.1 👍
