### ISSUE TITLE
Native federation: build not creating modules files with latest Angular version

### ISSUE THREAD

**Issue by pamartinez-signify** [angular-architects/module-federation-plugin#384]
`npm run build` stopped working with latest angular version.
it used to generate `remoteEntry.json`, `importmap.json` and libraries js files.

It does not after upgrading to the latest version of packages:

![image](https://github.com/angular-architects/module-federation-plugin/assets/150499920/8f36d162-f87e-45b3-8066-02e936eacd25)

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. I fixed it. Small issue with large effect.

Please update to the newest version and try again.

**Comment by pamartinez-signify** [comment]
This has been resolved with 17.0.3
Thanks, really appreciate it.
