### ISSUE TITLE
Angular 11 without Yarn

### ISSUE THREAD

**Issue by shuppert** [angular-architects/module-federation-plugin#39]
Is it possible to avoid Yarn and only use NPM with Angular 11 and version 12.0.0-rc.1.0.1 if the plugin?  The latest [tutorial](https://github.com/angular-architects/module-federation-plugin/blob/12.0.0/libs/mf/tutorial/tutorial.md) makes it sound like it's possible to choose between NPM or Yarn but the when installing the plugin it uses Yarn and creates a yarn,lock file.

**Comment by scottfwalter** [comment]
You don't need yarn for Angular 12.  However, it's needed for Angular 11.  From what I understand the reason why its needed for Angular 11 is to get a particular version of Webpack.

**Comment by eironman** [comment]
In order to use webpack 5 you need to use yarn at the moment

**Comment by manfredsteyer** [comment]
+1 -- for Angular 11 you need yarn. For Angular 12, both, yarn and npm is fine.
