### ISSUE TITLE
The requested module 'blob:...' does not provide an export named '...'

### ISSUE THREAD

**Issue by pamartinez-signify** [angular-architects/module-federation-plugin#391]
Now getting this error:
`SyntaxError: The requested module 'blob:http://localhost:4200/395ab176-349d-49ae-ba4b-aca4200bf73b' does not provide an export named 'AuthSdkError' (at _okta_okta_angular-6_3_0-dev.js:7:10)`

I am using both:
```
"@okta/okta-angular": "^6.3.0",
"@okta/okta-auth-js": "^7.4.3"
```

I noticed there is the following usage in @okta/okta-angular:
`import { AuthSdkError, toRelativeUrl } from "@okta/okta-auth-js";`
Then at some point it is used like:
`throw new AuthSdkError('...');`

For this reason the bootstrapping of the App is failing
![image](https://github.com/angular-architects/module-federation-plugin/assets/150499920/6cc0e6f5-0786-4b1f-9fce-9d9e41151567)

_Originally posted by @pamartinez-signify in https://github.com/angular-architects/module-federation-plugin/issues/387#issuecomment-1836917098_

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. It's fixed now.

To try it out, please a) delete your node_modules\.cache folder, b) install the latest version of our plugin, and c) try it again.
