### ISSUE TITLE
support for angular universal

### ISSUE THREAD

**Issue by jigfox** [angular-architects/module-federation-plugin#40]
Is it possible to add angular universal support? I would not mind helping, if someone with more ModuleFederation experience would support me. I have some experience with angular universal but almost no experience with ModuleFederation.

**Comment by jigfox** [comment]
I got it working with server side rendering when I replaced [ngx-build-plus][1] with [@angular-builders/custom-webpack][2] nix-build-plus [does not support angular universal][3]. 

Only thing that doesn't work right now is the dynamic loading of the microfrontends because it tries to access window and requires a DOM to add the `script` tag.

[1]: https://github.com/manfredsteyer/ngx-build-plus
[2]: https://github.com/just-jeb/angular-builders
[3]: https://github.com/manfredsteyer/ngx-build-plus/issues/67

**Comment by jigfox** [comment]
@manfredsteyer do have an idea how we could make `loadRemoteEntry` and `loadRemoteModule` aware of the Platform it is running on? And thus store remote modules/entries somewhere else if running on server/universal?

**Comment by piotrbrzuska** [comment]
@jigfox: Could you share an example project ?

**Comment by jigfox** [comment]
Not necessary anymore it’s working now with the latest beta, thanks for your efforts and work

**Comment by hennihaus** [comment]
@jigfox Do you could share an example with angular universal?

**Comment by manfredsteyer** [comment]
Hi,

the latest version (12.4) now supports Angular Universal, at least the new jsdom-based API. There are also some new schematics that make using this API easy (so I hope). You find some information on this in the readme.

Regarding the classic Universal API @jigfox refers to here: there are no schematics. However, the newest ngx-build-plus version now provides a server builder. Just adjust your angular.json to use ngx-build-plus:server

@jigfox: Can you provide us an example about using the classic Universal API with this plugin or module federation in general? I think this might be interesting for several people.
