### ISSUE TITLE
Support SSL when serving native federated app

### ISSUE THREAD

**Issue by JBBianchi** [angular-architects/module-federation-plugin#403]
Hello,

When I try to `serve` a federated app with the ssl flag (`ng serve --project myapp --ssl`), an error is throw: `Unknown argument: ssl`

It would be nice if the builder for native federation could support serving the app with SSL turned on.

**Comment by manfredsteyer** [comment]
We are going to directly delegate to the CLI's dev-server so that you have all the features it provides. Will be implemented with the next minor version.
