### ISSUE TITLE
native-federation builder i18n bug

### ISSUE THREAD

**Issue by AGreat1** [angular-architects/module-federation-plugin#404]
Hi!

I made a fork of one of your examples [here](https://github.com/AGreat1/module-federation-plugin-example/tree/nf-standalone-solution) and tried adding i18n. Aside from solving a minor problem, that buildTarget in extract-i18n had to be modified to directly refer to the esbuild config, I think I found a bug if i18n is supported from your side.

My build fails with the following call stack:
```
[error] Error: ENOENT: no such file or directory, open 'D:\work\temp\module-federation-plugin-example\dist\shell\index.html'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at updateIndexHtml (D:\work\temp\module-federation-plugin-example\node_modules\@angular-architects\native-federation\src\utils\updateIndexHtml.js:16:27)
    at runBuilder_1 (D:\work\temp\module-federation-plugin-example\node_modules\@angular-architects\native-federation\src\builders\build\builder.js:108:59)
```

It's no suprise. With i18n turned on, the dist folder no longer contains an index.html, that is now in the language bundles' folders.

Has support for i18n been thought through also in the regards that shell and mfe builds of corresponding languages will have to 'meet'? Is that just a matter of where they are hosted relative to each other / what their baseHref is?

**Comment by AGreat1** [comment]
Though I have zero experience when it comes to writing custom builders, it seems like the problem is that your builder assumes outputPath is where everything is supposed to go. Instead it should take the `options.localize` and infer from it the subfolders for each bundle, and edit the index file in each (and I don't know if there are any other uncovered files). I however don't know how to do that, else I would have contributed.

**Comment by manfredsteyer** [comment]
Unfortunately, Angular I18N is not supported.

**Comment by AGreat1** [comment]
Will it not be in the future though? I spent a little more time looking through your code, and I'm interested in contributing if this is otherwise not on/near the top of your list. With a little guidance I feel like I might be able to do it.
