### ISSUE TITLE
Native Federation: error: libs\..\index.ts is missing from the TypeScript compilation.

### ISSUE THREAD

**Issue by DerKapp** [angular-architects/module-federation-plugin#408]
Hello

If I have any library's path configured in the tsconfig `compilerOptions -> paths`, and I don't use this library in the remote or host application, i get the following error.

 >  NX   Build failed with 1 error:
  error: File 'libs\test\test\src\index.ts' is missing from the TypeScript compilation.

This behavior is the same on an NX-Workspace or a CLI Project.
It can be reproduced, by just adding a new Lib and don't use (import) it anywhere AND have the `paths` in the tsconfig configured.

If I remove the tsconfig `paths` configuration it works fine. Also when I use the lib in every remote and host, there is no problem.

I wonder what I'm doing wrong, or why nobody else had this issue.

Thanks for any investigation or help :)

Kind regards
Rafael

**Comment by JanWahl** [comment]
I was about to create a thread about this issue as well.

I got the build working by adding the libraries to the paths of tsconfig of each project, but that results in the issue that e.g. angular services are not shared singletons anymore.

The esbuild command created by the cli still works (I'm using nx e.g. `nx run mfe:build` runs successfully, but `nx run mfe:build` does not

**Comment by MaGnaL** [comment]
I was able to calm it down by adding the local libraries to the `skip` array of `federation.config.js`. I also had to remove `shareAll` because it started to complain about npm dependencies as well.

Not the proper solution I guess, but I could at least proceed with my demo case.

**Comment by ng-multivers** [comment]
i'm facing same issue with NX and native federation , adding libs path to `include` property ended up having those library add to the bundle . Adding to `skip` array in `federation.config `work but it's not a proper solution .

**Comment by DerKapp** [comment]
Thank you all for your ideas on this.
So for now I did the same as you guys, have all the paths correct listed in the `tsconfig.base.ts` and list these paths also in the `skip`  array in `federation.config.js` in those apps where I don't need them.
Like this the bundling is done correct. But it's tricky to have this config correct I guess..

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. It will be fixed with the next minor, 17.1
