### ISSUE TITLE
Micro frontend and shell at the same time?

### ISSUE THREAD

**Issue by julianlumets** [angular-architects/module-federation-plugin#414]
Hi! I had this idea and do not know how to solve it, it would be very important for my project:

I have multiple micro frontends and 1 shell. BUT if I want to use microfrontend 1 inside microfrontend 2, it works in standalone mode. BUT if i load microfrontend 2 into a shell -> it doesn work anymore? The shell says "unknown remote mfe1".

A use case for that would be: I have a bill overview (mfe2) and the bill contains products. Now I want to show product details (mfe1) in a popup inside mfe2. How can I handle that? I know routing via events could solve that but I dont want that.

Any ideas how to solve this error? Or isnt it possible to do so? Thank!

**Comment by manfredsteyer** [comment]
Hi,

do you use Native Federation or Module Federation?

**Comment by julianlumets** [comment]
Hi - thanks for the quick reply. i used native federation

**Comment by JBBianchi** [comment]
Maybe issue #379 can help ?

**Comment by manfredsteyer** [comment]
Yes, you are right. Let's go on with #379
