### ISSUE TITLE
native-federation with ssl, ssl-cert, and ssl-key ng serve parameters

### ISSUE THREAD

**Issue by walter-psjr** [angular-architects/module-federation-plugin#421]
Hi,

I am updating an angular 16 application that is using module-federation 16 to angular 17 with native-federation 17 but i am having problems with some parameters that i use for SSL.

I need to run the ng serve with SSL so i am using this npm start command:

"start:default": "ng serve --port 4201 --ssl --ssl-cert $HOME/.aspnet/https/${npm_package_name}.pem --ssl-key $HOME/.aspnet/https/${npm_package_name}.key"

I am starting the application with npm start. But when i updated to native-federation it started to show this error when i run npm start:

ng serve --port 4201 --ssl --ssl-cert $HOME/.aspnet/https/${npm_package_name}.pem --ssl-key $HOME/.aspnet/https/${npm_package_name}.key

Error: Unknown arguments: ssl, ssl-cert, ssl-key

It is saying that ssl, ssl-cert, and ssl-key are unknown parameters.

How can I run native-federation with SSL with this parameters?

**Comment by walter-psjr** [comment]
I looked at the source code and saw that native-federation is using browser-sync for dev-server, so I added the https options to it and created this pull request:

https://github.com/angular-architects/module-federation-plugin/pull/422

**Comment by manfredsteyer** [comment]
The next minor version of NF will directly delegate to the CLI's dev server. Then, you can set all these usual options in the angular.json.
