### ISSUE TITLE
Issue with importing @angular/compiler under native-federation

### ISSUE THREAD

**Issue by shrek1478** [angular-architects/module-federation-plugin#425]
When importing @angular/compiler under native-federation, a 'SyntaxError: Unexpected token {' appears in the browser console. I thought this is probably due to the following reason :
![image](https://github.com/angular-architects/module-federation-plugin/assets/53067756/a5e33631-3b9a-4508-9f9e-f0fcd3dfc417)

**Comment by Achilles1515** [comment]
No ending backtick after the sourceURL on line 6122 in the dev tools source screenshot. Where did it go??

**Comment by manfredsteyer** [comment]
We could bypass this one, but in general, it seems like using JIT causes issues with native federation.

What's the reason you are using JIT?

**Comment by peiran-sun** [comment]
I didn't choose JIT or AOT but used the default values instead. Could you please guide me on how to set it up to avoid errors? Thank you for your guidance.

**Comment by manfredsteyer** [comment]
The thing is, you should not need to import @angular/compiler. Can you try to remove this import?

**Comment by shrek1478** [comment]
@manfredsteyer 
Thank you very much for your guidance. We've solved the problem by removing the @angular/compiler import and rebuilding the library with the Angular builder instead of the TypeScript compiler.
