### ISSUE TITLE
Expose module and load module in native federation

### ISSUE THREAD

**Issue by JagadishNM** [angular-architects/module-federation-plugin#427]
Is it possible to expose module in native federation and load in shell app.

Getting below issue

![image](https://github.com/angular-architects/module-federation-plugin/assets/91608364/7c951d87-8e39-435d-9173-e0dfc6d3b833)

**Comment by manfredsteyer** [comment]
Do you try to mix Native Federation with Module Federation?

**Comment by JagadishNM** [comment]
I am trying to expose lazy load module from remote and tried to load remote
module into host app.

Used tech:
Native federation: v17
Angular: V17

**Comment by manfredsteyer** [comment]
Can you please provide a simple reproduction?

**Comment by manfredsteyer** [comment]
Ah, got you! Thanks for pointing this out. It will be fixed with the next version on Monday.
