### ISSUE TITLE
The builder doesn't support the default parameters of angular builder.

### ISSUE THREAD

**Issue by lblacio-craft** [angular-architects/module-federation-plugin#428]
The following command is not working with the native federation builder : 
ng serve [project-name] host 0.0.0.0 poll 2000.

The alternative of the parameter Poll is rebuildDelay ? 

![image](https://github.com/angular-architects/module-federation-plugin/assets/119685844/8f1ae8a7-94b5-499c-bec8-0f2f20b9208d)

**Comment by manfredsteyer** [comment]
That's a good point. The next minor version of NF will directly delegate to the CLI's application builder. Then, you can use all these settings in the angular.json.
