### ISSUE TITLE
The alias don't working with native federation builder.

### ISSUE THREAD

**Issue by lblacio-craft** [angular-architects/module-federation-plugin#429]
I tried to use the paths from the tsconfig file but it is not working with my microfrontend projects.

To be sure, I recreated my workspace with standard angular projects with the same ts config. All is working. 

FYI: in tsconfig.base.ts the baseUrl param = './'

![image](https://github.com/angular-architects/module-federation-plugin/assets/119685844/7e4bef57-3988-44b6-9a14-9e1d1bd8cf00)

![image](https://github.com/angular-architects/module-federation-plugin/assets/119685844/f7b00733-cf1b-42c7-8fba-d581a8f9eecc)

**Comment by manfredsteyer** [comment]
Hi,

can you please provide a simple reproduction?

I've tried it out here and it seems to work:
https://github.com/manfredsteyer/nf17x0

Best wishes,
Manfred

**Comment by saithis** [comment]
I have the same error, but only since I upgraded to native federation 17.1

**Comment by manfredsteyer** [comment]
Can you please provide a simple reproduction?

**Comment by lblacio-craft** [comment]
> Can you please provide a simple reproduction?

Hi, it is working now with the new version of Native Federation, I retry with a new project and on mine.
Thank you.

Regards,

Luis Blacio
