### ISSUE TITLE
Not sharing angular libraries throws Error: inject() must be called from an injection context

### ISSUE THREAD

**Issue by scottfwalter** [angular-architects/module-federation-plugin#43]
I have a child app wired up through the router:

```
  {
    path: 'hello',
    loadChildren: () =>
      loadRemoteModule({
        remoteEntry: 'http://localhost:4201/remoteEntry.js',
        remoteName: 'mfe1',
        exposedModule: './HelloModule',
      }).then((m) => m.HelloModule),
  },
```

If the child app does not the angular libraries in its list of shared libraries it throw the error:  

```
ERROR Error: Uncaught (in promise): Error: inject() must be called from an injection context
injectInjectorOnly@http://localhost:4201/default-src_app_hello_hello_module_ts.js:10890:15
ɵɵinject@http://localhost:4201/default-src_app_hello_hello_module_ts.js:10900:61
RouterModule_Factory@http://localhost:4201/default-src_app_hello_hello_module_ts.js:45267:130
hydrate@http://localhost:5000/node_modules_angular_core___ivy_ngcc___fesm2015_core_js.js:11928:35
```

The child app works fine on its own but not when consumed through loadRemoteModule.   If I add the Angular libraries to the shared webpack config in the shared libraries it will work.

Any reason why I can't have the child app load its own version of the Angular libraries?

Thanks, Scott.

**Comment by manfredsteyer** [comment]
Unfortunately, Angular does not support this. A solution is to hide the used Angular version (or any other framework version) behind a web component.
