### ISSUE TITLE
How to use Module Federation with Angular that has a baseHref?

### ISSUE THREAD

**Issue by naeimsf** [angular-architects/module-federation-plugin#432]
Hi guys, does Native Federation Lib work with baseHref? 

https://angular.io/api/common/APP_BASE_HREF
baseHref
deployUrl

all files return 404 at the moment.

cheers

**Comment by naveendanda** [comment]
Did it work ? We are trying to use path based routing and host app doesnt load when we have basehref, it ends with error as 'ailed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.' even though we have basehref generated build.
