### ISSUE TITLE
Angular Dependency Injection: Singleton Service gets instantiated twice -  esbuild, native federation

### ISSUE THREAD

**Issue by DinoCloudlet** [angular-architects/module-federation-plugin#433]
I have build a minimal setup based on the branch nf-standalone-solutions of the example project from the website where a singleton service gets instantiated twice under certain circumstances. The Problem does not occure in a default angular project:

- https://github.com/DinoCloudlet/module-federation-plugin-example-bug

**Changes:**

added File "projects/auth/src/lib/test.all.ts" (component+service+module in one file; it is not important if splitted in multiple files)
added * library export for test.all.ts
imported TestModule in AppModule of the shell app
added test component to app component html and injected the test service into the app component

If you start the shell app, the Service "ComponentTestService" gets instantiated twice (console output in the constructor of the service). In a similar workspace generated with angular, the service only gets instantiated once (without the native module federation but with esbuild).

**I could also isolate the error:**
If the service is not used in the library which defines it, the service gets initialized once even if used in multiple other libraries. The only case i could reproduce this error is if the service is injected in a component of the library itself and at the same time outside of the library (e.g. in the app).

**Comment by DinoCloudlet** [comment]
I asked a couple of other persons they could also reproduce this error. It seems that the service class is registered multiple times in the dependency injection since the class gets defined multiple times during runtime.

**Comment by manfredsteyer** [comment]
Hi,

Thanks for this info. Please ensure you have the latest version of Native Federation: 17.0.7 for Angular 17.0.x or 17.1.0-rc.1 for Angular 17.

I've seen, your package-lock.json prevents you from getting the newest one.
