### ISSUE TITLE
Failed to execute 'importScripts' on 'WorkerGlobalScope': Module scripts don't support importScripts().

### ISSUE THREAD

**Issue by ankurrai2602** [angular-architects/module-federation-plugin#435]
**I am getting issue when web worker file use importScript.** The screenshot is attached, It is working in normal angular 16 project, but not with module federation. Please help.
![image](https://github.com/angular-architects/module-federation-plugin/assets/1185435/9d5a5739-8b50-47e1-8230-cc081a9ad895)

**Comment by manfredsteyer** [comment]
Unfortunately, this is currently not supported
