### ISSUE TITLE
Any plans to use the new application builder now that angular 17.1 is out?

### ISSUE THREAD

**Issue by pamartinez-signify** [angular-architects/module-federation-plugin#437]
Yes, Native Federation is the future here. The current version, 17.0.0, is using browser-esbuild. The next one, 17.1.0, will use the new application builder.

_Originally posted by @manfredsteyer in https://github.com/angular-architects/module-federation-plugin/issues/376#issuecomment-1807212624_

**Comment by manfredsteyer** [comment]
Very soon. You can already now switch to 17.1.0-rc.1. There won't be any changes anymore.
