### ISSUE TITLE
Native federation and PWA not working together.

### ISSUE THREAD

**Issue by Marbulinek** [angular-architects/module-federation-plugin#439]
Hello.
I am trying to implement native federation application. I have shell and remote app. Everything works fine, shell is loading remote after click in navbar. But I have problems with installing angular PWA via ng add @angular/pwa. This is not working (by changes in angular.json file after installing native federation module)
When I manually modified configuration, I was able to run shell in PWA, but I am missing functionality to notify user about shell changes.
That's an issue caused by native federation module.

**Comment by manfredsteyer** [comment]
Hi,

For such scenarios, we have an uninstall schematic. It allows you to temporarily uninstall Native Federation to ng add such packages that expect a default Angular configuration. After that, you can call Native Federation's init schematic again. Your existing federation.config.js will be picked up.

Best wishes,
Manfred
