### ISSUE TITLE
HttpInterceptor Not Intercepting Remote App Requests in Module Federation (Host Bundles Remote)

### ISSUE THREAD

**Issue by Nishanthi** [angular-architects/module-federation-plugin#442]
I'm working on an Angular application using Module Federation. My host application downloads and bundles the plugin/remote application from an artifactory during its build process instead of hosting the remote on a separate server. I then lazy load the remote module by defining its routes in the host app.

My goal is to have the host app's httpInterceptor intercept requests made by the remote application as well.
I've included @angular/common/http with singleton: true, strictVersion: true, requiredVersion: 'auto' in the "shared" object of both host and remote webpack.config.ts files.

Unfortunately, this isn't happening, though I assumed the remote here to work similarly to any other lazy loaded module.

I'm looking for suggestions or ideas for troubleshooting this issue.
Are there any additional considerations for sharing HttpClientModule or configuring interceptors in this specific Module Federation setup with bundled remote applications?

**Comment by manfredsteyer** [comment]
Can you please provide a very simple reproduction of this? It should indeed work like with lazy loading.
