### ISSUE TITLE
Change port where micro frontend runs

### ISSUE THREAD

**Issue by julianlumets** [angular-architects/module-federation-plugin#443]
Hi! I implemented a few MFEs with native federation - so far so good. Now i want to change the port of one micro frontend. How can I do that? I made a full text search with the current port number in vs code and got one search result in angular.json as you can see here:
![image](https://github.com/angular-architects/module-federation-plugin/assets/84586104/72e075e2-154c-478b-89eb-dceb6c150444)

I replaced the port in angular json with my new one BUT if i execute ng serve - it still runs on the old port. When i access the new port it says ERROR CANNOT GET. And it shows this error:
![image](https://github.com/angular-architects/module-federation-plugin/assets/84586104/ebf74988-0530-45e7-8ae2-7e2cb820311c)

Thank you for your answers!

**Comment by julianlumets** [comment]
UPDATE: Even if i create a new micro frontend with ng g @angular-architects/native-federation:init --project mfe1 --port 4201 --type remote

The port when i run ng serve is 4200 and even if i run this command with --port 4201 -> the same error appears like in the picture above!

**Comment by julianlumets** [comment]
Another UPDATE:
I found out that THIS PROBLEM has something to do with the version of native federation!

I created the new project with native federation @ 17.1.1 (CAUSES THE PROBLEM!). Then i created a projects with the version @ 17.0.7 and it works perfectly again!

I hope that the team fixes this ASAP - i love this package and the mental module behind MFEs. Keep up the great work!

**Comment by julianlumets** [comment]
Update: I tried also the UPGRADE Guide for Angular 17.1 too and the problem is that it cannot start because of the missing path argument in the CLI as you already mentioned. Even with the windows powershell the applications do not start!

**Comment by manfredsteyer** [comment]
Thanks for the workaround and thanks for pointing this out.

We will update the ng-add schematic asap to make this work.

**Comment by julianlumets** [comment]
Thank you - i love the mental model behind Microfrontends so i try my best to improve it!

**Comment by manfredsteyer** [comment]
This is resolved now.
