### ISSUE TITLE
Native Federation doesnt support PWA

### ISSUE THREAD

**Issue by Marbulinek** [angular-architects/module-federation-plugin#444]
When you install angular PWA and then native federation (v. 17.1.1), is not compatible together.

Steps to reproduce
* prepare shell and mfe1 projects
* install PWA into the shell application ( ng add @angular/pwa)
* install native federation for shell and mfe1 and do basic native federation setup
* run shell as PWA application. You can see Service Worker, also "install application" icon
* change shell component code
* press F5 to see how PWA will notify us about code change in shell project.
 

__Here you can see issue in the console, when service worker in the shell register changes in the code:__

```
Failed to install app version 'ba26c71599a1f0659db57d9bfd88189cf776562a': Hash mismatch (cacheBustedFetchFromNetwork): 
https://my-website.com/shell/index.html: expected 42f3a2438c0057d38ce5056b3aa640913e30a3e2, got a8909d252e746f6123a05e4ab0d40c8750dead2b (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://my-website.com/shell/index.html: expected 42f3a2438c0057d38ce5056b3aa640913e30a3e2, got a8909d252e746f6123a05e4ab0d40c8750dead2b (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://my-website.com/shell/ngsw-worker.js:479:21)
    at async PrefetchAssetGroup.fetchFromNetwork (https://my-website.com/shell/ngsw-worker.js:454:19)
    at async PrefetchAssetGroup.fetchAndCacheOnce (https://my-website.com/shell/ngsw-worker.js:433:21)
    at async https://my-website.com/shell/ngsw-worker.js:538:9
    at async https://my-website.com/shell/ngsw-worker.js:524:9
    at async https://my-website.com/shell/ngsw-worker.js:524:9
    at async https://my-website.com/shell/ngsw-worker.js:524:9
    at async https://my-website.com/shell/ngsw-worker.js:524:9
    at async PrefetchAssetGroup.initializeFully (https://my-website.com/shell/ngsw-worker.js:523:7)
    at async https://my-website.com/shell/ngsw-worker.js:927:11
```

**Comment by manfredsteyer** [comment]
Yes, this is currently not supported. In general, it would be hard to make both worlds work together because the host's service worker doesn't know a thing about the remotes. Also, Angular's simple PWA support is a turn-key solution that assumes everything is known at compile time. If you really need PWA support + Federation, I would use sth like workbox.
