### ISSUE TITLE
Not working with Angular 12

### ISSUE THREAD

**Issue by rkanthaliya** [angular-architects/module-federation-plugin#45]
Hi,

I have upgraded my project to angular 12 and when I run the below command 

**ng add @angular-architects/module-federation --project shell --port 4200**

I am getting "Mf" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.

@manfredsteyer

**Comment by sean-perkins** [comment]
@rkanthaliya Upgrade to `@next`.

See the discussion here: https://github.com/angular-architects/module-federation-plugin/issues/34#issuecomment-831489612
