### ISSUE TITLE
Error: Module parse failed for @angular-architects/module-federation with Webpack Version 17.0.2

### ISSUE THREAD

**Issue by raulmelo** [angular-architects/module-federation-plugin#462]
### Issue Overview:
While building an Angular application that utilizes the Module Federation feature from @angular-architects/module-federation, I encountered a webpack compilation error that prevents the application from building successfully. The error is related to the handling of ES6 module syntax (import and export statements).

### Error Message:

```bash
[error] 86.60 ./node_modules/@angular-architects/module-federation/src/index.js:1:0 - Error: Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
[error] 86.60 File was processed with these loaders:
[error] 86.60  * ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js
[error] 86.60 You may need an additional loader to handle the result of these loaders.
[error] 86.60 > export * from '@angular-architects/module-federation-runtime';

```

### Possible Causes/Solutions:
It seems that Webpack or its loaders might not be correctly configured to handle ES6 modules. I have tried adjusting the webpack configuration and ensuring all related dependencies (webpack, babel-loader, etc.) are up to date without success.

Angular version: 17.1
Node.js version:  18
Operating System: OS

## 
The error occurred when I installed version 17.0.2. To resolve it, I reverted to version 17.0.1:

```js
"@angular-architects/module-federation": "17.0.1",
"@angular-architects/module-federation-tools": "17.0.1",
```

## tsconfig
<img width="591" alt="image" src="https://github.com/angular-architects/module-federation-plugin/assets/8516551/7466f8cd-b65c-4cfd-8b0b-37508a9f8e0f">

**Comment by JagadishNM** [comment]
getting same issue
![image](https://github.com/angular-architects/module-federation-plugin/assets/91608364/2234a5f4-e202-4909-b10f-44ca2f22443f)

**Comment by Sonajos** [comment]
Hi, I am getting the same results with the updated version. Reverting to 17.0.1 helped.

Our project has:
```JSON
tsconfig.json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "node",
    "importHelpers": true,
    "lib": ["ES2022","dom"],
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true,
  }
}
```

**Comment by manfredsteyer** [comment]
Thanks for this information. Just published a new version that fixes this issue.
