### ISSUE TITLE
Native federation and poor developer experience due to no live reloading of changes

### ISSUE THREAD

**Issue by Frank-Troia** [angular-architects/module-federation-plugin#463]
I've recently incorporated native federation to my Angular 17.1.1 project. We are using Nx so we follow a typical Nx monorepo structure where apps are thin and they pull in libraries. So most of the code for the host or remotes exists in libraries, not the apps.

I'm noticing two use cases that are leading to poor developer experience when using native federation over module federation.

1. Changes made to libraries are not reflected without a restart of the server, whether host or remote.
2. Changes made to remotes are not reflected on the host server without a restart of the remote server.

Repro is here
https://github.com/franktroia/nf-library-bug

To test each scenario, you can do the following

1. If you run `ng serve test-app` and adjust the `test-lib.component.html`, you will see that the library does not reload on localhost:4200. To get the changes live, you must re-run `ng serve test-app`
2. If you also run `ng serve remote-app` and adjust the `app.component.html`, you will see that the remote changes are not present in localhost:4200 even after a page refresh (F5). However, they are present at localhost:4201 as expected. The only way to make the changes present in localhost:4200 is to re-run `ng serve remote-app`.

Given these limitations, it will be challenging to adopt native federation for our team. Can you tell me whether I am doing something wrong? Or this is working as designed?

Forgive me, as I am slightly re-opening #450.

Any help would be appreciated!

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. We will look into this asap!

**Comment by manfredsteyer** [comment]
Just published a new patch version that fixes this issue.
However, you still need to press F5 in the shell after changing a remote.

**Comment by Frank-Troia** [comment]
@manfredsteyer Thanks! I pulled down the patch and it is improved!

**Comment by kryshac** [comment]
@manfredsteyer, hello, if the path is from the dist, it still doesn't work, but with serve-original it still works ok
```
"paths": {
    "@lib/my-lib": ["./dist/my-lib"]
}
```

**Comment by manfredsteyer** [comment]
Yes, that's right. It's currently implemented for "Nx-style" path mappings pointing to the src folder.
