### ISSUE TITLE
standalone implementation of bootstrap

### ISSUE THREAD

**Issue by dexster** [angular-architects/module-federation-plugin#465]
Is there a standalone version of the bootstrap method used to assist with a remote web component inside a shell with a different   ng version? 

The bootstrap example expects a module like so:
```ts
export class AppModule implements DoBoostrap { constructor(private injector: Injector) {
}
ngDoBootstrap() {
const ce = createCustomElement(AppComponent, {injector: this.injector}); customElements.define('angular1-element', ce);
} }

bootstrap(AppModule, {
   production: environment.production,
   appType: 'microfrontend' // for micro frontend // appType: 'shell', // for shell
});
```

but my web component is initialised like this:
```ts
(async () => {
  const app = await createApplication({providers: []});
  const toggleElement = createCustomElement(NxWelcomeComponent, {
    injector: app.injector,
  });
  customElements.define('my-toggle', toggleElement);
})();
```

**Comment by manfredsteyer** [comment]
Not really, You needed to write this by yourself.

**Comment by bh3605** [comment]
@manfredsteyer I'm a little confused about this nonchalant response. Angular says the future is with stand-alone components so in order for this library to continue to thrive I see it as a natural progression to support bootstrapping a stand-alone component as your shell.
