### ISSUE TITLE
Can't run `ng add` for version 17 of @angular-architects/module-federation - Cannot read properties of null (reading 'version')

### ISSUE THREAD

**Issue by edumserrano** [angular-architects/module-federation-plugin#468]
## Problem description

When I try to do:

```
npx ng add @angular-architects/module-federation@17.0.6
```

I get:

```
ℹ Using package manager: npm
✔ Package information loaded.

The package @angular-architects/module-federation@17.0.6 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
? Project name (press enter for default project) remote-ng17
? Port to use 4200
Cannot read properties of null (reading 'version')
```

or when I try to do:

```
ng g @angular-architects/module-federation:init --project host-ng17 --port 4200 --type host
```

I get:

```
Cannot read properties of null (reading 'version')
```

## How to reproduce

1) Create an ng 17 app with `ng new`.
2) Update the `angular.json` so that it uses the `browser` builder instead of the `application` builder. Here what I did was copy the `angular.json` from an Angular 16 app. My `angular.json` for my Angular 17 using the `browser` builder looks like:
```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "host-ng17": {
      "projectType": "application",
      "schematics": {},
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/host-ng17",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": ["zone.js"],
            "tsConfig": "tsconfig.app.json",
            "assets": ["src/favicon.ico", "src/assets"],
            "styles": ["src/styles.css"],
            "scripts": []
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "host-ng17:build:production"
            },
            "development": {
              "browserTarget": "host-ng17:build:development"
            }
          },
          "defaultConfiguration": "development"
        }
      }
    }
  }
}

```
3) Run 
```
npx ng add @angular-architects/module-federation@17.0.6
```

## Other information

- I'm running on `Windows 11 Version 23H2 (OS Build 22631.3007)`.
- The commands above were executed with `PowerShell 7.4.1`.
- The app is using `Angular 17.1.3` and my `package.json` looks like:

```json
{
  "name": "host-ng17",
  "version": "0.0.0",
  "scripts": {
    "start": "npx ng serve"
  },
  "private": true,
  "dependencies": {
    "@angular-architects/module-federation": "^17.0.6",
    "@angular/animations": "^17.1.3",
    "@angular/common": "^17.1.3",
    "@angular/compiler": "^17.1.3",
    "@angular/core": "^17.1.3",
    "@angular/forms": "^17.1.3",
    "@angular/platform-browser": "^17.1.3",
    "@angular/platform-browser-dynamic": "^17.1.3",
    "@angular/router": "^17.1.3",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.1.3",
    "@angular/cli": "^17.1.3",
    "@angular/compiler-cli": "^17.1.3",
    "typescript": "~5.3.2"
  }
}
```

**Comment by ccuamatzin-pilot** [comment]
I have the same issue

**Comment by abdelhafidel** [comment]
same here help !!!

**Comment by MihaiStancescu** [comment]
Yes, same problem here.

**Comment by MihaiStancescu** [comment]
Quick and ugly workaround until a proper fix is like this: 

1. install the package
2. you will get the error above
3. go to node_modules/@angular-architects/module-federation/src/schematics/mf/schematic.js 
4. change line 110 to ` const useDevServer = dep && dep.version && semver.satisfies(semver.minVersion(dep.version), '>=17.2.0');`
5. **This is a hack and a workaround while we wait for a proper fix.**

**Comment by abdelhafidel** [comment]
I have had the same issue so the problem was the version of @angular-architects/module-federation 17.0.6 so i downgrade the version to 17.0.1 : 
- ng add @angular-architects/module-federation@17.0.1 
the angular working package : 
 {
  "name": "shell",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "run:all": "node node_modules/@angular-architects/module-federation/src/server/mf-dev-server.js"
  },
  "private": true,
  "dependencies": {
    "@angular-architects/module-federation": "^17.0.1",
    "@angular/animations": "^17.2.0",
    "@angular/common": "^17.2.0",
    "@angular/compiler": "^17.2.0",
    "@angular/core": "^17.2.0",
    "@angular/forms": "^17.2.0",
    "@angular/platform-browser": "^17.2.0",
    "@angular/platform-browser-dynamic": "^17.2.0",
    "@angular/router": "^17.2.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.2.0",
    "@angular/cli": "^17.2.0",
    "@angular/compiler-cli": "^17.2.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "ngx-build-plus": "^17.0.0",
    "typescript": "~5.3.2"
  }
}

**Comment by diegocontreras2** [comment]
i same problemen

![image](https://github.com/angular-architects/module-federation-plugin/assets/42698568/b8bf0830-8b83-48dd-8869-f2f40b851350)

**Comment by manfredsteyer** [comment]
Hi,

Thanks for pointing this out, and big thanks to @MihaiStancescu for analyzing the source of this. 

It's fixed now.

Best wishes,
Manfred
