### ISSUE TITLE
NF: going dynamic dynamic

### ISSUE THREAD

**Issue by mbertuzzi** [angular-architects/module-federation-plugin#469]
Hello, 
I'm using Angular 17.2 with Native Federation 17.1, trying to dynamically add remote modules (unknown at build time).

First, I load the shell with my basic manifest 

```
initFederation('/assets/federation.manifest.json')
  .catch(err => console.error(err))
  .then(_ => import('./bootstrap'))
  .catch(err => console.error(err));
```

Then after the user auth I need to load it's activated modules.
There is a method to do that without errors? 

Simply re-do initFederation with complete manifest object gives error (Error: Rejected map override "@angular/animations"), seems for duplicated 'importmap-shim'.

I got it by doing this, but it's the right way?

```
export async function updateFederation(manifestObj: Record<string, string>) {
  const scripts = document.body.getElementsByTagName("script");
  for (let i = 0; i < scripts.length; i++) {
    const script = scripts.item(i) as HTMLScriptElement;
    if (script.type == "importmap-shim") {
      document.body.removeChild(script);
    }
  }
  await initFederation(manifestObj);
}
```

thanks 
Michael

**Comment by manfredsteyer** [comment]
Hi Michael,

in this case, you can use the following overload of `loadRemoteModule`:

```typescript
loadRemoteModule({ remoteEntry: 'http://...', exposedModule: './Module'})
```

**Comment by mbertuzzi** [comment]
Hi Manfred,
thanks, it works !!
