### ISSUE TITLE
Angular 17 Module-federation migration issue

### ISSUE THREAD

**Issue by ips219** [angular-architects/module-federation-plugin#470]
Hi...

I'm trying to upgrade a project that is using module federation plugin form Angular 16 to Angular 17.

I've completed all steps, but when I try to start the dev server compilation fails with this error.

`
./node_modules/.pnpm/@angular-architects+module-federation@17.0.7_@angular+common@17.2.1_@angular+core@17.2.1/node_modules/@angular-architects/module-federation/src/index.js:1:0 - Error: Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
File was processed with these loaders:
 * ./node_modules/.pnpm/@angular-devkit+build-angular@17.2.0_@angular+compiler-cli@17.2.1_@angular+service-worker@17._u3ellmvlmecn5ih2nygj2ptcxi/node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js
 * ./node_modules/.pnpm/@ngtools+webpack@17.2.0_@angular+compiler-cli@17.2.1_typescript@5.3.3_webpack@5.90.1/node_modules/@ngtools/webpack/src/ivy/index.js
 * ./node_modules/.pnpm/source-map-loader@5.0.0_webpack@5.90.1/node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> export * from '@angular-architects/module-federation-runtime';
`

I did upgrade angular, typescript, eslint, etc..

Does anybody faced this issue?

Thanks and best regards.

**Comment by ghbarton** [comment]
I've had this same issue today. Using 17.0.6 works so maybe an issue with the latest release.

**Comment by Sabbacus** [comment]
I haven't seen any blog post about support for Angular 17.2. On the other hand, I have not anything about Module/Native federation being broken with Angular 17.2 either.

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. It was due to wrong meta mata in the package.json. It's fixed now.
