### ISSUE TITLE
Error on build when use package @taiga-ui/icons

### ISSUE THREAD

**Issue by MrPhelko** [angular-architects/module-federation-plugin#471]
Hello. When using your version 17.1.0+ native federation with https://github.com/taiga-family/taiga-ui, I get a build error.

**Comment by manfredsteyer** [comment]
Hi @MrPhelko,

Thanks for pointing this out. It looks like this npm package also includes its own build scripts using dev dependencies that are not referenced. Hence, these scripts cannot be compiled.

You can make Native Federation ignore these scripts by adding the following entry to the skip list in your ``federation.config.json``:

```javascript
  skip: [
    'rxjs/ajax',
    'rxjs/fetch',
    'rxjs/testing',
    'rxjs/webSocket',
   
    // Add this line:
    '@taiga-ui/icons/scripts'
   
  ]
```

**Comment by MrPhelko** [comment]
@manfredsteyer thx
