### ISSUE TITLE
Unable to resolve specifier when importing from @angular/common/locales/de

### ISSUE THREAD

**Issue by rehdie** [angular-architects/module-federation-plugin#473]
If you want to add native-federation to a microfont-end, which uses a libary that imports from @angular/common/locales/de, the micro-frontend application doesn't work anymore due to the following runtime error: 

> Unable to resolve specifier '@angular/common/locales/de' imported from ......

I've created a repository, which can be used to reproduce the problem: https://github.com/rehdie/native-federation-test

The repository contains an angular workspace which contains 

- a library "test-lib"  with a single component StackComponent (not a standalone component. It is part of an NgModule). The library-module contains imports from @angular/common/locales/de (I know, that they are not needed in that library but it reproduces the problem).
- a microfront-end, which uses that StackComponent

The readme in that repository describes,  how to reproduce the problem.

**Comment by rehdie** [comment]
OK, my bad.

I have to add '@angular/common/locales/de' to sharedMappings in federation.config.js.  Then it works fine.

**Comment by kryshac** [comment]
when I run with serve everything works ok, but if I build it with prod then it doesn't create files for locales. @rehdie  did you have this problem?

**Comment by ips219** [comment]
Hello @rehdie can you provide an snipet of your federation.config?

I have the same issue as my remote includes several @angular/common/locales/... 
![image](https://github.com/angular-architects/module-federation-plugin/assets/3368591/0cd9e2ed-0aca-4a4f-9af9-6b0b76aab168)

But in my case I've got same result.

Best regards

**Comment by kryshac** [comment]
@ips219 you can try [this](https://github.com/angular-architects/module-federation-plugin/issues/524#issuecomment-2004550256) patch

**Comment by ravigaudani0909** [comment]
@ips219 Did you managed to fix the issue? because I also tried using **sharedMappings** and not working for me.

Also @kryshac I tried using patch as well but not working that as well

![image](https://github.com/angular-architects/module-federation-plugin/assets/126670676/96b5c840-36d7-4376-8929-7f8188199c12)

**Comment by ips219** [comment]
Hi...

Finally in the federation.config.js I did not change anythoing related to locales.

I did an small workaround in my mfe module.... Basically, I registered manually the locales in the MFE construtor and the build process didn't raised this error anymore.

![image](https://github.com/angular-architects/module-federation-plugin/assets/3368591/3e397f70-36bd-4c99-943b-a8dd65950385)

**Comment by ravigaudani0909** [comment]
Thanks for the info.
In my case I'm using `@angular-architects/native-federation: "^17.1.8"` and `Angular 17.3.0` so there is no app module.
Also I'm getting error directly on `ng serve`

**Comment by kryshac** [comment]
@ravigaudani0909 where did you set share in shell or in mfe?
and are you sure that the patch was applied?
you can make a demo repo where you have errors and I will be able to look there

**Comment by ravigaudani0909** [comment]
@kryshac [Here](https://github.com/ravigaudani0909/test-native-federation) is demo repo, please check readme to reproduce.

**Comment by kryshac** [comment]
@ravigaudani0909 can you check in [pr](https://github.com/ravigaudani0909/test-native-federation/pull/1)?

**Comment by ravigaudani0909** [comment]
Thanks you @kryshac it's working now with your patch. Any idea when it will be implemented in actual repo @angular-architects/native-federation?

**Comment by kryshac** [comment]
I’m not sure, as I asked about it on this [issues](https://github.com/angular-architects/module-federation-plugin/issues/524), but haven't received a response from any of the contributors yet.

**Comment by vahidsamimi** [comment]
I get the ERROR Error: Unable to resolve specifier 'date-fns/format. how can I fix it?

**Comment by kryshac** [comment]
@vahidsamimi  hi, how did you import?

**Comment by joepeace01** [comment]
Hi, I'm having a similar issue but didn't got any luck fixing it. 

<img width="1067" alt="Capture d’écran 2024-11-28 à 16 47 42" src="https://github.com/user-attachments/assets/69099088-f19f-4265-8557-f9a988f35ba4">

It seems that the error happen during the bootstraping of the app with es-module-shims. I only get a static page of my home page and none of the api calls are working

**Comment by joepeace01** [comment]
yes, the funny thing is that everything is working great on my shell app, I only have the issue with my remote app (both app are on different repositories with similar configuration)

**Comment by ladler1** [comment]
@joepeace01 have you tried to solve it using shim-mode: https://www.npmjs.com/package/es-module-shims/v/1.0.1 `<script type="module-shim">` on your main bundle?

**Comment by fpd007** [comment]
I tried adding either `<script type="module-shim"></script>` or  `<script type="esms-options">{ "shimMode": true }</script>` to the `index.html` but both did not help with that error. `shimMode` seems to be enabled.

**Comment by fpd007** [comment]
I resolved this issue by https://github.com/angular-architects/module-federation-plugin/issues/524#issuecomment-2580458399

**Comment by oshek14** [comment]
> yes, the funny thing is that everything is working great on my shell app, I only have the issue with my remote app (both app are on different repositories with similar configuration)

Did you find solution?

**Comment by brahim242455555** [comment]
Successfully configured PrimeNG with a custom French translation (frenchLocale) for calendar and UI components, and applied the Aura theme using providePrimeNG in the application configuration. 

export const frenchLocale = {
  firstDayOfWeek: 1,
  dayNames: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
  dayNamesShort: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
  dayNamesMin: ["D", "L", "M", "M", "J", "V", "S"],
  monthNames: [
    "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
    "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"
  ],
  monthNamesShort: ["Jan", "Fév", "Mar", "Avr", "Mai", "Juin", "Juil", "Aoû", "Sep", "Oct", "Nov", "Déc"],
  today: "Aujourd'hui",
  clear: "Effacer",
  dateFormat: "dd/mm/yy",
  weekHeader: "Sem"
};


import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter, withInMemoryScrolling } from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { providePrimeNG } from 'primeng/config';
import Aura from '@primeng/themes/aura';
import { routes } from './app.routes';
import { frenchLocale } from './config/primeng-locale';


export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withInMemoryScrolling({ scrollPositionRestoration: 'enabled' })),
    provideAnimationsAsync(),
    providePrimeNG({
      translation: frenchLocale,
      theme: {
          preset: Aura
      }
  })
  ]
};

**Comment by bh3605** [comment]
@joris-ondo-edzang Did you find a solution? I'm seeing the exact same error you are.

**Comment by bh3605** [comment]
Add this fixed my problem.
```
  <script type="esms-options">
  {
    "shimMode": true
  }
  </script>
```
