### ISSUE TITLE
Native Federation: Angular Version Missmatch

### ISSUE THREAD

**Issue by DerKapp** [angular-architects/module-federation-plugin#474]
I get a weird error when I load a remote MFE with a lesser angular version:
![image](https://github.com/angular-architects/module-federation-plugin/assets/22842655/ddcd9b95-f847-47e5-973a-305f45d9131d)

My setup is really basic, no web-components, just plain Angular with Native Federation.
Should this work? I have never seen an example or something where this scenario was shown, which gives me concerns if this case is supported.

Does anybody have a working version of a scenario where the host and the remote have **not** the same angular version?

**Comment by manfredsteyer** [comment]
Can you please let me have a simple reproduction of this issue?

**Comment by manfredsteyer** [comment]
Ah, now I got it. So, if you have different versions of Angular, you really need to wrap them up in Web Components. Here are some details: https://www.angulararchitects.io/blog/micro-frontends-with-modern-angular-part-2-multi-version-and-multi-framework-solutions-with-angular-elements-and-web-components/
