### ISSUE TITLE
Native Federation: How to use Angular Material globally and in each mfe ?

### ISSUE THREAD

**Issue by alaindeurveilher** [angular-architects/module-federation-plugin#478]
Hello,

I have this starter project built with Angular 17 and Native Federation.
https://github.com/alaindeurveilher/ng-mfe-app-starter/tree/starter-routing

I would like to know how to setup each application to use Angular Material, so that each MFE when being served in isolation (in development mode) would be using Angular Material as well as when being loaded in the shell.

And potentially one custom theme to be used by each of them. Let's say it would be the company/corporate theme and design.

I did not find much documentation around here about how to properly configure Angular Material, and sharing theming in general with micro frontends built up with Native Federation.

Thank you.

**Comment by alaindeurveilher** [comment]
At the moment I ended up installing @angular/material globally without specifying any project, and then setting up material in each of the micro frontends manually, as it would be expected after the installation by the ng add command:

https://github.com/alaindeurveilher/ng-mfe-app-starter/tree/with-material?tab=readme-ov-file#adding-angular-material

But I wonder if there would be an automatic sort of way to do it.

Thank you.

**Comment by manfredsteyer** [comment]
Yes, this is the way to go. Install it everywhere and Federation make sure at runtime that it's only loaded once.
