### ISSUE TITLE
Native Federation: Library with different version is not shared as expected due to config of required version

### ISSUE THREAD

**Issue by maan1112** [angular-architects/module-federation-plugin#479]
Hello,

I have create a dynamic shell and a remote as described under 
https://www.npmjs.com/package/@angular-architects/native-federation

I have installed useless-lib@1.0.1 in the shell and useless-lib@1.0.0 in the remote application.

After integrating the remote into the shell I would expect that lib version 1.0.1 is shared, but the library is loaded in both versions.

![image](https://github.com/angular-architects/module-federation-plugin/assets/85104579/84b840ec-ede4-4a29-81fc-bf1ccb70ef2e)

The source code can be found under
https://github.com/maan1112/native-federation-shell
https://github.com/maan1112/native-federation-remote

How to configure remote to use shells library?

Thanks M.

**Comment by manfredsteyer** [comment]
Yes, that's true. Currently, Native Federation uses a simplified strategy: It only shares libs if they have **exactly** the same version. This makes sense in the case of Angular because compiled Angular code uses parts of Angular's private API and there are no guarantees in terms of semver for private APIs.

Nevertheless, sooner or later, we will provide the flexibility known from module federation.

**Comment by legrottagliegionata** [comment]
Hello,

I would like to ask whether there have been any updates or plans regarding this limitation.

At the moment, a simplified sharing strategy based on *exact version matching* seems quite restrictive in real-world Angular setups. Angular’s dependency injection relies on `InjectionToken`s, and having multiple versions of the same shared library loaded at runtime can lead to inconsistent behavior. For example, a service declared with `providedIn: "root"` would effectively produce multiple instances — one per library version — potentially causing hard-to-detect issues.

In a configuration where a shared library is declared with:

```
strictVersion: true
requiredVersion: "auto"
```

I would expect Native Federation to resolve compatible versions automatically. For instance, if different remotes depend on versions compatible with `^1.0.0`, it would be reasonable for the federation runtime to select the highest compatible version available among all remotes loaded during `initFederation`.

Such behavior would allow updating a library used only by some remotes without requiring a full rebuild of the entire federation, which is currently one of the main advantages expected from a micro-frontend architecture.

Are there any ongoing discussions, roadmap items, or experimental approaches planned to introduce a more flexible version resolution similar to Module Federation?

Thank you.

**Comment by Aukevanoost** [comment]
Hi @legrottagliegionata, 

If you want you can have a look at this issue, this is a bit more up-to-date: https://github.com/angular-architects/module-federation-plugin/issues/1093
