### ISSUE TITLE
During upgrade  - "Collection does not have a schematics map."

### ISSUE THREAD

**Issue by tonybrasunas-greenlots** [angular-architects/module-federation-plugin#487]
I'm upgrading a set of Angular applications from v12 to v16, and they use Module Federation and this plugin.

After upgrading each app's Angular version successfully, and going one version at a time, I run the update command for the module federation plug-in. (Eg `ng update @angular-architects/module-federation@15`)

I get this 
``` 
An unhandled exception occurred: Collection "[app dir location]node_modules/@angular-architects/module-federation/migrations.json" 
does not have a schematics map.
See "/private/var/folders/m_/s6hjt4t90170wpj43zq_g_q80000gr/T/ng-yftav3/angular-errors.log" for further details.
```

- What is this schematics map of which they speak? 
- And is it an important error or something I can ignore. The app seems to work after the upgrade despite this error. 

I've tried updating `@angular-eslint/schematics` and `@schematics/angular` but they don't seem to fix the issue either.

**Comment by manfredsteyer** [comment]
I think you can ignore it. Just make sure, the config in the angular.json works for you. The best way to get a good config as a template is creating a new angular project and adding mf.
