### ISSUE TITLE
after a package is put in shared, the import no longer works

### ISSUE THREAD

**Issue by kryshac** [angular-architects/module-federation-plugin#488]
This is an example with the qs library. I have issues with multiple libraries.
```js
import { stringify } from 'qs';

console.log(stringify({ a: 1, b: 2 }));
```

If I exclude qs, then it works correctly:
```js
const { withNativeFederation, shareAll } = require('@angular-architects/native-federation/config');

module.exports = withNativeFederation({
  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
  },

  skip: [
    'qs',
  ],
});
```

But if qs is shared, I receive this error: SyntaxError: import not found: stringify.

Here is the export from qs:
```js
'use strict';

var stringify = require('./stringify');
var parse = require('./parse');
var formats = require('./formats');

module.exports = {
    formats: formats,
    parse: parse,
    stringify: stringify
};
```

I think the problem is that it converts to CommonJS when it is of type shared.

If I use this type of import:
```js
import qs from 'qs';

console.log(qs.stringify({ a: 1, b: 2 }));
```
Then there is no problem, but we have many libraries, and the project is quite large to change everywhere. What could we do?
Thanks

**Comment by manfredsteyer** [comment]
Please have a look here: #460

Best wishes,
Manfred
