### ISSUE TITLE
Generating Browser Application Bundles

### ISSUE THREAD

**Issue by marct83** [angular-architects/module-federation-plugin#5]
Testing the plugin and trying to build a mircrofrontend. ng serve seems to be getting hung up at: 

Generating browser application bundles (phase: building)...

Verbose flag doesn't seem to give any more information on what it's doing. 

Any ideas?

**Comment by manfredsteyer** [comment]
There is currently a bug with ``styleUrls``. Please try to comment out **all** usages of ``styleUrls`` and then start ng serve again. Does this work?

**Comment by marct83** [comment]
I removed them and it still is not building.

**Comment by manfredsteyer** [comment]
interesting. Can you provide your example? I'd love to have a look at it.

**Comment by zhangjindong** [comment]
https://github.com/zhangjindong/angular11-test.git
![angular11-test](https://user-images.githubusercontent.com/5567162/100730210-bb310e80-3404-11eb-864f-3c2fd28ef666.png)
Always prompt ”Generating browser application bundles (phase: building)...“。
Seems to be related to auth-lib

**Comment by manfredsteyer** [comment]
Thanks. Found it. Please have a look at the pitfalls section at [1]. It describes some limitations we currently have when sharing libs within a monorepo. Hopefully, this goes away, once the CLI/webpack5 integration isn't experimental anymore (CLI 12).

In your case, it's the usage of styleUrls and sharing a lib via webpack.config.js that isn't used. 

If you have further questions, please reach out.


[1] https://www.npmjs.com/package/@angular-architects/module-federation#user-content-pitfalls-when-sharing-libraries-of-a-monorepo

**Comment by Navrotskyi** [comment]
@manfredsteyer @marct83 You can update angular cli and angular packages to 11.1.0-next.1 and styleUrls will be working with shared libs

**Comment by zhangjindong** [comment]
@manfredsteyer 
Thank you very much, I understand.
I wish you a happy life.

**Comment by speedy32** [comment]
In my case it doesn't work with nay urls from node_modules. Even after install @angular/cli@11.1.0-next.1
![image](https://user-images.githubusercontent.com/8421691/101390222-c2ec2980-38c2-11eb-850d-0de627ff2fa5.png)

**Comment by zhangjindong** [comment]
@manfredsteyer 
Hi,I found that this project can run normally.
But I did not find anything special through comparison.
Please help analyze the reason for success.

https://github.com/zhangjindong/test-tailwind-antd.git

**Comment by Jordan-Hall** [comment]
@manfredsteyer when you upgrade to angular 11.1.0-beta-1 im getting the following error on NX library 

`Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader (/Users/libertyware/dev/clients/liberty-travel-system/node_modules/@ngtools/webpack/src/ivy/loader.js:28:18)

Error: Conflict: Multiple assets emit different content to the same filename libs_api-interfaces_src_index_ts.js`

**Comment by manfredsteyer** [comment]
@Jordan-Hall I know this one.

Please try to use this setting in your webpack cofig as a sibling of publicName:

```
chunkFilename: '[name]-[contenthash].js',
```

**Comment by Al00X** [comment]
@manfredsteyer @marct83  To fix serve hung, go to your `tsconfig.json` and under `paths`, remove the `.ts` extesion.
for example : 

Change this
> "paths": {
      "@lib/auth": ["libs/auth/src/index.ts"]
    }

To this

> "paths": {
      "@lib/auth": ["libs/auth/src/index"]
    }

It's a very weird fix!

**Comment by Al00X** [comment]
@manfredsteyer But I still have another and I had no luck fixing it

> ./libs/weather/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: The AngularCompilerPlugin was not found. The @ngtools/webpack loader requires the plugin.
    at Object.ngcLoader (...\node_modules\@ngtools\webpack\src\loader.js:29:15)

I can ignore this error and serve my app; But I can't build it.

**Comment by pschnoop** [comment]
Hey,
If I remove the `.ts` ending from `tsconfig.json` the build does not hang anymore, but now I receive the following error:
```
./libs/core/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: The AngularCompilerPlugin was not found. The @ngtools/webpack loader requires the plugin.
    at Object.ngcLoader (C:\dev\FatVegan\node_modules\@ngtools\webpack\src\loader.js:29:15)
```
Any suggestions on how to fix this? ^^'

**Comment by manfredsteyer** [comment]
Can you please give it another try with Angular 12.0.0-rc.1 and version 12.0.0-rc.1 of this plugin? We've fixed several issues there.
