### ISSUE TITLE
Duplicate bundles

### ISSUE THREAD

**Issue by hardikpatel043** [angular-architects/module-federation-plugin#50]
I have cloned https://github.com/manfredsteyer/module-federation-plugin-example.

I have updated browserlistrc file to support only modern browsers. Still, I see multiple bundles.

![image](https://user-images.githubusercontent.com/13534287/120642110-187c4a00-c492-11eb-8f05-726c4a6b870f.png)

Also, I have observed that multiple bundles are required. App doesn't work if I delete duplicated.

I would like to know why it does generate duplicate bundles and what should I do to eliminate this.

**Comment by manfredsteyer** [comment]
Yes, this is currently how module federation works. Consuming a shared lib in different other shared libs might lead to this. However, it's not as bad as it looks like b/c at runtime online one version is loaded.
