### ISSUE TITLE
Render component with dependencies?

### ISSUE THREAD

**Issue by enorfelt** [angular-architects/module-federation-plugin#51]
How do I go about rendering a remote component that has dependencies to it?
Or depends on initialization in the feature module like initializing a state in Ngxs?

**Comment by manfredsteyer** [comment]
Hi,

this is currently a general issue/ limitation of Angular. While Ivy allows to lazy loading components, we need to put the component's NgModule into the **same** file as the component.

Some people call this a SCAM (Single component Angular module)
