### ISSUE TITLE
Loding more the one Mfe at the same time. 

### ISSUE THREAD

**Issue by ikonezg** [angular-architects/module-federation-plugin#53]
So I have a typical shell app for hosting mfe. Setup for dynamically loading components (like widgets).  Like in the Plugin example. The only difference is I'm not adding them on click event but from the configuration list.  The problem occurs when we ngFor the widgets. It happens so fast that the first widget is not yet rendered or loaded . That other widget one from the same Mfe brakes. is it possible to load multiple mfe at the same remoteEntry.js

**Comment by rojasjandro89** [comment]
I have exactly the same problem. The only solution I found was centralizing the dynamic loading functionality in a service and queue them.

It's not ideal, but it works better than it sounds.

**Comment by ikonezg** [comment]
I had the same idea but I wanted to check is there something else a more performant solution.
Thank you  rojasjandro89
