### ISSUE TITLE
Native Federation and dynamic manifest

### ISSUE THREAD

**Issue by ips219** [angular-architects/module-federation-plugin#551]
Hello...

I've recently migrated to Angular 17, and I have started to analyze how to migrate to the new plugin based on Native Federation.

My application currently uses Angular webpack module federation for loading dynamically different modules based on the user privileges and scopes....This means that application starts, and based on the user settings (coming from API) , the shell application may load modules based on user navigation on demand.

Checking out the new library, although the same concepts are present, i've noticed that there is federation manifest that initialize the remote modules for using them later in the application.

Is it possible to generate the manifest dynamically from an API response information with specific user settings or should be static?

Thanks and best regards.

**Comment by manfredsteyer** [comment]
Sure. Feel free to generate it dynamically via a Web API you point to using initFederation.
