### ISSUE TITLE
"[ERROR] Two output files share the same path but have different contents" when building native federation cache

### ISSUE THREAD

**Issue by ips219** [angular-architects/module-federation-plugin#558]
I'm trying to migrate from webpack to native federation...

I've managed to make it work with one of my mfe, but I've another that is failing to generate the native federation cache bundle throwing the error: [ERROR] Two output files share the same path but have different contents when building native federation cache

![image](https://github.com/angular-architects/module-federation-plugin/assets/3368591/a62b90c2-b6f3-4fcf-85da-763f5f1979a5)

The full console output:
[error.txt](https://github.com/angular-architects/module-federation-plugin/files/15287334/error.txt)

I'm not sure if the problem comes from the compatibility of fullcalendar library (I may try to get feedbackfrom them) with esbuild or with the native federation plugin itself.

I've tried to skip fullcalendar libraries in the federation.config.js
![image](https://github.com/angular-architects/module-federation-plugin/assets/3368591/d05a5248-303c-4787-a7d4-e58e775d01af)

But I get the same error, for some reason it seems that is included inthe bundle.

Any idea of how can I workround this issue?

Thanks and best regards.

**Comment by manfredsteyer** [comment]
Can you please try to skip full calender via a RegExp:

skip:[
  /^@fullcalendar\//
]

This includes everything starting with fullcalender.

I will have a closer look soon to find out why fullcalender is causing this issue.

**Comment by ips219** [comment]
After adding the skip with the regexp as you said it worked.

![image](https://github.com/angular-architects/module-federation-plugin/assets/3368591/c2352c05-5727-423a-83ab-ad7dbbf8b3d2)

Thank you for your support.

I thought it worked at library level, The regexp works in the same way in the "share" settings?

**Comment by manfredsteyer** [comment]
Glad to hear that it works now. The RegExp only works in skip.
