### ISSUE TITLE
add License for tools and runtime npm packages

### ISSUE THREAD

**Issue by codingnuclei** [angular-architects/module-federation-plugin#56]
Hi,

My Company requires all our packages to have a License on NPM otherwise our proxy quarantines them.

Is it possible to add a License for: 

@angular-architects/module-federation-runtime

and

@angular-architects/module-federation-tools

Many thanks :)

**Comment by manfredsteyer** [comment]
Yes, totally. The next version will officially have MIT license. This is how it was intended to be all the time.
