### ISSUE TITLE
Failed build after upgrade to Angular v18

### ISSUE THREAD

**Issue by moravkin** [angular-architects/module-federation-plugin#562]
Upgrading to latest cli angular v18 native federation won't work. After initializing new application using command `ng new mfe4` and initializing nf using `ng add @angular-architects/native-federation --project mfe4 --port 4203 --type remote`, I run `npm run start` and got following error: 

An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/src/builders/application'
Require stack:
- ...........\mfe4\node_modules\@angular-architects\native-federation\src\builders\build\builder.js
- ...........\mfe4\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js

**Comment by manfredsteyer** [comment]
There will be soon a version for Angular 18. @GregOnNet already worked on it!
