### ISSUE TITLE
Question - [Native federation] building seperate repositories in one bundle with @softarc/native-federation-esbuild

### ISSUE THREAD

**Issue by dessyg** [angular-architects/module-federation-plugin#568]
Hello team,

With my team working on a business product with micro frontends, implemented with Angular 17 and Native federation. Each micro fe in a separate github repo and also the shell application. My question is, if it is possible to use [@softarc/native-federation-esbuild](@softarc/native-federation-esbuild) npm package for building a bundle with esbuild for all the micro frontend apps and the shell together. Becau all the examples are with one repo and all the application with a seperate folder in it.

Thanks in advance,
Desislava Georgieva

**Comment by manfredsteyer** [comment]
Hi,

Yes, this is completely possible. 

Ideally, you can prevent version conflicts via different repos.

If this does not work, you can wrap your apps into web components like here [1].

[1] https://www.angulararchitects.io/blog/micro-frontends-with-modern-angular-part-2-multi-version-and-multi-framework-solutions-with-angular-elements-and-web-components/
