### ISSUE TITLE
Using this plugin with Angular 11 - single SPA micro frontend breaks the application

### ISSUE THREAD

**Issue by dnyaneshwr-shinde** [angular-architects/module-federation-plugin#57]
When we are tying to use this plugin to setup module federation into and Angular 11 - single SPA application, it stops working with following error. 

`single-spa minified message #37: See https://single-spa.js.org/error/?code=37&arg=application&arg=models-plan&arg={"default":{},"__useDefault":true}`

We followed below article by Manfred Steyer:
[link](https://www.angulararchitects.io/en/aktuelles/the-microfrontend-revolution-part-2-module-federation-with-angular/)

**Comment by manfredsteyer** [comment]
I'm sorry. This has not been tested with single spa.
