### ISSUE TITLE
Error on serve and build after upgrade to Angular 18 and native federation 18.0.0

### ISSUE THREAD

**Issue by papagno** [angular-architects/module-federation-plugin#570]
I have a working project with angular 17 and plugin 17.1.8. I'm trying to upgrade to angular 18 and plugin 18.0.0. When I start or build the app I get the following error:

`An unhandled exception occurred: Package subpath './src/builders/application' is not defined by "exports" in node_modules\@angular\build\package.json`

Do you have any hint on what the issue could be?

**Comment by papagno** [comment]
@ZissisT thank you, this worked!

**Comment by alekk84** [comment]
after run postinstall script ng serve-original not working
`An unhandled exception occurred: (0 , private_1.purgeStaleBuildCache) is not a function`

**Comment by lblacio-craft** [comment]
> after run postinstall script ng serve-original not working `An unhandled exception occurred: (0 , private_1.purgeStaleBuildCache) is not a function`

https://github.com/angular-architects/module-federation-plugin/issues/590
