### ISSUE TITLE
Error: Dynamic require of "tslib" is not supported

### ISSUE THREAD

**Issue by omishyn-dm** [angular-architects/module-federation-plugin#572]
After update @angular-architects/native-federation from 18.0.0 to 18.0.2
on serve i have error in console dev tools

Error: Dynamic require of "tslib" is not supported

and i found next code in artifact file

...
// node_modules/@angular-architects/native-federation/src/index.js
var require_src = __commonJS({
  "node_modules/@angular-architects/native-federation/src/index.js"(exports) {
    "use strict";

    Object.defineProperty(exports, "__esModule", {
      value: true
    });
    var tslib_1 = __require("tslib");
    tslib_1.__exportStar((init_softarc_native_federation_runtime(), __toCommonJS(softarc_native_federation_runtime_exports)), exports);
  }
});
...

I think it heppends becouse you change index.js source code from

export * from '@softarc/native-federation-runtime';

to

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
tslib_1.__exportStar(require("@softarc/native-federation-runtime"), exports);

I patched this file and it works again

Please return code in node_modules/@angular-architects/native-federation/src/index.js

**Comment by mqrten** [comment]
Same issue for me when using nested MFE-s 3 levels in and only if using @ViewContainer on the second level (if I remove ViewContainer error disappears). Furthermore, error occurs only if I access through first level, never when I access it through second level.

shell => mfe level 2 => mfe level 3.

Needed to downgrade to 18.0.0, furthermore, needed to add mfe level 3 remote to *shell* (defining it only in level 2 was not sufficient), otherwise mfe level 3 was not recognised.

**Comment by dodesheide** [comment]
Same issue for us. We created a duplicate here:
https://github.com/angular-architects/module-federation-plugin/issues/602

**Comment by dodesheide** [comment]
Try to update to 18.1.1. This version fixed for me the error. See https://github.com/angular-architects/module-federation-plugin/issues/602 .

**Comment by angelo-v** [comment]
The error came back with 18.1.3

**Comment by angelo-v** [comment]
It seems the package got published as commonjs instead of esm again. Could you take a look at this and fix it @manfredsteyer?

**Comment by ZissisT** [comment]
Any status update on this?

**Comment by rainerhahnekamp** [comment]
Sorry, guys, for these delays. We now have a Stackblitz example. It would be great if you could be able to reproduce the issue with it: https://stackblitz.com/github/rainerhahnekamp/native-federation-stackblitz?file=projects%2Fhost%2Fsrc%2Fapp%2Fapp.routes.ts

Do you think that's possible?

**Comment by ZissisT** [comment]
I am a bit lost on who is asked to do what :/ We see this error a lot in several packages and if we can help solving it it would be great.

**Comment by rainerhahnekamp** [comment]
everyone who participated here is asked :) So if you think you have the time and want to contribute, please do so.

**Comment by manfredsteyer** [comment]
There was, unfortunately, a bug in a minor version. Just update to the newest version of NatFed and delete your folder node_modules/.cache.
