### ISSUE TITLE
Native federation problem with library builds.

### ISSUE THREAD

**Issue by mino89** [angular-architects/module-federation-plugin#576]
Hi guys,
I've started an experiment with native federation library, regarding all mircrofrontend app everything is working fine, but, when I try to run  
```bash
ng build services
```
I get this error
```bash
(0 , private_1.purgeStaleBuildCache) is not a function
```
I've tried to search some info about, but nobody has a similar situation

Here you can find my [source code](https://github.com/mino89/angular-modular-app/tree/nativefederation
)

These are the versions of packages I've used in my project

```
angular-modular-prj@0.0.0
├── @angular-architects/native-federation@18.0.2
├── @angular-devkit/build-angular@18.0.3
├── @angular/animations@18.0.2
├── @angular/cli@18.0.3
├── @angular/common@18.0.2
├── @angular/compiler-cli@18.0.2
├── @angular/compiler@18.0.2
├── @angular/core@18.0.2
├── @angular/forms@18.0.2
├── @angular/platform-browser-dynamic@18.0.2
├── @angular/platform-browser@18.0.2
├── @angular/router@18.0.2
├── @types/jasmine@5.1.4
├── es-module-shims@1.10.0
├── jasmine-core@5.1.2
├── karma-chrome-launcher@3.2.0
├── karma-coverage@2.2.1
├── karma-jasmine-html-reporter@2.1.0
├── karma-jasmine@5.1.0
├── karma@6.4.3
├── ng-packagr@18.0.0
├── rxjs@7.8.1
├── tslib@2.6.3
├── typescript@5.4.5
└── zone.js@0.14.7
```

**Comment by LilianSOLER** [comment]
+1

**Comment by lblacio-craft** [comment]
+1

**Comment by lblacio-craft** [comment]
Anyone found a solution about this ?  I have the same issue since, I also updated Angular version and native federation too

**Comment by tibztibz** [comment]
+1

**Comment by lblacio-craft** [comment]
I resolved my problem. check hier : https://github.com/angular-architects/module-federation-plugin/issues/590

**Comment by lblacio-craft** [comment]
> i have already @angular/cli in my dependencies for me.

FYI: Me too but I runned this command.

**Comment by tibztibz** [comment]
in my case, i use pnpm, so il do 'pnpm add -Dwf  @angular/cli' to force to download @anglar/cli and t's work after.
But it's because the postinstall isn't launched. When i do a pnpm i, the postintsall is launched and i have again the private_1.purgeStaleBuildCache error.

**Comment by Keyurkch** [comment]
+1 facing same issue. I am creating native federation with angular 18. ng build my-lib gives same  private_1.purgeStaleBuildCache error.

**Comment by lblacio-craft** [comment]
@manfredsteyer please could we have an answer.  thank you

**Comment by ofthelit** [comment]
Building a library works for me when I change the content in `node_modules\@angular\build\private.js` to:
`module.exports = require('./src/private.js');`

The file is written by [patch-angular-build.ts](https://github.com/angular-architects/module-federation-plugin/blob/2fe3dc8e7fcc15893d4ab21fb59bab956654d81c/libs/native-federation/src/utils/patch-angular-build.ts#L5C1-L5C39).
