### ISSUE TITLE
nf - build/options externalDependencies, allowedCommonJsDependencies not working

### ISSUE THREAD

**Issue by MarcelBariakGrenzebach** [angular-architects/module-federation-plugin#584]
Package versions:
`"@microsoft/signalr": "^8.0.0",
 "@angular-architects/native-federation": "^18.0.2",
`
There is a known problem with the `@microsoft/signalr": "^8.0.0"` angular 18/ esbuild - https://github.com/dotnet/aspnetcore/issues/52082#top

When I am using the @microsoft/signalr in the angular 18 projects without native federation and applying externalDependencies, allowedCommonJsDependencies depends on https://github.com/dotnet/aspnetcore/issues/52082#issuecomment-2094135503 all is working fine.
` "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "externalDependencies": [
              "http",
              "https",
              "url",
              "util",
              "net"
            ],
            "allowedCommonJsDependencies": [
              "tough-cookie",
              "node-fetch",
              "fetch-cookie",
              "abort-controller",
              "ws",
              "eventsource"
            ],`

In the case of the native federation, I applied build options:
`"architect": {
        "build": {
          "builder": "@angular-architects/native-federation:build",
          "options": {
            "externalDependencies": [
              "http",
              "https",
              "url",
              "util",
              "net"
            ],
            "allowedCommonJsDependencies": [
              "tough-cookie",
              "node-fetch",
              "fetch-cookie",
              "abort-controller",
              "ws",
              "eventsource"
            ]
          },`
and also for:
`"esbuild": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "externalDependencies": [
              "http",
              "https",
              "url",
              "util",
              "net"
            ],
            "allowedCommonJsDependencies": [
              "tough-cookie",
              "node-fetch",
              "fetch-cookie",
              "abort-controller",
              "ws",
              "eventsource"
            ],`
![image](https://github.com/angular-architects/module-federation-plugin/assets/41298565/0abfc351-7a41-4951-bfb7-a68d40c2099c)
![image](https://github.com/angular-architects/module-federation-plugin/assets/41298565/6b2fa4eb-5572-4707-914d-27bdee90df13)

**Comment by manfredsteyer** [comment]
This is, because https, http, util etc. are node packages not available in the browser. You need to add this lib are respective entry points to the skip list.

**Comment by MarcelBariakGrenzebach** [comment]
Hi @manfredsteyer, thanks for your response.

I tried it with share = but the build not working 
![image](https://github.com/angular-architects/module-federation-plugin/assets/41298565/30aca6e2-78ce-4c04-af48-542cd7202cdd)
![image](https://github.com/angular-architects/module-federation-plugin/assets/41298565/60a64e28-ea40-4951-940a-2957631e3048)


I tried it with shareAll + skip = but the build not working 
![image](https://github.com/angular-architects/module-federation-plugin/assets/41298565/ef6bd263-5f04-46f3-8fbd-139eb636e86b)
![image](https://github.com/angular-architects/module-federation-plugin/assets/41298565/1677b2a9-2c6a-4189-ad86-51d61bc31781)

I tried also to install @microsoft/signalr and eventsource to devDependencies - this also did not help.

Ng serve working only when I added @microsoft/signalr  to skip area.
