### ISSUE TITLE
Library not being shared between the projects

### ISSUE THREAD

**Issue by Aeseir** [angular-architects/module-federation-plugin#59]
I followed the tutorial listed here [https://github.com/angular-architects/module-federation-plugin/blob/main/libs/mf/tutorial/tutorial.md](url) and it works a treat.

However when it came to having a shared auth-lib running it doesn't shared it.

here is the tsconfig.json code

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "paths": {
      "auth-lib": [
        "projects/auth-lib/src/public-api.ts"
      ]
    },
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```
here is the webpack from MFE1

```
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");
const path = require("path");

const sharedMappings = new mf.SharedMappings();
sharedMappings.register(
  path.join(__dirname, '../../tsconfig.json'),
  ['auth-lib']);

module.exports = {
  output: {
    uniqueName: "mfe1",
    publicPath: "auto"
  },
  optimization: {
    runtimeChunk: false
  },   
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    }
  },
  plugins: [
    new ModuleFederationPlugin({
      
        // For remotes (please adjust)
        name: "mfe1",
        filename: "remoteEntry.js",
        exposes: {
          './Module': './projects/mfe1/src/app/flights/flights.module.ts',
        },        
        
        // For hosts (please adjust)
        remotes: {
            "shell": "shell@http://localhost:5000/remoteEntry.js",
        },

        shared: {
          "@angular/core": { singleton: true, strictVersion: true }, 
          "@angular/common": { singleton: true, strictVersion: true }, 
          "@angular/common/http": { singleton: true, strictVersion: true }, 
          "@angular/router": { singleton: true, strictVersion: true },

          ...sharedMappings.getDescriptors()
        }
        
    }),
    sharedMappings.getPlugin()
  ],
};

```

here is the webpack from Shell

```
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");
const path = require("path");

const sharedMappings = new mf.SharedMappings();
sharedMappings.register(
  path.join(__dirname, '../../tsconfig.json'),
  ['auth-lib']);

module.exports = {
  output: {
    uniqueName: "shell",
    publicPath: "auto"
  },
  optimization: {
    runtimeChunk: false
  },   
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    }
  },
  plugins: [
    new ModuleFederationPlugin({
      
        // For remotes (please adjust)
        // name: "shell",
        // filename: "remoteEntry.js",
        // exposes: {
        //     './Component': './projects/shell/src/app/app.component.ts',
        // },        
        
        // For hosts (please adjust)
        remotes: {
            "mfe1": "mfe1@http://localhost:3000/remoteEntry.js",

        },

        shared: {
          "@angular/core": { singleton: true, strictVersion: true }, 
          "@angular/common": { singleton: true, strictVersion: true }, 
          "@angular/common/http": { singleton: true, strictVersion: true }, 
          "@angular/router": { singleton: true, strictVersion: true },

          ...sharedMappings.getDescriptors()
        }
        
    }),
    sharedMappings.getPlugin()
  ],
};

```

I've tried to see similar examples and play around but nothing seems to work.

Any advise is appreciated (note i strictly followed the tutorial so no updates were done to anything).

**Comment by Aeseir** [comment]
If it further helps any investigations, I've noticed also while the module of MFE1 is loaded, the corresponding assets aren't.

As a simple test i changed the name of angular.png in the MFE1 asset to be angular-mfe1.png and update the corresponding home and flight-search html components to reflect the name.

When MFE1 launches everything is as it should be, however when opening it via Shell (localhost:5000) the contents load however  it searches for asset-mfe1.png within localhost:5000 and not localhost:3000, and shows a broken image as it cannot find it.

My assumption is in real world majority of scenarios you would host the images and therefore it would pull it via secured url, however in the minority where there is a dependency to store it in asset folder this is a problem.

**Comment by pedrincandido** [comment]
Hello everyone!!, i found solution..
this in shell.. (main application)

![image](https://user-images.githubusercontent.com/32328995/128704847-f8f02ccb-7c98-432c-a585-a55854de3d5d.png)

after adding ```auth-lib``` in shared mappings and adding '@ngxs/store' in shared dependencies on webpack and auth-lib.

<img width="1440" alt="Captura de Tela 2021-08-09 às 09 16 40" src="https://user-images.githubusercontent.com/32328995/128705099-ad47501a-5d97-4f72-957c-2ac0a2ae81a8.png">

now in MFE(name 'auth')

<img width="1440" alt="Captura de Tela 2021-08-09 às 09 19 42" src="https://user-images.githubusercontent.com/32328995/128705278-57b9e52d-89fd-48b3-89df-59c54284ab70.png">

adding ```auth-lib```in shared mappings and adding ngxs/store, but I don't think it's necessary to add eagerly, singleton is necessary

<img width="1440" alt="Captura de Tela 2021-08-09 às 09 21 56" src="https://user-images.githubusercontent.com/32328995/128905896-2c5f80b2-a1fe-401c-99a8-5dc254d7b79b.png">

remembering that the module you are going to export, it will become part of the other application, with that in mind, after everything is ready, next pass in your "Modules exposed in webpack" added ```NgxsModule.forFeature([YourState])```, 

<img width="1440" alt="Captura de Tela 2021-08-10 às 14 42 46" src="https://user-images.githubusercontent.com/32328995/128908686-7209204d-31b8-4441-aad1-6911a7bdd829.png">

in your on shell application module, adding ```NgxsModule.forRoot()```, not necessary adding ```NgsModule.forRoot(Statename)``` 

![Captura de Tela 2021-08-10 às 18 04 02 (2)](https://user-images.githubusercontent.com/32328995/128934827-14449bf2-c328-4ce6-8daa-f7354d3e06f8.png)

I have an example working here [here](https://github.com/pedrincandido/module-federation-plugin-example)

**Comment by Jeff-sitekit** [comment]
I'm experiencing the same - apparently unable to share a singleton library between front-ends. Each front-end gets their own instance. Is there any update on this?

**Comment by Jeff-sitekit** [comment]
Resolving my own issue here:
The shared service (singleton) was not being correctly shared between the remote components because my RemoteEntryModule was importing the Angular BrowserModule.
I'm not sure whether this came from an example or was generated by one of the schematics. Whatever, removing that from the Angular imports resolved the issue with the shared library service.
I hope this will be helpful for others experiencing something similar.

**Comment by mikezks** [comment]
@Jeff-sitekit, thanks for your answer - this may help others in future.

In a single-version MF setup, the BrowserModule needs to be imported only once, like in a normal Angular app (Build Monolith; default setup). Therefore please expose Feature Modules as Remotes and not Root Modules.

**Comment by mguay22** [comment]
> @Jeff-sitekit, thanks for your answer - this may help others in future.
> 
> In a single-version MF setup, the BrowserModule needs to be imported only once, like in a normal Angular app (Build Monolith; default setup). Therefore please expose Feature Modules as Remotes and not Root Modules.

Thank you. This wasn't immediately clear to me as a newcomer to this process/library.
