### ISSUE TITLE
MF + Angular + web components production ready?

### ISSUE THREAD

**Issue by out-dev** [angular-architects/module-federation-plugin#591]
I would like to use the microfrontend approach with angular + module federation + web component.
Can I classify this repository and the associated tools from yours as prduction ready?

By the way: Many thanks for the helpful examples and tutorials :-)

**Comment by muenchto** [comment]
This is a very good question.  Support on issues seems to be low/non-existent in the last months, but compatibilty with Angular 18 has been ensured. 

I would also be very happy to hear about the roadmap of this project, expecially Native Federation (I dont think many people want to stick with Webpack for long in the Angular world).

**Comment by manfredsteyer** [comment]
Yes, this is something quite a lot of companies are doing. The road is rocky, but that's the nature of the beast.
