### ISSUE TITLE
Library doesn't compile after update to angular v18

### ISSUE THREAD

**Issue by lblacio-craft** [angular-architects/module-federation-plugin#594]
I Updated my project to the latest version of angular and native federation.
Since this, My library project doesn't compile. I noticed another person has the same https://github.com/angular-architects/module-federation-plugin/issues/576.
The other application projects are working well.

Could you check this please ?

**Comment by sheshnathverma** [comment]
Can someone please suggest a workaround? I'm stuck

**Comment by muenchto** [comment]
Did you follow the guide to update to angular 18? It includes a little special/hacky part, maybe u missed this? 
https://github.com/angular-architects/module-federation-plugin/blob/main/libs/native-federation/docs/update18.md

**Comment by lblacio-craft** [comment]
> Did you follow the guide to update to angular 18? It includes a little special/hacky part, maybe u missed this? https://github.com/angular-architects/module-federation-plugin/blob/main/libs/native-federation/docs/update18.md

I did both options.

**Comment by manfredsteyer** [comment]
Let's retry this with NF 18.1 which will land very soon.
