### ISSUE TITLE
Build is stuck in case of error

### ISSUE THREAD

**Issue by ivaspavlo** [angular-architects/module-federation-plugin#596]
Hello,

There is an issue with NF plugin: in case of an error during the build ("ng build") - it doesn't exit.

Steps to reproduce:
1. git clone https://github.com/ivaspavlo/nf-build-issue-demo.git
2. npm i
3. npm run build

Alternatively, if usual builder is used ("npm run usual-build") it exists on error.

Thank you for any hint!

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. This will be resolved in version 18.1 which will land very soon.

**Comment by deven810** [comment]
Hey, this error exists in version 17.1.8 and upgrading to Angular 18 isn't an option right now. Do you think we could release these changes/guide us on how we can fix this issue for ourselves potentially in the 17.1.x version?
