### ISSUE TITLE
[Native federation] Images are not loaded in shell application

### ISSUE THREAD

**Issue by eyevan** [angular-architects/module-federation-plugin#598]
Hi all,

We have this shell and MFE setup working but just now realised that the images are not working the shell application. We're kinda stuck and besides copying the images to the shell, nothing seems to work.

How is this handled in esbuild with native federation?

**Comment by manfredsteyer** [comment]
Yes, you are right. This is not the job of federation. There are several solutions:
a) The shell could tell each mfe it's absolute URL
b) you could use a reverse proxy
