### ISSUE TITLE
Can HttpInterceptor's shell intercept http request of plugin httpclient call?

### ISSUE THREAD

**Issue by dtrouillet** [angular-architects/module-federation-plugin#6]
Hello,

I use your awesome lib to integrate plugin in my Angular application.
But I need to use httpinterceptor for all of my api call, even if call is made by plugin (remote) (for oauth2-oidc).

Is it possible to make this just on shell (host)?

Regards
Damien Trouillet

**Comment by manfredsteyer** [comment]
If you share @angular/core/http it should be possible. In this case, you only have one instance of the HTTP_INTERCEPTORS token.
