### ISSUE TITLE
Share libraries between different monorepos

### ISSUE THREAD

**Issue by echonok** [angular-architects/module-federation-plugin#60]
Hello!
I'm trying to find out whether it is possible to share a library from one repo to another using Module Federation.
I see it is really easy for one complex monorepo but what if we want to split it into different repos?
Sorry, if this question is dumb but I can't wrap my head around this.

**Comment by manfredsteyer** [comment]
Yes, totally. Just install it as an npm package and register it in the webpack config as shared lib.

The generated webpack config does the same for @angular/core etc.
