### ISSUE TITLE
Feature Request: merge multiple bundles/ chunks into one to reduce the number of http-calls

### ISSUE THREAD

**Issue by dipu7388** [angular-architects/module-federation-plugin#601]
#### Description
Currently, when exporting constants or shared modules in our project, each export generates a separate chunk during the build process. For example, a file like `global.constants.ts` with exports such as:
```typescript
export const A = 0;
export const B = 1;
export const C = 2;
results in three separate chunks being generated.

Requested Feature
We would like to request a feature that allows us to merge these separate chunks into a single chunk during the build process. This capability would help in reducing the number of HTTP requests and improving loading times by bundling related exports into a single chunk.

Use Case
Example: Currently, rxjs and @angular/material exports are generating multiple chunks for each export. We would like these to be merged into a single chunk respectively.

### Steps to Reproduce
1. Clone the repository with the specific branch:
   ```bash
   git clone -b native-federation https://github.com/dipu7388/multiple-entry.git
   cd multiple-entry

**Comment by dipu7388** [comment]
@manfredsteyer  can we have an option to merge two of more files into one. please look into it.

**Comment by manfredsteyer** [comment]
Hi,

I think it's not a bundle per export but a bundle per entry point. And Angular Material has a lot of entry points. As each entry point ends up in an ESM-bundle the result are several bundles. I currently don't see any way to prevent this when sticking with the ESM standard which is one of the goals of Native Federation.

However, if someone has an idea of how to accomplish that, I'm happy to discuss possible implementations.
