### ISSUE TITLE
ng test error with angular 18 + native federation 18

### ISSUE THREAD

**Issue by walter-psjr** [angular-architects/module-federation-plugin#606]
Hi,

I updated an angular 17 project with native federation to angular 18.1.1 and native federation 18.0.2 and my ng test stopped to work. When I run ng test i get this error:

![image](https://github.com/user-attachments/assets/6bbac71e-0df7-488a-95f4-92fda0bd4c0e)

To check if it is a problem with my project i created a new one, executed ng test i it was working, and after install native federation in it it started to return the same error.

Anyone else with the same problem?

**Comment by rosalesponcer** [comment]
I have the same error as you; I haven't been able to solve it yet

**Comment by dodesheide** [comment]
I think this nearly the same error:

https://github.com/angular-architects/module-federation-plugin/issues/603

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. This is resolved with version 18.1, which will land very soon.
