### ISSUE TITLE
Angular 10 - Cannot find module 'webpack/lib/container/ModuleFederationPlugin'

### ISSUE THREAD

**Issue by NimitTRT** [angular-architects/module-federation-plugin#61]
Hi, I am using Angular 10 as my Host and a new Angular 12 as a shell. The shell is working perfectly but in the host, I am receiving the error `Cannot find module 'webpack/lib/container/ModuleFederationPlugin'`
I referred to the issue [Issue20](https://github.com/angular-architects/module-federation-plugin/issues/20) and tried the solution
` "resolutions": {
    "webpack": "5.27.2"
  }`
But it still gave me the same error.
I tried adding webpack as a dependency in package.json
`"webpack": "~5.40.0",`
But it seems to have some package version issue
![image](https://user-images.githubusercontent.com/77389787/124125453-3dff7200-da97-11eb-857c-4641cb82576c.png)

My Angular Versions are
![image](https://user-images.githubusercontent.com/77389787/124125579-69825c80-da97-11eb-9ba9-c6a7a85b3713.png)

Is there a way to use module-federation without upgrading my Angular to 12?
And will upgrading it to 12 solve the issue?

**Comment by manfredsteyer** [comment]
I'm afraid, this won't work. It only woked in Angular 11 b/c of some amazing community contributions. And with v 12, we have official webpack 5 support.
