### ISSUE TITLE
unclean shareAll output with some packages (out of memory/import errors)

### ISSUE THREAD

**Issue by Ketec** [angular-architects/module-federation-plugin#612]
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
I also see errors for files that aren't even modules - like changelog.md from some node_module package.

```
./node_modules/vanilla-jsoneditor/CHANGELOG.md:1:1 - Error: Module parse failed: Unexpected character ' ' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

Likely because the config output from shareAll contains:
    'vanilla-jsoneditor/CHANGELOG.md': {
      singleton: true,
      strictVersion: true,
      requiredVersion: '^0.23.8',
      eager: true,
      pinned: true,
      version: '0.23.8'
    },

etc  - css, map, md, d.ts etc are included  depending on package types.
Perhaps shareAll might needs some filter to exclude non-important files from it's exports. It's likely ES6 package.

**Comment by manfredsteyer** [comment]
you can use the skip array to exclude such packages.
