### ISSUE TITLE
purgeStaleBuildCache after update to native-federation 18

### ISSUE THREAD

**Issue by DvDruzhkov** [angular-architects/module-federation-plugin#615]
Hello.

I have a project with nx, Angular 17.3.6 and @angular-architects/native-federation 17.1.7

After upgrading to Angular 18.1.3 and @angular-architects/native-federation 18.0.2 and applying the patch in postinstall "node node_modules/@angular-architects/native-federation/src/patch-angular-build.js", the serve-original "@angular-devkit/build-angular:dev-server" project does not build, I get the error:
(0 , private_1.purgeStaleBuildCache) is not a function
TypeError: (0 , private_1.purgeStaleBuildCache) is not a function
    at initialize (C:\myProject\node_modules\@angular-devkit\build-angular\src\builders\dev-server\builder.js:98:46)
    at C:\myProject\node_modules\@angular-devkit\build-angular\src\builders\dev-server\builder.js:60:36
    at Observable._subscribe (C:\myProject\node_modules\rxjs\dist\cjs\internal\observable\defer.js:8:31)
    at Observable._trySubscribe (C:\myProject\node_modules\rxjs\dist\cjs\internal\Observable.js:41:25)
    at C:\myProject\node_modules\rxjs\dist\cjs\internal\Observable.js:35:31
    at Object.errorContext (C:\myProject\node_modules\rxjs\dist\cjs\internal\util\errorContext.js:22:9)
    at Observable.subscribe (C:\myProject\node_modules\rxjs\dist\cjs\internal\Observable.js:26:24)
    at C:\myProject\node_modules\rxjs\dist\cjs\internal\operators\switchMap.js:13:16
    at OperatorSubscriber.<anonymous> (C:\myProject\node_modules\rxjs\dist\cjs\internal\util\lift.js:14:28)
    at C:\myProject\node_modules\rxjs\dist\cjs\internal\Observable.js:30:30

Before applying the patch, the build serve-original works, but @angular-architects/native-federation:build not work

**Comment by DvDruzhkov** [comment]
same problem https://github.com/angular-architects/module-federation-plugin/issues/576

**Comment by manfredsteyer** [comment]
I'm going to publish a version 18.1 for Angular 18.1.x very soon. Can you please retry using this version once it's available?

**Comment by DvDruzhkov** [comment]
Of course, I will follow the updates and update immediately.

@manfredsteyer, thank you for your product, with its help we made an excellent integration of different solutions on Angular and React into one site

**Comment by DvDruzhkov** [comment]
@manfredsteyer , hi, after upgrading to @angular-architects/native-federation version 18.1.1, my build worked @angular-architects/native-federation:build and @angular-devkit/build-angular:dev-server.

Now my stack is @angular/core version 18.1.3 and @angular-architects/native-federation version 18.1.1.

Thank you very much for your work!
