### ISSUE TITLE
private_1.getSupportedBrowsers is not a function

### ISSUE THREAD

**Issue by LoaderB0T** [angular-architects/module-federation-plugin#616]
Hi there, I just tried out the new 18.1 version for ng 18.1.

I have the same problem that @ofthelit had here: https://github.com/angular-architects/module-federation-plugin/issues/576#issuecomment-2273419765
where the import of the angular private package fails.

The problem seems to be that the generated private.js has `exports = require('./src/private.js');` instead of `modules.exports = require('./src/private.js');`

When I add `modules.` to the file, everything builds just fine.

Node Version v22.4.1
Angular Version 18.1.4
angular-architects/native-federation Version 18.1.1

![image](https://github.com/user-attachments/assets/5f037909-fe7d-4f0b-aff6-145babd0af98)

**Comment by nbonneau** [comment]
+1

**Comment by manfredsteyer** [comment]
Hi,

There is no generated private.ts anymore in NF 18.1. Meanwhile, we got a solution that allows us to go without this workaround. Can you pls try the following:

- delete your node_modules folder
- Remove the postbuild task in your package.json
- npm i

**Comment by LoaderB0T** [comment]
Thanks, the postbuild task was indeed still in my package json!
Removing it fixed the issue!
