### ISSUE TITLE
@Angular/ssr not working in remotes [Module federation]

### ISSUE THREAD

**Issue by S-FurmanBSF** [angular-architects/module-federation-plugin#618]
Hi! Is there any example where module federation with @angular/ssr in remotes is working? I found branch in examples: ssr-islands but over there SSR is working only in shell application

**Comment by manfredsteyer** [comment]
Yes, that's right. SSR is currently not supported. The solution provided by Nx can do SSR.

**Comment by S-FurmanBSF** [comment]
Thanks for the response @manfredsteyer! I have a project where I need to stay up-to-date with the current versions of Angular. Do you think I should use Module Federation with SSR from Nx, or should I configure Webpack Module Federation on my own?
