### ISSUE TITLE
Load Dynamic Component

### ISSUE THREAD

**Issue by logitimate** [angular-architects/module-federation-plugin#62]
Is there anyway currently to load a component exposed in the webpack.config? Just thinking about more horizontal approaches this could be extremely handy. I would love to be able to load a component without having to add routing etc. Not sure how possible this is with the angular ecosystem.

EDIT: I found an example where you were using the loadRemoteModule for a component and that seems to work. I am getting injector errors for any service I have in the component that is being dynamically loaded that way. Curious if that is something seen before.
```

            loadRemoteModule({
              remoteName: editors[0].remoteName,
              exposedModule: './TextEditorComponent',
            }).then((m) => {
              const Comp = m['TextEditorComponent'];
              if (!this.viewContainer) {
                return;
              }

              const factory = this.cfr.resolveComponentFactory(Comp);
              this.compRef = this.viewContainer.createComponent(
                factory,
                undefined,
                this.injector
              );
            });
```

EDIT: I ended up being able to get the injector working by using the reference from the factory.create. Thoughts on this??

```
 loadRemoteModule({
          remoteEntry: editors[0].remoteEntry,
          remoteName: editors[0].remoteName,
          exposedModule: editors[0].exposedModule,
        }).then((m) => {
          const factory = this.compiler.compileModuleSync(m.TextEditorModule);
          const reference = factory.create(this.injector);
          const Comp = m.TextEditorModule.components.TextEditorComponent;
          if (!this.editor) {
            return;
          }

          const componentFactory = this.cfr.resolveComponentFactory(Comp);
          this.compRef = this.editor.createComponent(
            componentFactory,
            undefined,
            reference.injector
          );
        });

```

**Comment by manfredsteyer** [comment]
Yes, this is possible. Please find an example here:
https://www.angulararchitects.io/aktuelles/dynamic-module-federation-with-angular-2/

Btw: You can also use *ngComponentOutlet
