### ISSUE TITLE
NG0203, NG0200 : Errors on upgrading to NG18 and native-federation 18.1.2

### ISSUE THREAD

**Issue by ratsey** [angular-architects/module-federation-plugin#621]
Today I upgraded to NG18 (specifically 18.2.0) and native-federation 18.1.2.  All was working prior to the upgrade.

Now on loading my shell application I get an error:

```
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.dev/errors/NG0203
    at injectInjectorOnly (_angular_core.MLRUh0DjMK-dev.js:658:11)
    at ɵɵinject (_angular_core.MLRUh0DjMK-dev.js:668:59)
    at Object.factory (_angular_core.MLRUh0DjMK-dev.js:16071:45)
    at core.mjs:3132:35
    at runInInjectorProfilerContext (core.mjs:866:5)
    at R3Injector.hydrate (core.mjs:3131:11)
    at R3Injector.get (core.mjs:3005:23)
    at definition.getStandaloneInjector (_angular_core.MLRUh0DjMK-dev.js:16078:27)
    at ComponentFactory.create (core.mjs:16496:53)
    at ViewContainerRef2.createComponent (core.mjs:16960:43)
```

I'm not directly injecting anything out of context in my code.

Also, when accessing a remote application, I get a circular dependency error:

```
Error: NG0200: Circular dependency in DI detected for _StandaloneService. Find more at https://angular.dev/errors/NG0200
    at throwCyclicDependencyError (core.mjs:964:9)
    at R3Injector.hydrate (core.mjs:3127:9)
    at R3Injector.get (core.mjs:3005:23)
    at definition.getStandaloneInjector (_angular_core.MLRUh0DjMK-dev.js:16078:27)
    at ComponentFactory.create (core.mjs:16496:53)
    at ViewContainerRef2.createComponent (core.mjs:16960:43)
    at _RouterOutlet.activateWith (router.mjs:2635:31)
    at _RouterOutlet.initializeOutletWithName (router.mjs:2569:14)
    at _RouterOutlet.ngOnInit (router.mjs:2553:10)
    at callHookInternal (core.mjs:5004:10)
```

My federation configs are all very vanilla:

```
...
  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
  },
...
```
I'm running a mono repo so shell and remote apps are all within the same project and compiled with NG 18.

Edit: add package.json versions:
```
  "dependencies": {
    "@angular/animations": "^18.2.0",
    "@angular/cdk": "^18.2.0",
    "@angular/common": "^18.2.0",
    "@angular/compiler": "^18.2.0",
    "@angular/core": "^18.2.0",
    "@angular/forms": "^18.2.0",
    "@angular/platform-browser": "^18.2.0",
    "@angular/platform-browser-dynamic": "^18.2.0",
    "@angular/platform-server": "^18.2.0",
    "@angular/router": "^18.2.0",
    "@angular/ssr": "^18.2.0",
    "@fortawesome/fontawesome-free": "^6.6.0",
    "chart.js": "^4.4.3",
    "es-module-shims": "^1.5.12",
    "express": "^4.18.2",
    "font-awesome": "^4.7.0",
    "ngx-cookie-service": "^18.0.0",
    "primeicons": "^7.0.0",
    "primeng": "^17.18.9",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "xml-to-json-util": "^1.0.1",
    "zone.js": "~0.14.10"
  },
  "devDependencies": {
    "@angular-architects/native-federation": "^18.1.2",
    "@angular-devkit/build-angular": "^18.2.0",
    "@angular-eslint/builder": "18.3.0",
    "@angular-eslint/eslint-plugin": "18.3.0",
    "@angular-eslint/eslint-plugin-template": "18.3.0",
    "@angular-eslint/schematics": "18.3.0",
    "@angular-eslint/template-parser": "18.3.0",
    "@angular/cli": "^18.2.0",
    "@angular/compiler-cli": "^18.2.0",
    "@softarc/eslint-plugin-sheriff": "^0.16.1",
    "@softarc/sheriff-core": "^0.16.1",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.12",
    "@types/node": "^22.3.0",
    "@types/webpack-env": "^1.18.5",
    "@typescript-eslint/eslint-plugin": "^8.0.0",
    "@typescript-eslint/parser": "^8.0.0",
    "angular-eslint": "18.3.0",
    "eslint": "^9.8.0",
    "jest": "^29.7.0",
    "jest-preset-angular": "^14.2.2",
    "ng-mocks": "^14.13.0",
    "ng-packagr": "^18.2.0",
    "primeflex": "^3.3.1",
    "ts-jest": "^29.2.4",
    "typescript": "^5.5.4",
    "typescript-eslint": "^8.1.0"
  }
```

**Comment by ErikBuhre** [comment]
I have run into the same Problem, and at first thought it might be due to a mismatch in versions between the frontend and the shell. But that wasn't the case.

The problem only occurs once I bump Angular to version `18.2.0`.

**Comment by klerick** [comment]
@manfredsteyer

I have the same problem 
if I use angular@18.2.0 and last version of native federation a have severa angular core in my application
![image](https://github.com/user-attachments/assets/c885dd02-e1ff-4132-bb12-2a19ce6872ac)
but in version angular@18.2.0 and native-federation@18.0.2
<img width="643" alt="image" src="https://github.com/user-attachments/assets/8ae24202-ae61-4598-a516-9d7013123fa5">

**Comment by uttamvs-rp** [comment]
I'm in the same boat. Has anyone figured out a solution to this?

**Comment by uttamvs-rp** [comment]
I'm using Angular to version `18.1.0`

**Comment by rlarac** [comment]
Just to add that using Nx `19.6.0` (Angular `~18.2.0`) the error `NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with 'runInInjectionContext'` the error appears when I serve the host application.

Using Nx `19.5.7` (Angular `~18.1.0`) the host works! (at least with the basic configuration).

**Comment by kruczjak** [comment]
Hi, I can confirm that fix described in https://github.com/angular-architects/module-federation-plugin/issues/621#issuecomment-2293351616 works.

Running:
`sed -i 's/{ write: false },//' node_modules/@angular-architects/native-federation/src/builders/build/builder.js` on Linux
and
`sed -i '' 's/{ write: false },//' node_modules/@angular-architects/native-federation/src/builders/build/builder.js` on MacOS

Fixes the problem (at least temporarily).

**Comment by kudarias** [comment]
same issue here and temporary solution works from @klerick, please fix as soon as possible, if it is possible. thx.

**Comment by danimaiochi** [comment]
After spending so much time trying to figure out what I've done wrong with my new angular 18 app, I've cloned the `nf-standalone-solution` and upgraded from 17 (working) to 18, which resulted in the problem again.

Shame that the `libs/native-federation/docs/update18.md` is just a lie

**Comment by elvysmarcos** [comment]
I temporarily solved the problem with Krupczak's recommendation, in this case I updated everything to the latest version, but before that, I deleted the node_modules folder, installed it again and then ran the command

**Comment by kudarias** [comment]
> After spending so much time trying to figure out what I've done wrong with my new angular 18 app, I've cloned the `nf-standalone-solution` and upgraded from 17 (working) to 18, which resulted in the problem again.
> 
> I've then changed the version to 18.1 and 18.0 but always the same problem. Can anyone help me? I seem to be the only one having this problem on any version of 18.
> 
> Thanks!

we have to wait on @manfredsteyer solution man

**Comment by danimaiochi** [comment]
> Hi, I can confirm that fix described in [#621 (comment)](https://github.com/angular-architects/module-federation-plugin/issues/621#issuecomment-2293351616) works.
> 
> Running:
> 
> on Linux: `sed -i 's/{ write: false },//' node_modules/@angular-architects/native-federation/src/builders/build/builder.js`
> 
> on MacOS: `sed -i '' 's/{ write: false },//' node_modules/@angular-architects/native-federation/src/builders/build/builder.js`
> 
> Fixes the problem (at least temporarily).

If you want to do this on Windows, you can use the Git Bash cmd and run the linux command

**Comment by alaindeurveilher** [comment]
Yep, that worked for me too. It was due to that breaking change in Angular 18.2.0. So as suggested by others:, I patched the builder.js file:

```json

  "scripts": {
    "ng": "ng",
    "workaround:patch:nf": "sed -i 's/{ write: false },//' node_modules/@angular-architects/native-federation/src/builders/build/builder.js",
    "start": "yarn workaround:patch:nf && ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
```

**Comment by tonybrasunas-greenlots** [comment]
> here

Thanks @alaindeurveilher 
Slightly different On Mac:

`"workaround": sed -i '' 's/{ write: false },//' node_modules/@angular-architects/native-federation/src/builders/build/builder.js",

**Comment by markusahrweileramcon** [comment]
In case you want to replace it, using javascript:

```javascript
import { readFileSync, writeFileSync } from 'node:fs';

const path = './node_modules/@angular-architects/native-federation/src/builders/build/builder.js';

const data = readFileSync(path).toString();

writeFileSync(path, data.replace(/\{ write: false }, /, ''));
```

**Comment by ToraTengu** [comment]
We have the same issue but decided to go the other way. 

We are keeping the versions of angular and native-fedetarion both at **~18.0.x**. It was what we used, at the time, for the prototype so we know that it works.

IMHO, patching the package in the node_modules is not worth the work/risk... To many situations were you can end up having to re-patch the file: new version still with the bug or a full re-install of the node_modules packages...

**Comment by kudarias** [comment]
> We have the same issue but decided to go the other way.
> 
> We are keeping the versions of angular and native-fedetarion both at **~18.0.x**. It was what we used, at the time, for the prototype so we know that it works.
> 
> IMHO, patching the package in the node_modules is not worth the work/risk... To many situations were you can end up having to re-patch the file: new version still with the bug or a full re-install of the node_modules packages...

native federation 18.0.* angular 18.1.* works

**Comment by kudarias** [comment]
so after days of investigation i found out, that the problem is just **@angular/build** library -> 18.2.* is problematic, so this library has to be version 18.1.*, others could be 18.*.
side effects: if you using @angular/fire@18 (analytics), it will stop work, because it works with just @angular/build@18.2.*

**Comment by ToraTengu** [comment]
> so after days of investigation i found out, that the problem is just **@angular/build** library -> 18.2.* is problematic, so this library has to be version 18.1.* , others could be 18.* . side effects: if you using @angular/fire@18 (analytics), it will stop work, because it works with just @angular/build@18.2.* and without upper workaround

Sounds great! Ill have a colleague update the prototype with these versions and test it out...

**Comment by manfredsteyer** [comment]
Hi,

thanks for pointing this out.

I was able to reproduce this issue.

I'm wondering why removing { write: false } helps. I currently don't see the connection.

**Comment by manfredsteyer** [comment]
Ah, I got it: The signature of buildApplicationInternal changed. This parameter does not exist anymore.

Big thanks for pointing this out. I'll make a new version ready.

**Comment by manfredsteyer** [comment]
Just published a new Version: 18.2.1

**Comment by gigadie** [comment]
> sed -i 's/{ write: false },//' node_modules/@angular-architects/native-federation/src/builders/build/builder.js

I still had to do this, it didn't help me installing the version 18.2.3.

```
"@angular-architects/native-federation": "^18.2.3",
"@angular/animations": "~19.0.1",
"@angular/cdk": "~19.0.1",
"@angular/common": "~19.0.1",
"@angular/compiler": "~19.0.1",
"@angular/core": "~19.0.1",
"@angular/forms": "~19.0.1",
"@angular/material": "~19.0.1",
"@angular/platform-browser": "~19.0.1",
"@angular/platform-browser-dynamic": "~19.0.1",
"@angular/router": "~19.0.1",
```

**Comment by marcodemoja** [comment]
> Hi @manfredsteyer
> 
> > sed -i 's/{ write: false },//' node_modules/@angular-architects/native-federation/src/builders/build/builder.js
> 
> I still had to do this, it didn't help me installing the version 18.2.3.
> 
> ```
> "@angular-architects/native-federation": "^18.2.3",
> "@angular/animations": "~19.0.1",
> "@angular/cdk": "~19.0.1",
> "@angular/common": "~19.0.1",
> "@angular/compiler": "~19.0.1",
> "@angular/core": "~19.0.1",
> "@angular/forms": "~19.0.1",
> "@angular/material": "~19.0.1",
> "@angular/platform-browser": "~19.0.1",
> "@angular/platform-browser-dynamic": "~19.0.1",
> "@angular/router": "~19.0.1",
> ```
> 
> this is my setup

same here

**Comment by danimaiochi** [comment]
@gigadie and @marcodemoja you guys are clearly using angular 19 with native-federation 18.2, it would only work with luck.
either go back to angular 18.2 or wait for the native-federation 19.

source: https://www.npmjs.com/package/@angular-architects/native-federation (check versions)

**Comment by marcodemoja** [comment]
@danimaiochi sorry I forgot to mention that I am using angular v18.2.* . I can't copy/past the content of my package-lock.json file unfortunately but I have just checked the angular version of all the mfe and shell app before commenting on this issue

**Comment by danimaiochi** [comment]
@marcodemoja try deleting your package-lock, node_modules folder and doing a npm install, I had some issues where it was getting previous cached versions from my tests, once I cleared everything..
oh, just saw your update, brilliant!

**Comment by marcodemoja** [comment]
yep, exactly as I mentioned :) thanks!

**Comment by muqtharali** [comment]
Facing this issue with Angular 19 and native federation 19.0.7. Any update on this?

**Comment by 27theo** [comment]
I think I'm also encountering the above issue, @manfredsteyer.

```ini
# Shell app (Angular 19)
├── @angular-architects/module-federation@19.0.1
├── @angular-architects/native-federation@19.0.9
├── @angular-devkit/build-angular@19.1.5
├── @angular/animations@19.1.4
├── @angular/cli@19.1.5
├── @angular/common@19.1.4
├── @angular/compiler-cli@19.1.4
├── @angular/compiler@19.1.4
├── @angular/core@19.1.4
├── @angular/forms@19.1.4
├── @angular/platform-browser-dynamic@19.1.4
├── @angular/platform-browser@19.1.4
├── @angular/router@19.1.4
├── @module-federation/enhanced@0.8.9
├── @softarc/native-federation-node@2.0.21
...
```

```ini
# Remote app (Angular 15)
├── @angular-architects/module-federation@15.0.3
├── @angular-devkit/build-angular@15.2.11
├── @angular/animations@15.2.10
├── @angular/cli@15.2.11
├── @angular/common@15.2.10
├── @angular/compiler-cli@15.2.10
├── @angular/compiler@15.2.10
├── @angular/core@15.2.10
├── @angular/elements@15.2.10
├── @angular/forms@15.2.10
├── @angular/platform-browser-dynamic@15.2.10
├── @angular/platform-browser@15.2.10
├── @angular/router@15.2.10
...
```

I was initially experimenting with a shell in 19 and a remote in 15 when I encountered the exception. I also tried a shell in 18, but encountered the same exception. I'm still looking into whether the problem is on my end.

```ini
# Shell app (Angular 18)
├── @angular-architects/native-federation@18.2.7
├── @angular-devkit/build-angular@18.2.14
├── @angular/animations@18.2.13
├── @angular/cli@18.2.14
├── @angular/common@18.2.13
├── @angular/compiler-cli@18.2.13
├── @angular/compiler@18.2.13
├── @angular/core@18.2.13
├── @angular/forms@18.2.13
├── @angular/platform-browser-dynamic@18.2.13
├── @angular/platform-browser@18.2.13
├── @angular/router@18.2.13
├── @module-federation/enhanced@0.8.9
├── @softarc/native-federation-node@2.0.21
...
```

Exception upon visiting the shell app:

```
ERROR RuntimeError: NG0203: inject() must be called from an injection context
such as a constructor, a factory function, a field initializer, or a function
used with `EnvironmentInjector#runInContext`. Find more at
https://angular.io/errors/NG0203
```

I have the shell app loading the remote app through the `router-outlet` immediately upon page load.

**Comment by 27theo** [comment]
@markusahrweileramcon Inter-version module federation is definitely supported by angular-architects' packages. There are a number of resources made available by the group instructing on how to get it working. I followed the resources to the best of my ability but ended up with that error.

The problem was likely on my end, but I've not yet figured out what it was.

Only when starting from scratch, beginning with a shell + remote pair both in v18, and then adding a remote in v15 to that shell with a few tweaks of my own did I get it working. As a side note, I suggest this method to anybody who is struggling to get federation working and stumbles across this thread.

**Comment by 27theo** [comment]
Incidentally, I just encountered the error again when specifying that no packages be shared between shell and remote. That may have been what I had configured when I encountered the error for the first time.

**Comment by dahfah** [comment]
I have this error: 'chunk-WDMUDEB6.js:48 ERROR RuntimeError: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with runInInjectionContext. Find more at https://angular.dev/errors/NG0203
    at injectInjectorOnly (core.mjs:1104:11)
    at ɵɵinject (core.mjs:1114:40)
    at Object.factory (core.mjs:19297:42)
    at core.mjs:2289:35
    at runInInjectorProfilerContext (core.mjs:880:5)
    at R3Injector.hydrate (core.mjs:2288:11)
    at R3Injector.get (core.mjs:2167:23)
    at __spreadProps.getStandaloneInjector (core.mjs:19337:31)
    at createRootViewInjector (core.mjs:17534:44)
    at ComponentFactory.create (core.mjs:17600:32)'   '

I have a shell and a microservice, each project with its own package.json configuration, but they both use the same Angular Federation version (19.0.7). However, I encounter an error when trying to retrieve the router from the microservice.

**Comment by 27theo** [comment]
@dahfah 

Would you post your `federation.config.js` files for shell and microservice? For me the problem lay in package sharing, as far as I could tell.

My minimal working configurations:

```typescript
// Shell -- Angular 19.1.4
module.exports = withNativeFederation({
  name: "shell-19",

  exposes: {
    "./Component": "./src/app/app.component.ts",
  },

  shared: {
    ...shareAll({
      singleton: true,
      strictVersion: true,
      requiredVersion: "auto",
    }),
  },

  skip: [/^@module-federation/],
});
```

```typescript
// Microservice -- Angular 19.1.4
module.exports = withNativeFederation({
  name: "remote-19",

  exposes: {
    "./Component": "./src/app/app.component.ts",
    "./web-components": "./src/bootstrap.ts",
    "./routes": "./src/app/app.routes.ts",
  },

  shared: {
    ...shareAll({
      singleton: true,
      strictVersion: true,
      requiredVersion: "auto",
    }),
  },

  skip: [],
});
```
