### ISSUE TITLE
Issue with `tsconfig.federation.json` generation

### ISSUE THREAD

**Issue by bbaia** [angular-architects/module-federation-plugin#641]
In `createTsConfigForFederation` method, The ` tsconfigAsString.replace(/\/\*.+?\*\/|\/\/.*(?=[\n\r])/g,'');` does not only remove comments :)

```
  "exclude": ["src/**/*.spec.ts", "src/**/*.mock.ts"]
```
is replaced by:
```
  "exclude": ["src*.mock.ts"]
```

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. It's solved now with Version 18.2.2.
