### ISSUE TITLE
Remote app fails on ngx-bootstrap package update even when shell app provides the shared-library to remotes

### ISSUE THREAD

**Issue by bhuvaneshwari-b** [angular-architects/module-federation-plugin#642]
hi @manfredsteyer , I have an angular library which is installed into the shell app using a .tgz file from a s3 bucket. We had imported the BsDatepicker code in that library from the ngx-bootstrap package and now we have removed all that code and imported it directly from ngx-bootstrap. Thus the import changed from 
<img width="542" alt="Screenshot 2024-09-13 at 2 04 47 PM" src="https://github.com/user-attachments/assets/cdd8bb0d-ec42-47e9-81fe-fb8bea50d797">
 to 
<img width="778" alt="Screenshot 2024-09-13 at 2 04 59 PM" src="https://github.com/user-attachments/assets/a3c61f47-68c5-4db3-9b0d-70555a8b6155">

The same is being exported in the library's module. This library is shared in webpack.config of both shell and host apps. So ideally building shell app should suffice, but the remote apps fail with saying below error
<img width="748" alt="Screenshot 2024-09-13 at 2 06 53 PM" src="https://github.com/user-attachments/assets/a6e2b76a-e665-4035-8c12-89278af19589">
 
Shell and Remote webpack config
<img width="456" alt="Screenshot 2024-09-13 at 3 34 15 PM" src="https://github.com/user-attachments/assets/906d6abf-71e4-4f33-9483-ae8664f7e2db">

module federation: 15.0.3
angular : v15
ngx-bootstrap: 9.0.0

Initial findings:
 I had found that redeploying remote app fixes the issue. As all our shell and remote apps use same node_modules folder(using symlinks) I think it should be something related to node_modules as rebuilding the apps work. But ideally the changes in the shared-library should work with just building shell app as its shared.

Tried importing BsDatepickerModule in shell's app app.module.ts and shared library's modules as well. Still no luck

**Comment by manfredsteyer** [comment]
So, the thing is, if you compile a piece of code with Angular version X, it expects to see this very version at runtime. Even a different patch version can be problematic. This is because the compiled code uses internal APIs of Angular, and they don't align with semver.
