### ISSUE TITLE
`native-federation:build` builder does not take into account custom index file

### ISSUE THREAD

**Issue by bbaia** [angular-architects/module-federation-plugin#644]
Using latest 17.x version, but its seems the bug is still there in latest code (see updateIndexHtml method) :

The code does not care of the configuration when using a custom index.html file
```
"options": {
   ...
   "index": "projects/app/src/my-index.html",
   ...
```

**Comment by manfredsteyer** [comment]
yes, this one is not used.

**Comment by bbaia** [comment]
So, it will not be fixed?

**Comment by bbaia** [comment]
I don't understand why it is hard coded while there is a [parameter](https://angular.dev/reference/configs/workspace-config#index-configuration) for that in `angular.json` file
