### ISSUE TITLE
Migration of Module federation to Native federation issue

### ISSUE THREAD

**Issue by muqtharali** [angular-architects/module-federation-plugin#646]
I am using angular CLI 17 and module federation 17.

I am trying to migrate to angular new build system. In the existing angular.json, I have this builder

`"builder": "ngx-build-plus:browser",`

To use the new angular build system, I am migrating the module federation to native federation plug in using this migration guide
[https://github.com/angular-architects/module-federation-plugin/blob/main/libs/native-federation/docs/migrate.md](url)

I have upgraded module federation to 18.0.4.

But when I run the below command

`ng g @angular-architects/module-federation:remove --project  project-name`

Getting this error

> **architect.build.options.main not found for project  project-name**

where as my angular.json has this hierarchy

```
"architect": {
        "build": {
          "builder": "ngx-build-plus:browser",
          "options": {
            "outputPath": "dist/project-name",
            "index": "src/index.html",
            "main": "src/main.ts"
          }
```

I don't understand what is the issue here. Can you please provide your inputs.

**Comment by muqtharali** [comment]
Looks like there was some issue with project name in the command. Now I am passing the project name which is available in angular.json. 
After this change, getting the below error 
**Cannot read properties of undefined (reading 'browserTarget')**

**Comment by manfredsteyer** [comment]
Hi,

can you please share your angular.json and the name of the project you want to migrate?

**Comment by manfredsteyer** [comment]
Just published a new version of Mf. Can you please update and try again?
If it does not work, can you please provide your angular.json?

**Comment by muqtharali** [comment]
Thanks for the update @manfredsteyer.
I have tested with **@angular-architects/module-federation@18.0.6**, now I am able to run this command successfully
`ng g @angular-architects/module-federation:remove --project  project-name`

But it is not removing module-federation dependency from the project, just it is updating main.ts, angular.json and package.json

Is that the expectation? As per the migration guide, it is saying 

> Remove Module Federation from your poject(s):

I will test the complete migration and let you know the updates.

**Comment by manfredsteyer** [comment]
Glad it works now. You are right. The intention was to update the angular.json accordingly, which is, IMHO, the hardest part. Ultimately, when everything works, you can throw out the entry from your package.json.
