### ISSUE TITLE
Using Native Federation with the Service Worker causes a "Hash mismatch" error

### ISSUE THREAD

**Issue by berkon** [angular-architects/module-federation-plugin#647]
I'm using the Native Federation module and want to install the Service Worker. So I tried:

`ng add @angular/pwa`

but this results in the following error message:

`Path "undefined" does not exist.`

According to [this](https://medium.com/@lukas.caniga/angular-17-as-microfrontend-native-federation-supporting-pwa-and-ssr-1e9d43eb411d) post, it looks like the Native Federation module does not support this command. So I added the Service Worker manually (without using the schematics). In general it looks fine, but when I run `ng serve` I'm always getting a:

`Hash mismatch ...`

error for the `index.html` file (sometimes also for `chunk-xxxx.js` files). This also happens when I'm using an alternate server module like `http-server` and calling `ng build` before. To me it looks like that `ngsw-config` is called too early in the build process and obviously `index.html` gets modified afterwards. I don't know why. When I'm calling `ngsw-config` manually after `ng build`, the correct hash is written to `ngsw.json` and the error disappears. But I can't make it work for `ng serve` too.

**Comment by manfredsteyer** [comment]
Hi,

Yes, service workers and Angular i18n are not supported.

IMHO, this combination does not fit that well because Micro Frontends are used for huge systems that are normally not made offline-aware with service workers as a whole.

**Comment by berkon** [comment]
Hi Manfred,

thanks a lot for your confirmation! The main reason why I need the Service Worker is to show OS native notifications. I know this is supported via the Notification interface too, but there are some features like "Actions" (putting buttons in a notification e.g. for accept/decline) and also the function getNotifications() which returns a list of all notifications (which is very useful e.g. for not showing the same notification twice).

Regards,
Bernd
