### ISSUE TITLE
Injecting data throw @Input() or @Inject() into MF Remote Component 

### ISSUE THREAD

**Issue by ikonezg** [angular-architects/module-federation-plugin#65]
Loading Components dynamically as a widget from the remote works perfectly. Thank you, Manfred.  If I have that kind of Component and I want to load it into the Shell and pass the context into it. How can we do this. I tried injector token, but the problem is that injector token in shell and remote MF is different. Also, the token is not registered in RemoteMF.

Thank you

**Comment by pirminrehm** [comment]
How did you load the Components dynamically?

I've created a sample multi-repo project where Components are lazy loaded via Module Federation. They have @Inputs to pass a context with.
The whole sample project:
https://github.com/pirminrehm/ng-mf-shell
The lazy loaded component:
https://github.com/pirminrehm/ng-mf-notification/blob/main/src/app/single-components/add-alert-button/add-alert-button.component.ts
And where it's lazy loaded:
https://github.com/pirminrehm/ng-mf-weather/blob/main/src/app/weather-widget/weather-widget.component.ts

**Comment by ikonezg** [comment]
> How did you load the Components dynamically?
> 
> I've created a sample multi-repo project where Components are lazy loaded via Module Federation. They have `@Inputs()` to pass a context with.
> The whole sample project:
> https://github.com/pirminrehm/ng-mf-shell
> The lazy loaded component:
> https://github.com/pirminrehm/ng-mf-notification/blob/main/src/app/single-components/add-alert-button/add-alert-button.component.ts
> And where it's lazy loaded:
> https://github.com/pirminrehm/ng-mf-weather/blob/main/src/app/weather-widget/weather-widget.component.ts#L41

No, my project is a little different. I'm loading components and not modules. Also, I'm injecting those components into the dom with cdk portal ( or with component factory resolver, same thing) . My inspiration was Manfreda plugin example.

**Comment by pirminrehm** [comment]
> No, my project is a little different. I'm loading components and not modules. Also, I'm injecting those components into the dom with cdk portal ( or with component factory resolver, same thing) . My inspiration was Manfreda plugin example.

That's more or less what I coded in my example. In order to load the single Component it is wrapped into a module. The Component is then extracted from the module, injected via component factory and inputs are added.

**Comment by manfredsteyer** [comment]
Hi,

if you use a token, you need to put it into a shared lib.

Here, I'm using another approach: Instantiating the component by hand and setting props by hand.

https://www.angulararchitects.io/aktuelles/dynamic-module-federation-with-angular-2/

Best,
Manfred
