### ISSUE TITLE
Nested importing (openlayer, ol)

### ISSUE THREAD

**Issue by Chutka** [angular-architects/module-federation-plugin#658]
### For which library do you need help?

native-federation

### Question

How I can import nested modules which isn't exported in index.js root folder (import {} from 'ol' - can't work in that case) 
```
import ImageLayer from 'ol/layer/Image';
import TileLayer from 'ol/layer/Tile';
```
The code above cause an error `Unable to resolve specifier`
Because all nested folders don't exist in importMap while resolving path (only root 'ol' path) 

<img width="722" alt="Screen Shot 2024-10-07 at 21 39 33" src="https://github.com/user-attachments/assets/f2cb1e73-d425-4436-944a-d9fa3fa8ccd8">

Saw the https://github.com/angular-architects/module-federation-plugin/issues/430 but after closing the same question was added

Maybe someone asked that but couldn't find the same topic

**Comment by rainerhahnekamp** [comment]
@Chutka, correct me if I'm wrong but your are trying to access files, which are not part of the primary or secondary entry point right? If yes, that will not work. You're trying to access elements which are meant to be encapsulated.

**Comment by Chutka** [comment]
But it's a part of `ol` library, I don't know why they aren't exports all of the sub-packages in index.ts (to be able to use all classes like `Image`, `Title` and others - but I don't want to get an access to smth like a "hidden" part of library which should be used by developer) 
Ok, as I see it can be resolved somehow right now in module federation - am I right ? 
____
P.S. -> I've shared an example when how to reproduce the problem https://github.com/angular-architects/module-federation-plugin/issues/430#issuecomment-2401970383

**Comment by rainerhahnekamp** [comment]
@Chutka I mean if they are not exposing it, they really think of them as encapsulated. The other option is that they expose as secondary entrypoint which is support by native federation.

Don't know about Module Federation. That is webpack.

**Comment by Chutka** [comment]
Oh... I see, thanks for your help
