### ISSUE TITLE
Help Needed: Choosing Between Native and Module Federation in Angular 18

### ISSUE THREAD

**Issue by CavidH** [angular-architects/module-federation-plugin#666]
### For which library do you need help?

native-federation, module-federation

### Question

Hello,

I’m currently working on an Angular 18 project and I'm trying to decide between using Native or Module Federation for my architecture. I would appreciate any guidance or insights on the following points:

Performance: How does each option impact application performance?
Complexity: Which option tends to be more complex in terms of setup and maintenance?
Scalability: Which solution is more scalable for larger applications?
Best Practices: Are there any best practices or recommendations for choosing between the two?
I’m looking forward to any suggestions or experiences you might have!

Thank you!

**Comment by sportypriyank** [comment]
We recently shifted to native federation from module federation as Angular now uses esbuild by default and module federation only works with webpack builder. Usage wise they both are same. I would recommend to go with native federation with the for 17+ angular versions.

**Comment by CavidH** [comment]
> We recently shifted to native federation from module federation as Angular now uses esbuild by default and module federation only works with webpack builder. Usage wise they both are same. I would recommend to go with native federation with the for 17+ angular versions.

I'm using Angular 18, and I'm having issues with many libraries and packages.

**Comment by rainerhahnekamp** [comment]
@CavidH, in essence, both native federation and module federation enable lazy loading of modules or components at runtime that are unknown during compilation.

The key difference is that module federation relies on Webpack for both splitting and loading, which ties you to the Webpack. Although there are some new developments for RSPack as well.

On the other hand, native federation uses esbuild for splitting, but loading happens via import maps, a Web standard (https://github.com/WICG/import-maps). This makes it independent of any specific bundler.

For obvious reasons, I'd go with native federation.

**Comment by CavidH** [comment]
> @CavidH, in essence, both native federation and module federation enable lazy loading of modules or components at runtime that are unknown during compilation.
> 
> 
> 
> The key difference is that module federation relies on Webpack for both splitting and loading, which ties you to the Webpack. Although there are some new developments for RSPack as well.
> 
> 
> 
> On the other hand, native federation uses esbuild for splitting, but loading happens via import maps, a Web standard (https://github.com/WICG/import-maps). This makes it independent of any specific bundler.
> 
> 
> 
> For obvious reasons, I'd go with native federation.

Thank you for the response.

**Comment by CavidH** [comment]
> @CavidH, in essence, both native federation and module federation enable lazy loading of modules or components at runtime that are unknown during compilation.
> 
> 
> 
> The key difference is that module federation relies on Webpack for both splitting and loading, which ties you to the Webpack. Although there are some new developments for RSPack as well.
> 
> 
> 
> On the other hand, native federation uses esbuild for splitting, but loading happens via import maps, a Web standard (https://github.com/WICG/import-maps). This makes it independent of any specific bundler.
> 
> 
> 
> For obvious reasons, I'd go with native federation.


I had another question: sometimes when using native federation, some libraries cannot be resolved, and errors occur. What could be the reason for this?

**Comment by rainerhahnekamp** [comment]
In most cases that is because those libraries are not in ESM format. Imports Maps require that and if they encounter CommonJS there will be an error. In this case, check if that library has an ESM version or just don't share it.

**Comment by rainerhahnekamp** [comment]
@CavidH closing this one. If you need more help, feel free to re-open it again.
