### ISSUE TITLE
Cannot find module '@angular-devkit/schematics'

### ISSUE THREAD

**Issue by bittagUser** [angular-architects/module-federation-plugin#667]
### With what library do you have an issue?

native-federation

### Reproduction of the bug/regression with instructions

Starting from a clean project, I try running the command ng add @angular-architects/native-federation or ng g @angular-architects/native-federation:init --project mfe1 --port 4201 --type remote, but I still get the same error.
![Screenshot 2024-10-15 121347](https://github.com/user-attachments/assets/10a6b80b-eade-47c1-a4f8-52eed18a13e3)

### Expected behavior

Native Federation should be configured correctly.

### Versions of Native/Module Federation, Angular, Node, Browser, and operating system

"dependencies": {
    "@angular/animations": "^18.2.0",
    "@angular/common": "^18.2.0",
    "@angular/compiler": "^18.2.0",
    "@angular/core": "^18.2.0",
    "@angular/forms": "^18.2.0",
    "@angular/platform-browser": "^18.2.0",
    "@angular/platform-browser-dynamic": "^18.2.0",
    "@angular/router": "^18.2.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.10"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "18.1.4",
    "@angular/cli": "^18.2.8",
    "@angular/compiler-cli": "^18.2.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.2.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.5.2"
  }

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by vtolstov** [comment]
how you solve the issue?
