### ISSUE TITLE
unable to install @angular-architects/module-federation

### ISSUE THREAD

**Issue by VenkataSKota** [angular-architects/module-federation-plugin#67]
Getting the following error when `npm i @angular-architects/module-federation@12.2.1`

Error:
`
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @angular/common@undefined
npm WARN node_modules/@angular-architects/module-federation/node_modules/@angular/common
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @angular/common@">=12.4.0" from @angular-architects/module-federation-runtime@12.4.0
npm WARN node_modules/@angular-architects/module-federation/node_modules/@angular-architects/module-federation-runtime
npm WARN   @angular-architects/module-federation-runtime@"^12.2.0" from @angular-architects/module-federation@12.2.1
npm WARN   node_modules/@angular-architects/module-federation
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @angular/core@undefined
npm WARN node_modules/@angular-architects/module-federation/node_modules/@angular/core
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @angular/core@">=12.4.0" from @angular-architects/module-federation-runtime@12.4.0
npm WARN node_modules/@angular-architects/module-federation/node_modules/@angular-architects/module-federation-runtime
npm WARN   @angular-architects/module-federation-runtime@"^12.2.0" from @angular-architects/module-federation@12.2.1
npm WARN   node_modules/@angular-architects/module-federation
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular/common@>=12.4.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Local\npm-cache\_logs\2021-07-09T18_34_49_694Z-debug.log
`

**Comment by VenkataSKota** [comment]
I am able to address this using --legacy-peer-deps option. 

`npm i @angular-architects/module-federation@12.2.1 --legacy-peer-deps`

**Comment by marcelnoack** [comment]
I get the same error when using it with `ng add`
