### ISSUE TITLE
loadChildren doesn't work with named router-outlet

### ISSUE THREAD

**Issue by jeka5555** [angular-architects/module-federation-plugin#68]
I add the **outlet** property to the app.routing.ts:
``` 
    {
      path: 'flights',
      outlet: 'test',
      loadChildren: () => loadRemoteModule({
          remoteEntry: URL,
          remoteName: 'mfe1',
          exposedModule: './Module'
        })
        .then(m => m.FlightsModule)
    },
```

In the template, add the name attribute for the router-outlet tag:
```
<router-outlet name="test"></router-outlet>
```

The microapplication stops loading inside the named router-outlet tag. 
This error does not allow me to connect multiple micro-applications on the same routing path.

**Comment by GioLynx** [comment]
Hi Jeka, do you have solved this problem? thanks

**Comment by smasala** [comment]
`This error does not allow me to connect multiple micro-applications on the same routing path.`

This doesn't work because they all compete for the same URL on load. You need to queue the loading of multiple MFEs and then trigger the initial route one by one....

**Comment by mikezks** [comment]
Thanks @smasala, I agree.
This is how the Angular Router works and not connected to this package or Module Federation in general.
