### ISSUE TITLE
Unable to use date-fns-tz in native-federated application

### ISSUE THREAD

**Issue by Muntazir86** [angular-architects/module-federation-plugin#689]
### With what library do you have an issue?

native-federation

### Reproduction of the bug/regression with instructions

1. clone [repo](https://github.com/Muntazir86/native-federation-text.git)
3. build shared-lib 
4. Serve both shell and mfe1
5. application failed to load
6. getting `main.ts:6 SyntaxError: The requested module 'blob:http://localhost:4200/467b57c0-0db6-4911-a418-3659f3640a57' does not provide an export named 'getTimezoneOffset' (at shared_lib.js:4:10)` error in console.

### Expected behavior

Should work as working in application with out native federation

### Versions of Native/Module Federation, Angular, Node, Browser, and operating system

Angular: 17.3.0
Native federation: 17.1.8
date-fns: 2.30.0
date-fns-tz: 1.3.8

### Other information

 i have checked that `getTimezoneOffset` is exported from date-fns-tz

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by manfredsteyer** [comment]
Hi,

Native Federation creates a bundle per entry point. In date-fns each function has an entry point of its own. So, if you use the following import, it should work:

import getTimezoneOffset from 'date-fns-tz/getTimezoneOffset';
