### ISSUE TITLE
process is not defined error in Angular 17 host app loading Angular 14 remote app using Module Federation

### ISSUE THREAD

**Issue by Vishnu94833** [angular-architects/module-federation-plugin#703]
---

**Description:**  
I'm encountering an error when trying to load a remote Angular module in my **Angular 17** host application. The remote application is built with **Angular 14**, and both are configured with **Module Federation** using the `@angular-architects/module-federation` package.

When attempting to navigate to the route loading the remote module, I get the following error in the browser console:

```
ReferenceError: process is not defined
    at 94655 (util.js:109:1)
    at __webpack_require__ (bootstrap:19:1)
    at 50372 (checks.js:6:12)
    at __webpack_require__ (bootstrap:19:1)
    at 14430 (index.js:6:1)
    at __webpack_require__ (bootstrap:19:1)
    at 89236 (backoff.js:5:15)
    at __webpack_require__ (bootstrap:19:1)
    at 42215 (index.js:4:15)
    at __webpack_require__ (bootstrap:19:1)
```

---

**Host Application:**
- **Angular Version:** 17
- **Routing Configuration:**
    ```typescript
    import { NgModule } from '@angular/core';
    import { RouterModule, Routes } from '@angular/router';
    import { loadRemoteModule } from '@angular-architects/module-federation';

    const routes: Routes = [
      {
        path: 'mfe1',
        loadChildren: () =>
          loadRemoteModule({
            type: 'module',
            remoteEntry: 'http://localhost:8081/remoteEntry.js',
            exposedModule: './AppModule',
          }).then(m => m.AppModule),
      },
    ];

    @NgModule({
      imports: [RouterModule.forRoot(routes)],
      exports: [RouterModule],
    })
    export class AppRoutingModule {}
    ```

---

**Remote Application:**
- **Angular Version:** 14
- **Webpack Configuration:**
    ```javascript
    const { ModuleFederationPlugin } = require('webpack').container;

    module.exports = {
      output: {
        publicPath: "auto", 
      },
      plugins: [
        new ModuleFederationPlugin({
          name: 'remoteApp',
          filename: 'remoteEntry.js',
          exposes: {
            './AppModule': './src/app/app.module.ts',
          },
          shared: {
            "@angular/core": { singleton: true, eager: true, requiredVersion: 'auto' },
            "@angular/common": { singleton: true, eager: true, requiredVersion: 'auto' },
            "@angular/router": { singleton: true, eager: true, requiredVersion: 'auto' },
          },
        }),
      ],
    };
    ```

---

**Steps to Reproduce:**
1. Start the **remote application** on `http://localhost:8081/`.
2. Start the **host application** on `http://localhost:4200/`.
3. Navigate to the `mfe1` route in the host app.

---

**Expected Behavior:**  
The remote module should load successfully in the host application.

**Actual Behavior:**  
The following error is thrown in the browser console:  
`ReferenceError: process is not defined`

---

**What I’ve Tried:**
- Added `import 'process/browser';` to `polyfills.ts`.
- Used `webpack.ProvidePlugin` to polyfill `process`.
- Verified that `remoteEntry.js` is accessible at `http://localhost:8081/remoteEntry.js`.

---

**Questions:**
- Is there a specific configuration needed to make `process` available in this setup?
- Could the issue be related to version mismatches between Angular 17 (host) and Angular 14 (remote)?
- What is the recommended way to handle such issues in Module Federation setups?

---

**Comment by manfredsteyer** [comment]
If you want to mix and match different versions, you need to wrap your remotes into web components.
