### ISSUE TITLE
How to share host service in the remote application so that they can share observable events in angular 16

### ISSUE THREAD

**Issue by irfan99300** [angular-architects/module-federation-plugin#708]
Hello everyone, 
I have two angular applications one is host and one is remote which are two completely different repo. I am able to host remote module in host application using module federation version 16 in angular 16
I am not using any monorepo

Now I am stuck I want to share same instance of host service in remote application so that they can use observables events to communicate with each other

Any guidance or help or pointing in the right direction to achieve my goal of using observables events between host and remote

I tried to expose host service from host application and dynamically load in remote standalone component but it did not work

I am new to micro frontend any help will be highly appreciated

**Comment by manfredsteyer** [comment]
For this, you need to put the service in a shared npm package.
