### ISSUE TITLE
Failing to add PrimeNg component library with native-federation, where I succeed with module-federation

### ISSUE THREAD

**Issue by luboid** [angular-architects/module-federation-plugin#709]
Hi,

I'm trying to add PrimeNg library to Angular 18 projects with native federation, but somewhere I'm failing, I followed your examples. It works with module federation. I'm applying repos with test cases. Can you point me in the right direction?

[test-angular-module-federation-with-primeng](https://github.com/luboid/test-angular-module-federation-with-primeng)

[test-angular-native-federation-with-primeng](https://github.com/luboid/test-angular-native-federation-with-primeng)

ps: PrimeNg styles are missing.

**Comment by manfredsteyer** [comment]
Thanks for this info. We have investigated this issue and provide a fix asap. It has to do with the interplay of primeng's new theming API and native federation.

**Comment by HeneryHawk** [comment]
Hi
i do have the same issue.
The styles are not applied. I followed the instructions at [https://primeng.org/configuration](https://primeng.org/configuration) but after adding `@angular-architects/native-federation` the styles are gone and the theme from primeng is not applied anymore.

**Comment by manfredsteyer** [comment]
Stay tuned. I think we can fix this quickly

**Comment by manfredsteyer** [comment]
Short update: I have a working prototype. I think, I can provide a new lib version tomorrow.

**Comment by manfredsteyer** [comment]
Hi,

Good message: This is solved now. Just update to `@angular-architects/native-federation@18.2.5` (needs Angular 18.x).

Best wishes,
Manfred

PS:
For lower versions, I've provided a work around here:
https://github.com/angular-architects/module-federation-plugin/issues/695

**Comment by luboid** [comment]
Thank you!

**Comment by manfredsteyer** [comment]
Please activate the `transient` flag in your `federation.config.js`:

https://github.com/angular-architects/module-federation-plugin/tree/main/libs/native-federation#how-to-deal-with-transitive-dependencies

This is for backwards compatibility.
