### ISSUE TITLE
Sharing Components to remote app

### ISSUE THREAD

**Issue by NimitTRT** [angular-architects/module-federation-plugin#71]
I have a shell that has common utility components, like modals, confirmation boxes, etc.
How do I use those utility components in my remote apps. Do I have to duplicate the code or is there a way for remote apps to access shell components?

**Comment by tlinqu** [comment]
Check Manfred's articles: https://www.angulararchitects.io/aktuelles/the-microfrontend-revolution-module-federation-in-webpack-5/ and follow his examples which use @angular-architects/module-federation of this repo.

**Comment by mattvasc-mcd** [comment]
> Check Manfred's articles: https://www.angulararchitects.io/aktuelles/the-microfrontend-revolution-module-federation-in-webpack-5/ and follow his examples which use @angular-architects/module-federation of this repo.

Unfortunately I haven't seen yet on Manfred's examples a way to use components of the host on the remote part.

Usually it is done the other way around, so I guess that this issue still valid.

**Comment by frazzaglia** [comment]
You can create an npm library with all shared components. Then you can simply share it through webpack-shared.config.js file.
Another solution could be to create an angular library with the shared components and then register in webpack.config.js like this:

sharedMappings.register(
  path.join(__dirname, 'tsconfig.json'),
  [
    /* mapped paths to share */
    "@YOUR_LIBRARY_NAME"
  ]);

**Comment by mikezks** [comment]
See https://github.com/angular-architects/module-federation-plugin/issues/73#issuecomment-1025960316.
