### ISSUE TITLE
Native Federation

### ISSUE THREAD

**Issue by prasoon** [angular-architects/module-federation-plugin#710]
I am creating multi repo micro frontend using native federation.
I want to have routings in mfe apps and not able to expose those route in shell app..
can anyone help me out ?

**Comment by manfredsteyer** [comment]
Please have a look here:
https://www.angulararchitects.io/blog/micro-frontends-with-modern-angular-part-2-multi-version-and-multi-framework-solutions-with-angular-elements-and-web-components/
