### ISSUE TITLE
Rebuild federation artifacts with ng build --watch

### ISSUE THREAD

**Issue by ladler1** [angular-architects/module-federation-plugin#713]
### For which library do you need help?

native-federation

### Question

I’m currently evaluating the migration from module-federation to native-federation. When running the application with **ng serve** the federation artifacts are rebuild on code changes. When running the application with **ng build** and the **watch** flag only the application bundles are rebuilt but not the Federation artifacts. I want to only build my remote for local development and don’t start a dev server. Is it possible with this configuration to rebuild the federation artifacts too?

**Comment by manfredsteyer** [comment]
Thanks for this. I think we should support this with one of the next versions.

**Comment by manfredsteyer** [comment]
This will be supported by the next version, which we'll publish very soon!

**Comment by ladler1** [comment]
That's good to hear. Thank you

**Comment by manfredsteyer** [comment]
Just published version 18@latest and version 19. Now, setting watch:true for the NF builder should work.

**Comment by ladler1** [comment]
`[error] Error: server is not started
    at reloadBrowser (\node_modules\@angular-architects\native-federation\src\utils\dev-server.js:54:15)
    at runBuilder_1 (\node_modules\@angular-architects\native-federation\src\builders\build\builder.js:182:52)
    at runBuilder_1.next (<anonymous>)
    at resume (\node_modules\tslib\tslib.js:283:48)
    at fulfill (\node_modules\tslib\tslib.js:285:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)`

when an error occures the **ng build** with **watch** flag crashes since no server is started
