### ISSUE TITLE
Remote Providers Not Initialized After Build. Angular 19

### ISSUE THREAD

**Issue by odomanskyi** [angular-architects/module-federation-plugin#714]
### With what library do you have an issue?

native-federation

#### Reproduction Repository

[Reproduction repo link](https://github.com/odomanskyi/native-federation-ng19)

#### Steps to Reproduce

1. Clone the repository.
2. Run the dev server using:
```
nx serve host
nx serve remote
```
- The application works correctly.
3. Build the host application:
```
nx build host
nx build remote
```
4. Run the host application from the build:
```
node dist/apps/host/server/server.mjs
```

#### Actual Behavior

- No errors appear in the console.
- Remote modules load successfully.
- However, remote providers do not seem to be initialized.

#### Screenshots
Dev server working correctly:
<img width="700" alt="Dev Server Working" src="https://github.com/user-attachments/assets/73ea97f2-e57b-4400-8c23-2e1078b4ef73" />

Nothing happens when running the built application:
<img width="439" alt="image" src="https://github.com/user-attachments/assets/aa24c4bc-4694-4433-975c-e201b4f10d66" />

#### Additional Context

- The issue occurs only in the build environment.
- No visible errors in the console.

### Expected behavior

The application should work as it does in development mode, with all remote modules and providers initialized properly.

### Versions of Native/Module Federation, Angular, Node, Browser, and operating system

Module federation: 18.2.3
Angular: 19.0.4
Nx: 20.2.2
Ngrx: 19.0.0
Node: 20.14.0
Browser: Chrome 131.0.6778.86
Operating system: macOS 13.2

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by franktroia** [comment]
I believe I am experiencing the same issue in my large NX/Angular monorepo after upgrading to Angular 19. However my configuration is different. My configuration is without SSR, but loading dynamic micro-frontends using the router. I've been struggling with this issue for nearly a week now.

I took the repro from above and converted more closely to my use case and I replicated my issue, which does log an error the console. Here is the fork.
https://github.com/franktroia/native-federation-ng19

If you follow the same steps as OP, except after serving the host, attempt to load http://localhost:4200/remote and you will see the following error
```
chunk-2FVNVFHM.js:7 ERROR Error: NG0203
    at eI (_angular_core.6x2VgMhzmV.js:2:2769)
    at me (_angular_core.6x2VgMhzmV.js:2:2896)
    at Object.factory (_angular_core.6x2VgMhzmV.js:31:31626)
    at Sn.hydrate (chunk-2FVNVFHM.js:7:4368)
    at Sn.get (chunk-2FVNVFHM.js:7:3548)
    at Te.getStandaloneInjector (_angular_core.6x2VgMhzmV.js:31:31971)
    at Rn.create (chunk-2FVNVFHM.js:7:48856)
    at Nd.createComponent (chunk-2FVNVFHM.js:7:52965)
    at e.activateWith (chunk-2FVNVFHM.js:7:118650)
    at Ua.activateRoutes (chunk-2FVNVFHM.js:7:123403)
 ```
My guess is there is an issue with setting up the injectors after loading the remote.

**Comment by manfredsteyer** [comment]
Thanks for this information. There will be a version 19 for Angular 19 very soon.

**Comment by manfredsteyer** [comment]
Hi @odomanskyi,

Thanks for your reproduction. The thing is, it should not even work with ng serve. IMHO, this is not what the host assumes it is. 

```typescript
loadRemoteApp(): void {
  loadRemoteModule('remote', './provider').then(({ provideRemoteApp, RemoteActions }) => {
    if (!this._provided) {
      createEnvironmentInjector([provideRemoteApp()], this._environmentInjector);
      this._provided = true;
    }

    this._store.dispatch(RemoteActions.remoteLoaded());
  });
}
```

So, here, the host assumes that we are automatically switching to the new environment injector. But this is not the case.  `createEnvironmentInjector` returns a new environment injector that falls back to its parent when sth is not found there. 

What I would do:
- Create a lib providing a provideXYZ() function
- Call provideXYZ in the shell and in the mfe

Best wishes,
Manfred

**Comment by manfredsteyer** [comment]
We now have a version for Angular 19.
