### ISSUE TITLE
MFE doesn't load in shell with error : "The component must be standalone." with Angular 19 and @angular-architects/native-federation 19.0.2

### ISSUE THREAD

**Issue by hal1984** [angular-architects/module-federation-plugin#718]
### With what library do you have an issue?

native-federation

### Reproduction of the bug/regression with instructions

create new angular workspace:
- ng new native-federation-19
create shell and mfe1 projects:

- ng new application shell
- ng new application mfe1

add native federation: 
- npm i @angular-architects/native-federation -D
- ng g @angular-architects/native-federation:init --project mfe1 --port 4201 --type remote 
- ng g @angular-architects/native-federation:init --project shell --port 4200 --type dynamic-host

Configure basic routing as in this provided example:

https://github.com/hal1984/native-federation-19/tree/standalone-bug

run the project: npm run start

Resulting error in browser console:

```
hook.js:608 ERROR RuntimeError: NG04014: Invalid configuration of route ''. The component must be standalone.
    at assertStandalone (_angular_router.tQd_i61ZMM-dev.js:1227:11)
    at Object.next (_angular_router.tQd_i61ZMM-dev.js:3315:58)
    at rxjs_operators.qhak5zUfkG-dev.js:3910:74
    at OperatorSubscriber2._this._next (rxjs_operators.qhak5zUfkG-dev.js:829:9)
    at Subscriber2.next (rxjs_operators.qhak5zUfkG-dev.js:331:12)
    at rxjs_operators.qhak5zUfkG-dev.js:1652:18
    at OperatorSubscriber2._this._next (rxjs_operators.qhak5zUfkG-dev.js:829:9)
    at Subscriber2.next (rxjs_operators.qhak5zUfkG-dev.js:331:12)
    at rxjs.SHkuB73hYc-dev.js:1869:20
    at _ZoneDelegate.invoke (zone.js:369:28)
```

### Expected behavior

The page loads with the shell and the mfe1 into the router

### Versions of Native/Module Federation, Angular, Node, Browser, and operating system

Native Federation: 19.0.2
Operating System: macOS
Angular: 19.0.5
node: 22

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by manfredsteyer** [comment]
Hi,

Unfortunately, I was not able to reproduce this. Here, I updated our example app to v19, and it still works:
https://github.com/manfredsteyer/module-federation-plugin-example.git (branch **nf-standalone-solution**).

What do you do differently?
Can you please provide a reproduction?

Best wishes,
Manfred

**Comment by franklin7301** [comment]
In the shell’s route configuration, adding .then(m => m.AppComponent) should fix the issue. For example:

```
export const routes: Routes = [
  {
    path: '',
    loadComponent: () => 
      loadRemoteModule({
        remoteName: 'mfe1',
        exposedModule: './Component',
        fallback: DummyComponent
      }).then(m => m.AppComponent)
  }
];
```

**Comment by hal1984** [comment]
> In the shell’s route configuration, adding .then(m => m.AppComponent) should fix the issue. For example:
> 
> ```
> export const routes: Routes = [
>   {
>     path: '',
>     loadComponent: () => 
>       loadRemoteModule({
>         remoteName: 'mfe1',
>         exposedModule: './Component',
>         fallback: DummyComponent
>       }).then(m => m.AppComponent)
>   }
> ];
> ```

Yes, that was missing! Thank you!
