### ISSUE TITLE
serve SSR exits abruptly, without showing any error in Angular 19 and NF 19.0.2

### ISSUE THREAD

**Issue by hal1984** [angular-architects/module-federation-plugin#719]
### With what library do you have an issue?

native-federation

### Reproduction of the bug/regression with instructions

create new angular workspace:
- ng new native-federation-19 --ssr
create shell and mfe1 projects:

- ng new application shell
- ng new application mfe1

add native federation: 
- npm i @angular-architects/native-federation -D
- ng g @angular-architects/native-federation:init --project mfe1 --port 4201 --type remote 
- ng g @angular-architects/native-federation:init --project shell --port 4200 --type dynamic-host

Configure basic routing as in this provided example:

https://github.com/hal1984/native-federation-19/tree/ssr

run the project: "npm run build:mfe1 && npm run serve:ssr:mfe1"

output:

> INFO  Building federation artefacts
> Browser bundles      
> Initial chunk files   | Names            |  Raw size | Estimated transfer size
> polyfills-YJELPHIQ.js | polyfills        |  71.96 kB |                23.24 kB
> main-7U6Z6FAN.js      | main             |   2.34 kB |               951 bytes
> chunk-2VMXMS7J.js     | -                | 661 bytes |               661 bytes
> styles-5INURTSO.css   | styles           |   0 bytes |                 0 bytes
> 
>                       | Initial total    |  74.96 kB |                24.85 kB
> 
> Lazy chunk files      | Names            |  Raw size | Estimated transfer size
> chunk-2SWKKKAH.js     | bootstrap        | 835 bytes |               835 bytes
> 
> 
> Server bundles       
> Initial chunk files   | Names            |  Raw size
> polyfills.server.mjs  | polyfills.server |  31.05 kB |                        
> server.mjs            | server           |  16.11 kB |                        
> chunk-2XAXBCZJ.mjs    | -                |   1.44 kB |                        
> chunk-UVH22FHU.mjs    | -                |   1.19 kB |                        
> main.server.mjs       | main.server      | 506 bytes |                        
> 
> Lazy chunk files      | Names            |  Raw size
> chunk-UYGVM4ZZ.mjs    | bootstrap-server | 838.43 kB |                        
> 
> Prerendered 0 static routes.
> Application bundle generation complete. [0.911 seconds]
> 
> Output location: /Users/jorge/Desktop/native-federation-19/dist/mfe1
> 
> 
> > native-federation-19@0.0.0 serve:ssr:mfe1
> > node dist/mfe1/server/server.mjs
> 
> ➜  native-federation-19 git:(ssr) 
> 
> 

### Expected behavior

MFE 1 is served and don't close unexpectedly 

### Versions of Native/Module Federation, Angular, Node, Browser, and operating system

NF 19.0.2
Angular 19.0.5
node: 22

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by manfredsteyer** [comment]
Hi,

Thanks for pointing this out.

It seems like Angular 19 is generating this if statement in the `server.ts` that becomes the `bootstrap-server.ts` in our setup:

```
if (isMainModule(import.meta.url)) { ... }
```

This prevents the server from starting when used with Native Federation. The reason is that when using Federation, the main bundle needs to initialize Federation and import the rest of the application. Please remove it by hand (just the if, not its content).

I think we can remove this line automatically via our schematic in the future.

Btw: In the MFE1 project, I also changed the relBundlePath to '../browser/' in your server.ts. It was pointing to the shells bundles (I guess this was due to copy/paste).
