### ISSUE TITLE
Sharing root level providers of shell angular app with mfe1

### ISSUE THREAD

**Issue by vighnesh92** [angular-architects/module-federation-plugin#73]
Hi,

Building upon the idea described in this [article](https://www.angulararchitects.io/aktuelles/the-microfrontend-revolution-part-2-module-federation-with-angular/), how do i share the root level providers of the shell app with each loaded microfrontend apps?

Example:
Lets say the shell app provides a counter service with a count variable. How can i share this counter service with the state (count variable) across the loaded microfrontend apps. 

It would be great if there is an example demonstrating the same. 

FYI: I am trying to achieve this in a multi-repo environment. 

Thanks,
Vighnesh KSP

**Comment by vighnesh92** [comment]
As of now, the only option is to push the shared services to a common library. Then consume them in the respective MFEs.

**Comment by mikezks** [comment]
In a single-version setup, you can share monorepo libs or npm packages with your services `providedIn: 'root'`.
In a multi-version setup, no dependency injection is possible by design.

**Comment by vighnesh92** [comment]
> In a single-version setup, you can share monorepo libs or npm packages with your services `providedIn: 'root'`. In a multi-version setup, no dependency injection is possible by design.

Exactly, this is what is currently possible. I am asking whether can we achieve it without moving the common services outside to a npm package. The root app can act as provider for the common services.

**Comment by mikezks** [comment]
Yes, you  can put it into a monorepo lib. See no. 6 of the linked blog series.
