### ISSUE TITLE
passing props to web-component-wrapper doesn't attaches those props to the web component as attributes

### ISSUE THREAD

**Issue by syed-alam218** [angular-architects/module-federation-plugin#78]
this is how I'm passing props:-
```
{
        path: 'engage',
        component: WebComponentWrapper,
        data: {
          remoteEntry: enageEntry,
          remoteName: 'mfe4',
          exposedModule: './web-components',
          elementName: 'mfe4-element',
          props: {
            baseUrl: '/engage'
          }
        } as WebComponentWrapperOptions
 }
 ```
      
**output:-**
```<mfe4-element>...</mfe4-element>```

**expected output:-**
```<mfe4-element baseUrl="/engage">...</mfe4-element>```

https://github.com/angular-architects/module-federation-plugin/blob/main/libs/mf-tools/src/lib/web-components/web-component-wrapper.ts

### here line no. 35 in the source code is the issue I guess 🤔 

```
private populateProps() {
    for (const prop in this.props) {
       this.element[prop] = this.props[prop];
    }
  }
```
  
  **suggested fix:-**
  
  ```
  private populateProps() {
    for (const prop in this.props) {
       this.element.setAttribute(prop, this.props[prop]);
    }
  }
  ```

**Comment by manfredsteyer** [comment]
I guess, setting props instead of attributes is the better solution b/c attributed cannot deal with complex data (objects, arrays) and  it's a common best practice that the props should cover everything attributes cover and perhaps a bit more (e. g. objects as mentioned)

**Comment by liu351** [comment]
providing props from the router data is not supported in the existing WebComponentWrapper, is it? It looks like only the options can be set if we are using the WebComponentWrapper in our router configuration. What do you recommend if we want to pass it like below that is similar to OP's example?

```
 {
                matcher: startsWith(entry.routePath),
                component: WebComponentWrapper,
                data: {
                    type: 'module',
                    remoteEntry: entry.remoteEntry,
                    exposedModule: entry.exposedModule,
                    elementName: entry.elementName,
                    props: {
                        baseUrl: entry.routePath
                    }
                } as WebComponentWrapperOptions
            }
```
