### ISSUE TITLE
"Uncaught Error: Shared module is not available for eager consumption" when running tests

### ISSUE THREAD

**Issue by teflonwaffles** [angular-architects/module-federation-plugin#81]
I've been having a similar issue to [this one](https://github.com/angular-architects/module-federation-plugin/issues/33). I installed the plugin into an Angular app, and the existing unit tests started failing with a similar message. (I'm not trying to test module federation -- these are tests of existing functionality that used to pass before installing the plugin.)

For the time being, I'm following the guidance [here](https://github.com/manfredsteyer/module-federation-plugin-example-nx/issues/3) to work around this issue -- essentially, setting each shared dependency to 'eager: true'. But is there a better way?

What extra configuration will allow Karma/Jasmine tests to pass? (What would the guidance in your reply to the previous issue look like?)

**Comment by manfredsteyer** [comment]
Hi,

yes, setting everything to eager is one option.

You could also completely disable module federation for testing remotes. For this, just remove this line in angular.json:

```
"extraWebpackConfig": "projects/shell/webpack.config.js"
```
