### ISSUE TITLE
No NgModule metadata found for exposed angular11.2.x module

### ISSUE THREAD

**Issue by nishadthajudeen001** [angular-architects/module-federation-plugin#82]
what would be the possible reason for below error in the exposed angular module while consuming with loadRemoteModule 

Error: No NgModule metadata found for 'abcManagementModule'.Error: No NgModule metadata found for 'abcManagementModule'.

Angular 11.2.x version

**Comment by manfredsteyer** [comment]
Can you please try upgrading to Angular 12. This lib doesn't support Angular 11 anymore as only CLI 12 and upwards officially support webpack 5 and MF.

**Comment by nishadthajudeen001** [comment]
Thanks @manfredsteyer
