### ISSUE TITLE
Consume react remote using dynamic module federation

### ISSUE THREAD

**Issue by harshavb7** [angular-architects/module-federation-plugin#85]
I have been trying to integrate react mfe into angular shell using dynamic federation approach. But its failing in loadRemoteModule function as react doesn't have valid ngModuleName, Can someone help in guiding me in integrating react mfe into angular shell using dynamic federation.

**Comment by manfredsteyer** [comment]
I'm sorry, this lib has been created for Angular.

**Comment by harshavb7** [comment]
> I'm sorry, this lib has been created for Angular.
Thanks @manfredsteyer for the reply.
My shell is based on Angular and I'm using this lib to dynamically load remotes.. I was able to load Angular remotes but React remotes are not loaded dynamically due ngModuleName. Can you please help me in consuming react remotes in Angular shell.
