### ISSUE TITLE
Application sometimes not bootstrapping in firefox

### ISSUE THREAD

**Issue by unib1t** [angular-architects/module-federation-plugin#86]
After transforming my application (angular CLI 12.2.0)  with module-federation (12.4.0) it is _sometimes_ not bootstrapping in firefox.
Behaviour is very randomly, sometimes it starts correctly after some refreshes. 
From the network inspection I see that the application bundles are correctly donwloaded. 
So seems like webpack is not bootstrapping the app, unfortunately nothing in console.
Tested on different versions of firefox, including latest.
Works perfectly and consistently in Chrome.
Any advice on how to debug / investigate this problem?

**Comment by unib1t** [comment]
Solved. I turned out to be a circular dependency in my shared library. The import statement was referencing the dependency by the mapped lib name instead of the plain path. Problem was never raised during compile- or runtime, which made it hard to find.

**Comment by cropd** [comment]
@unib1t can you explain this a little bit more? I know, you had this issue about 2 years ago, but maybe you can still remember how you solved it ;) 
I might have the same issue with my react app, at least I have the exact same behaviour...

**Comment by kishan110** [comment]
@cropd I have the same behavior with angular 14 application and same issue in safari browser as well.
Works properly and consistently in Chrome.
If you find any solution or where to debug, Please share it.

**Comment by kishan110** [comment]
In my case, removed `import zone.js` from poliyfill.ts file and added into bootstrap file then working properly in Firefox/safari browser
`require('zone.js/dist/zone');`

**Comment by murli2308** [comment]
@kishan110 saved my day. thanks its working like charm

**Comment by vlyamzin** [comment]
For those who are struggling with this issue, if you're using a shared library approach as detailed here: [Using Module Federation with (Nx) Monorepos and Angular](https://www.angulararchitects.io/en/blog/using-module-federation-with-monorepos-and-angular/), you should use relative paths within this library. Using TypeScript aliases can lead to circular dependencies.

Here is an example:

```
// project structure

projects
|-- shell
|   |-- webpack.config.js
|-- shared-lib
|   |-- auth.componen.ts
|   |-- auth.service.ts
|   |-- public-api.ts
|-- tsconfig.json

```

```js
// tsconfig.json
{
  "compilerOptions": {
    "paths": {
      "@demo/shared-lib": ["projects/shared-lib/public-api.ts"]
    },
  }
}
```

```javascript
// shell/webpack.config.js

const {  withModuleFederationPlugin} = require('@angular-architects/module-federation/webpack');

module.exports = withModuleFederationPlugin({
  sharedMappings: ['@demo/shared-lib']
});
```

```javascript
// shared-lib/auth.component.ts

import {AuthService} from '@demo/shared-lib' // <-- this does not work
import {AuthService} from './auth.service.ts' // <-- this works
```
