### ISSUE TITLE
How to access remote app's service worker from the shell app?

### ISSUE THREAD

**Issue by SavvasAkshayJain** [angular-architects/module-federation-plugin#88]
I have an MFE with a custom service worker for offline support. My requirement is to have this MFE's service worker control the page when loaded from the shell app. How do I achieve this using module-federation-plugin, given both the MFE and shell apps are angular applications?

**Comment by manfredsteyer** [comment]
In this case, everything runs in the context of the shell. Hence, you need to add a script tag to the shell pointing to the service worker.
