### ISSUE TITLE
Can we have an example to share an individual component in the tutorial

### ISSUE THREAD

**Issue by shyam1992** [angular-architects/module-federation-plugin#9]
Hi, 
I would like to know if there is an option to share individual components like in React using Module federation in Angular.
If yes, can someone please share an example or update the tutorial accordingly.

Thanks.

**Comment by rustyy** [comment]
Hi @shyam1992,
you may have a look here: https://github.com/manfredsteyer/multi-framework-micro-frontend 
and there https://youtu.be/oXGeywCIQDU?t=3632

Hope this helps.

**Comment by shyam1992** [comment]
@rustyy thanks,
Those resources were really helpful, but there are no example to include an individual component in a screen rather than loading a module on route change. I think I will figure it out by trial end error .:)

**Comment by rustyy** [comment]
@shyam1992 , you are talking about an Angular-Component right?
So you want to inject a component from a remote into the host? 

I played around with a similar example, you may use componentFactoryResolver for this. I just pushed my current example to 

https://github.com/rustyy/angular-playground/blob/cf09d59f93cb47462f76c8741085a81b0d518c1f/module-federation/projects/host/src/app/app.component.ts#L1-L48

Not yet sure if it is the best solution possible, but it may be one ;)

**Comment by shyam1992** [comment]
Great, This at least solves the purpose for time being until a clear solution comes out. Thanks @rustyy 👍
