### ISSUE TITLE
Cannot download packages with ng add anymore 

### ISSUE THREAD

**Issue by SavvasZaidQuadri** [angular-architects/module-federation-plugin#93]
Every since I downloaded the mod fed plugin package my main.ts/bootstrap.ts were automatically modified. Now I cannot install things like angular material or bootstrap or font awesome with ng add because I get the error: `bootstrap call not found.` Is there something in angular.json I should be changing or something?

I did try to run this first: ng g @angular-architects/module-federation:boot-async false --project yourProject
but then i get the error: `No project index HTML file could be found.`

Steps to reproduce: 
1) take any existing mfe and run ng add @angular-architects/module-federation@next
2) ng add @angular/material

**Comment by mbharanidharan88** [comment]
> Hi,
> 
> yes, this is a known thing. In order to make module federation work, we need to bootstrap the app asynchronously:
> 
> ```
> main.ts ---dynamic-import---> bootstrap.ts
> ```
> 
> However, some schematics assume that bootstrapping directly happens in main.ts. There is a schematic, that helps you turning async bootstrapping on and off:
> 
> ```
> ng g @angular-architects/module-federation:boot-async false --project yourProject
> 
> ng add your-libraries-of-chioce --project yourProject
> 
> ng g @angular-architects/module-federation:boot-async true --project yourProject
> ```

After changing from `main.ts` to `bootstrap.ts` and adding `ng add @angular/material --project yourProject`

Your project is not using the default builders for "build". The Angular Material schematics cannot add a theme to the workspace configuration if the builder has been changed.

**Comment by gokul-predigle** [comment]
I'm still facing this issue sir.
ng add @angular/material --project media-app 
Skipping installation: Package already installed
? Choose a prebuilt theme name, or "custom" for a custom theme: Custom
? Set up global Angular Material typography styles? Yes
? Include the Angular animations module? Include and enable animations
UPDATE package.json (1595 bytes)
✔ Packages installed successfully.
No project index HTML file could be found.

**Comment by p-aron** [comment]
I think this can help in your case.
https://github.com/nrwl/nx/issues/7621#issuecomment-972732294
If you change the executor in your project.json
"executor": "@nx/angular:webpack-browser" -> "executor": "@angular-devkit/build-angular:browser",
the schematics runs

**Comment by kashif-ali-khan** [comment]
> > Hi,
> > yes, this is a known thing. In order to make module federation work, we need to bootstrap the app asynchronously:
> > ```
> > main.ts ---dynamic-import---> bootstrap.ts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, some schematics assume that bootstrapping directly happens in main.ts. There is a schematic, that helps you turning async bootstrapping on and off:
> > ```
> > ng g @angular-architects/module-federation:boot-async false --project yourProject
> > 
> > ng add your-libraries-of-chioce --project yourProject
> > 
> > ng g @angular-architects/module-federation:boot-async true --project yourProject
> > ```
> 
> After changing from `main.ts` to `bootstrap.ts` and adding `ng add @angular/material --project yourProject`
> 
> Your project is not using the default builders for "build". The Angular Material schematics cannot add a theme to the workspace configuration if the builder has been changed.

Is your problem solved ?
